package de.vimotest.sandbox.context;

/*Generated by MPS */


public abstract class ContextReference_ViewTestSetup {
  public abstract void Init();
  public abstract void SetSimpleStringContext(String stringValue);
  public abstract ContextReference_View BuildSut();
}
