package de.vimotest.sandbox.context;

/*Generated by MPS */


public class ContextReference_ViewModelTestEnvironmentImpl extends ContextReference_ViewModelTestEnvironment {
  @Override
  public void Init() {
  }
  @Override
  public void SetSimpleStringContext(String stringValue) {
  }
  @Override
  public ContextReference_ViewModel BuildSut() {
    return null;
  }
}
