package de.vimotest.sandbox.context;

/*Generated by MPS */


public class ContextReference_ViewContextProviderImpl extends ContextReference_ViewContextProvider {
  public void Init() {
  }
  public void SetSimpleStringContext(String string) {
  }
  public ContextReference_View BuildSut() {
    return null;
  }
}
