package de.vimotest.sandbox.context;

/*Generated by MPS */


public class ContextReference_ViewTestSetupImpl extends ContextReference_ViewTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public void SetSimpleStringContext(String stringValue) {
  }
  @Override
  public ContextReference_View BuildSut() {
    return null;
  }
}
