package de.vimotest.sandbox.context;

/*Generated by MPS */


public abstract class DataTableContext_ViewContextProvider {
  public abstract void Init();
  public abstract void SetIdAndName(String string);
  public abstract void SetDataTableString(String string);
  public abstract void SetDataTableJson(String json);
  public abstract void SetDataTableXml(String xml);
  public abstract DataTableContext_View BuildSut();
}
