package de.vimotest.sandbox.context;

/*Generated by MPS */


public class DataPathContext_ViewTestSetupImpl extends DataPathContext_ViewTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public void SetDataPathContext(String contextPath) {
  }
  @Override
  public DataPathContext_View BuildSut() {
    return null;
  }
}
