package de.vimotest.sandbox.context;

/*Generated by MPS */


public class DataTableContext_ViewContextProviderImpl extends DataTableContext_ViewContextProvider {
  @Override
  public void Init() {
  }
  @Override
  public void SetIdAndName(String string) {
  }
  @Override
  public void SetDataTableString(String string) {
  }
  @Override
  public void SetDataTableJson(String json) {
  }
  @Override
  public void SetDataTableXml(String xml) {
  }
  @Override
  public DataTableContext_View BuildSut() {
    return null;
  }
}
