package de.vimotest.sandbox.context;

/*Generated by MPS */


public abstract class DataPathContext_ViewModelTestEnvironment {
  public abstract void Init();
  public abstract void SetDataPathContext(String contextPath);
  public abstract DataPathContext_ViewModel BuildSut();
}
