package de.vimotest.sandbox.context;

/*Generated by MPS */


public class DataPathContext_ViewContextProviderImpl extends DataPathContext_ViewContextProvider {
  @Override
  public void Init() {
  }
  @Override
  public void SetDataPathContext(String contextPath) {
  }
  @Override
  public DataPathContext_View BuildSut() {
    return null;
  }
}
