package de.vimotest.sandbox.context;

/*Generated by MPS */


public class DataPathContext_ViewModelTestSetupImpl extends DataPathContext_ViewModelTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public void SetDataPathContext(String contextPath) {
  }
  @Override
  public DataPathContext_ViewModel BuildSut() {
    return null;
  }

}
