package de.vimotest.sandbox.context;

/*Generated by MPS */


public class DataTableContext_ViewModelTestSetupImpl extends DataTableContext_ViewModelTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public void SetIdAndName(String multiLineString) {
  }
  @Override
  public void SetDataTableString(String multiLineString) {
  }
  @Override
  public void SetDataTableJson(String json) {
  }
  @Override
  public void SetDataTableXml(String xml) {
  }
  @Override
  public DataTableContext_ViewModel BuildSut() {
    return null;
  }

}
