package de.vimotest.sandbox.context;

/*Generated by MPS */


public abstract class StringContext_ViewModelTestEnvironment {
  public abstract void Init();
  public abstract void SetSimpleStringContext(String stringValue);
  public abstract StringContext_ViewModel BuildSut();
}
