package de.vimotest.sandbox.context;

/*Generated by MPS */


public class StringContext_ViewContextProviderImpl extends StringContext_ViewContextProvider {
  @Override
  public void Init() {
  }
  @Override
  public void SetSimpleStringContext(String string) {
  }
  @Override
  public StringContext_View BuildSut() {
    return null;
  }
}
