package de.vimotest.sandbox.context;

/*Generated by MPS */


public class StringContext_ViewModelTestEnvironmentImpl extends StringContext_ViewModelTestEnvironment {
  @Override
  public void Init() {
  }
  @Override
  public void SetSimpleStringContext(String stringValue) {
  }
  @Override
  public StringContext_ViewModel BuildSut() {
    return null;
  }
}
