package de.vimotest.sandbox.context;

/*Generated by MPS */


public abstract class StringContext_ViewTestSetup {
  public abstract void Init();
  public abstract void SetSimpleStringContext(String string);
  public abstract StringContext_View BuildSut();
}
