package de.vimotest.sandbox.context;

/*Generated by MPS */


public class XmlElementContext_ViewModelTestEnvironmentImpl extends XmlElementContext_ViewModelTestEnvironment {
  @Override
  public void Init() {
  }
  @Override
  public void SetXmlElementContext(String xml) {
  }
  @Override
  public XmlElementContext_ViewModel BuildSut() {
    return null;
  }
}
