package de.vimotest.sandbox.context;

/*Generated by MPS */


public class XmlElementContext_ViewContextProviderImpl extends XmlElementContext_ViewContextProvider {
  @Override
  public void Init() {
  }
  @Override
  public void SetXmlElementContext() {
  }
  @Override
  public XmlElementContext_View BuildSut() {
    return null;
  }
}
