package de.vimotest.sandbox.context;

/*Generated by MPS */


public abstract class XmlElementContext_ViewContextProvider {
  public abstract void Init();
  public abstract void SetXmlElementContext();
  public abstract XmlElementContext_View BuildSut();
}
