package de.vimotest.sandbox.context;

/*Generated by MPS */


public abstract class XmlElementContext_ViewModelTestEnvironment {
  public abstract void Init();
  public abstract void SetXmlElementContext(String xml);
  public abstract XmlElementContext_ViewModel BuildSut();
}
