package de.vimotest.sandbox.context;

/*Generated by MPS */


public class XmlFileContext_ViewModelTestEnvironmentImpl extends XmlFileContext_ViewModelTestEnvironment {
  @Override
  public void Init() {
  }
  @Override
  public void SetXmlFileContext(String xmlFileContent) {
  }
  @Override
  public void SetXmlExternalFileContext(String xmlFileName) {
  }
  @Override
  public XmlFileContext_ViewModel BuildSut() {
    return null;
  }
}
