package de.vimotest.sandbox.context;

/*Generated by MPS */


public class XmlFileContext_ViewTestSetupImpl extends XmlFileContext_ViewTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public void SetXmlFileContext(String xmlFileContent) {
  }
  @Override
  public void SetXmlExternalFileContext(String xmlFileName) {
  }
  @Override
  public XmlFileContext_View BuildSut() {
    return null;
  }
}
