package de.vimotest.sandbox.context;

/*Generated by MPS */


public abstract class XmlFileContext_ViewTestSetup {
  public abstract void Init();
  public abstract void SetXmlFileContext(String xmlFileContent);
  public abstract void SetXmlExternalFileContext(String xmlFileName);
  public abstract XmlFileContext_View BuildSut();
}
