package de.vimotest.sandbox.context;

/*Generated by MPS */


public class XmlFileContext_ViewContextProvider {
  public void Init() {
  }
  public void SetXmlFileContext(String xmlFileContent) {
  }
  public void SetXmlExternalFileContext(String xmlFileName) {
  }
  public XmlFileContext_View BuildSut() {
    return null;
  }
}
