package de.vimotest.sandbox.bindings.enumtostring;

/*Generated by MPS */

import de.vimotest.sandbox.bindings.CustomTypeInfoEnum;
import java.util.Objects;

/**
 * foo
 */
public class ConvertMyEnumToStr {
  public static String ConvertMyEnumToStr(CustomTypeInfoEnum symbol) {
    if (Objects.equals(symbol, CustomTypeInfoEnum.SymbolA)) {
      return "SymbolA";
    }
    if (Objects.equals(symbol, CustomTypeInfoEnum.SymbolB)) {
      return "SymbolB";
    }
    return "?";
  }
}
