package de.vimotest.generationConfig.separateViewModelController;

/*Generated by MPS */


public abstract class MyViewController {
  public void loadView() {
  }
  public void myFlagChecked(Boolean isChecked) {
  }
}
