package de.vimotest.generationConfig.separateViewModelController;

/*Generated by MPS */


public class SeparateViewController_ViewModelTestSetupImpl extends SeparateViewController_ViewModelTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public void SetEmptyContext() {
  }
  @Override
  public MyViewController BuildSutViewController() {
    return null;
  }
  @Override
  public MyViewModel GetViewModel() {
    return null;
  }
}
