package de.vimotest.generationConfig.separateViewModelController;

/*Generated by MPS */

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;

public class SeparateViewModelController_2_ViewTests_Test {
  private MyViewModel sutViewModel;
  private MyViewController sutViewController;
  private SeparateViewModelController_ViewModelTestSetup testSetup;
  @Test
  public void test_MyTest2_given_empty_context_when_LoadView_and_uncheck_MyFlag_then_() throws Exception {
    this.given_empty_context();
    this.BuildSut();
    this.when_LoadView();
    this.when_uncheck_MyFlag();
    this.RetrieveViewModel();
  }
  @BeforeEach
  public void setUp() {
    this.testSetup = new SeparateViewModelController_ViewModelTestSetupImpl();
    this.testSetup.Init();
  }



  protected void BuildSut() {
    this.sutViewController = this.testSetup.BuildSutViewController();
  }

  protected void RetrieveViewModel() {
    this.sutViewModel = this.testSetup.GetViewModel();
  }


  public void given_empty_context() {
  }


  public void when_LoadView() {
    this.sutViewController.loadView();
  }
  public void when_uncheck_MyFlag() {
    this.sutViewController.myFlagChecked(false);
  }


}
