package de.vimotest.generationConfig.separateViewModelController;

/*Generated by MPS */


public class SeparateViewModelController_ViewModelTestEnvironmentImpl extends SeparateViewModelController_ViewModelTestEnvironment {
  @Override
  public void Init() {
  }
  @Override
  public void SetEmptyContext() {
  }
  @Override
  public MyViewController BuildSutViewController() {
    return null;
  }
  @Override
  public MyViewModel GetViewModel() {
    return null;
  }
}
