package de.vimotest.sandbox.examples.login;

/*Generated by MPS */


public class LoginViewContextProvider {
  public void Init() {
  }
  public void SetEmptyContext() {
  }
  public void SetXmlElementContext() {
  }
  public LoginView BuildSut() {
    return null;
  }
}
