package de.vimotest.sandbox.datadriven;

/*Generated by MPS */


public abstract class DataDrivenViewModelTestEnvironment {
  public abstract void Init();
  public abstract DataDrivenViewModel BuildSut();
}
