package de.vimotest.sandbox.datadriven;

/*Generated by MPS */


public class DataDrivenViewModelTestEnvironmentImpl extends DataDrivenViewModelTestEnvironment {
  @Override
  public void Init() {
  }
  @Override
  public DataDrivenViewModel BuildSut() {
    return null;
  }
}
