package de.vimotest.sandbox.datadriven;

/*Generated by MPS */


public class DataDrivenViewModelResultRow {
  private String NameLabelText;
  public String getNameLabelText() {
    return this.NameLabelText;
  }
  private String IdLabelText;
  public String getIdLabelText() {
    return this.IdLabelText;
  }
  private String DescriptionLabelText;
  public String getDescriptionLabelText() {
    return this.DescriptionLabelText;
  }
  private String RowHandle;
  public String getRowHandle() {
    return this.RowHandle;
  }
}
