package de.vimotest.examples.loginview.de.vimotest.examples.loginview;

/*Generated by MPS */


public class LoginViewTestSetupImpl extends LoginViewTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public void SetEmptyContext() {
  }
  @Override
  public void SetXmlElementContext(String xml) {
  }
  @Override
  public LoginView BuildSut() {
    return null;
  }
}
