package de.vimotest.examples.loginview.de.vimotest.examples.loginview;

/*Generated by MPS */


public class LoginView {
  private String UsernameText;
  public String getUsernameText() {
    return this.UsernameText;
  }
  private String PasswordText;
  public String getPasswordText() {
    return this.PasswordText;
  }
  private Boolean isShowPasswordChecked;
  public Boolean getIsShowPasswordChecked() {
    return this.isShowPasswordChecked;
  }
  private Boolean isLoginEnabled;
  public Boolean getIsLoginEnabled() {
    return this.isLoginEnabled;
  }
  private String ErrorTextText;
  public String getErrorTextText() {
    return this.ErrorTextText;
  }
  private Boolean isErrorTextVisibility;
  public Boolean getIsErrorTextVisibility() {
    return this.isErrorTextVisibility;
  }
  public void LoadView() {
  }
  public void UsernameTextFilled(String text) {
  }
  public void PasswordTextFilled(String text) {
  }
  public void ShowPasswordChecked(Boolean isChecked) {
  }
  public void LoginClicked() {
  }
}
