package de.vimotest.generationConfig.commandActionHooks;

/*Generated by MPS */

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;

public class CommandActionHooks_ViewTests_Test {
  private CommandActionHooks_View sut;
  private CommandActionHooks_ViewContextProvider contextProvider;
  @Test
  public void test_MyTest_given_when_LoadView_and_uncheck_MyFlag_then_() throws Exception {
    this.BuildSut();
    this.when_LoadView();
    this.when_uncheck_MyFlag();
  }
  @BeforeEach
  public void setUp() {
    this.contextProvider = new CommandActionHooks_ViewContextProviderImpl();
    this.contextProvider.Init();
  }



  protected void BuildSut() {
    this.sut = this.contextProvider.BuildSut();
  }





  public void when_LoadView() {
    this.contextProvider.pre_loadView("A", true, 42);
    this.sut.loadView("A", true, 42);
  }
  public void when_uncheck_MyFlag() {
    this.sut.myFlagChecked(false);
  }


}
