package de.vimotest.generationConfig.separateViewController;

/*Generated by MPS */


public abstract class MyViewController {
  public void LoadView() {
  }
  public void MyCheckBoxChecked(Boolean isChecked) {
  }
}
