package de.vimotest.generationConfig.separateViewController;

/*Generated by MPS */


public abstract class MyViewController {
  public void loadView() {
  }
  public void myCheckBoxChecked(Boolean isChecked) {
  }
}
