package de.vimotest.generationConfig.separateViewController;

/*Generated by MPS */


public class MyViewModel {
  private Boolean isMyFlagCheckBoxChecked;
  public Boolean getIsMyFlagCheckBoxChecked() {
    return this.isMyFlagCheckBoxChecked;
  }
}
