package de.vimotest.generationConfig.separateViewController;

/*Generated by MPS */


public class SeparateViewController_ViewContextProviderImpl extends SeparateViewController_ViewContextProvider {
  public void Init() {
  }
  public void SetEmptyContext() {
  }
  public MyViewController BuildSutViewController() {
    return null;
  }
  public MyViewModel GetViewModel() {
    return null;
  }
}
