package de.vimotest.generationConfig.separateViewController;

/*Generated by MPS */


public abstract class SeparateViewController_ViewContextProvider {
  public abstract void Init();
  public abstract void SetEmptyContext();
  public abstract MyViewController BuildSutViewController();
  public abstract MyViewModel GetViewModel();
}
