package de.vimotest.sandbox.dependencies;

/*Generated by MPS */

import java.util.Objects;

/**
 * foo
 */
public class ConvertMyEnumToString {
  public static String convertMyEnumToString(MyEnum symbol) {
    if (Objects.equals(symbol, MyEnum.A)) {
      return "A";
    }
    if (Objects.equals(symbol, MyEnum.B)) {
      return "B";
    }
    return "?";
  }
}
