package de.vimotest.sandbox.dependencies;

/*Generated by MPS */


public class Dependency_ViewModelTestSetupImpl extends Dependency_ViewModelTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public Dependency_ViewModel BuildSut() {
    return null;
  }
}
