package de.vimotest.sandbox.dependencies;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;
import java.util.Objects;

public class LoggerSpy implements Logger {
  private Logger wrapped;

  public void setWrapped(Logger wrapped) {
    this.wrapped = wrapped;
  }

  public static class LogCallInfo {
    public String messageValue;
    public LogCallInfo() {
    }
    public LogCallInfo(String messageValue) {
      this.messageValue = messageValue;
    }
  }
  public static class LogMultipleCallInfo {
    public List<String> messagesValue = new LinkedList<>();
    public LogMultipleCallInfo() {
    }
    public LogMultipleCallInfo(List<String> messagesValue) {
      this.messagesValue = messagesValue;
    }
  }
  public List<LogCallInfo> LogCallInfos = new LinkedList<>();
  public List<LogMultipleCallInfo> LogMultipleCallInfos = new LinkedList<>();
  @Override
  public void Log(String message) {
    if (!(Objects.equals(this.wrapped, null))) {
      this.wrapped.Log(message);
    }
    LogCallInfo callInfo = new LogCallInfo();
    callInfo.messageValue = message;
    this.LogCallInfos.add(callInfo);
  }
  @Override
  public void LogMultiple(List<String> messages) {
    if (!(Objects.equals(this.wrapped, null))) {
      this.wrapped.LogMultiple(messages);
    }
    LogMultipleCallInfo callInfo = new LogMultipleCallInfo();
    callInfo.messagesValue = messages;
    this.LogMultipleCallInfos.add(callInfo);
  }
}
