package de.vimotest.sandbox.dependencies;

/*Generated by MPS */

import java.util.List;
import java.util.Map;

public interface Logger {
  void Log(String message);
  void LogMultiple(List<String> messages);
  Boolean LogWithResult(String message, MyEnum enumValue, Map<String, String> parameters);
}
