package de.vimotest.sandbox.dependencies;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;
import java.util.Objects;

public class LoggerSpy implements Logger {
  private Logger wrapped;

  public void setWrapped(Logger wrapped) {
    this.wrapped = wrapped;
  }

  public static class LogCalls {
    public String messageValue;
    public LogCalls() {
    }
    public LogCalls(String messageValue) {
      this.messageValue = messageValue;
    }
  }
  private List<LogCalls> calls = new LinkedList<>();
  @Override
  public void Log(String message) {
    if (!(Objects.equals(this.wrapped, null))) {
      this.wrapped.Log(message);
    }
    LogCalls callInfo = new LogCalls();
    callInfo.messageValue = message;
    this.calls.add(callInfo);
  }
}
