package de.vimotest.sandbox.dependencies;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;
import java.util.Map;
import java.util.Objects;

public class LoggerSpy implements Logger {
  private Logger wrapped;

  public void setWrapped(Logger wrapped) {
    this.wrapped = wrapped;
  }

  public static class LogCallInfo {
    public String messageValue;
    public LogCallInfo() {
    }
    public LogCallInfo(String messageValue) {
      this.messageValue = messageValue;
    }
  }
  public static class LogMultipleCallInfo {
    public List<String> messagesValue = new LinkedList<>();
    public LogMultipleCallInfo() {
    }
    public LogMultipleCallInfo(List<String> messagesValue) {
      this.messagesValue = messagesValue;
    }
  }
  public static class LogWithResultCallInfo {
    public String messageValue;
    public MyEnum enumValueValue;
    public Map<String, String> parametersValue;
    public LogWithResultCallInfo() {
    }
    public LogWithResultCallInfo(String messageValue, MyEnum enumValueValue, Map<String, String> parametersValue) {
      this.messageValue = messageValue;
      this.enumValueValue = enumValueValue;
      this.parametersValue = parametersValue;
    }
  }
  public List<LogCallInfo> LogCallInfos = new LinkedList<>();
  public List<LogMultipleCallInfo> LogMultipleCallInfos = new LinkedList<>();
  public List<LogWithResultCallInfo> LogWithResultCallInfos = new LinkedList<>();
  @Override
  public void Log(String message) {
    LogCallInfo callInfo = new LogCallInfo();
    callInfo.messageValue = message;
    this.LogCallInfos.add(callInfo);
    if (!(Objects.equals(this.wrapped, null))) {
      this.wrapped.Log(message);
    }
  }
  @Override
  public void LogMultiple(List<String> messages) {
    LogMultipleCallInfo callInfo = new LogMultipleCallInfo();
    callInfo.messagesValue = messages;
    this.LogMultipleCallInfos.add(callInfo);
    if (!(Objects.equals(this.wrapped, null))) {
      this.wrapped.LogMultiple(messages);
    }
  }
  @Override
  public Boolean LogWithResult(String message, MyEnum enumValue, Map<String, String> parameters) {
    LogWithResultCallInfo callInfo = new LogWithResultCallInfo();
    callInfo.messageValue = message;
    callInfo.enumValueValue = enumValue;
    callInfo.parametersValue = parameters;
    this.LogWithResultCallInfos.add(callInfo);
    if (!(Objects.equals(this.wrapped, null))) {
      return this.wrapped.LogWithResult(message, enumValue, parameters);
    }
    return false;
  }
}
