package de.vimotest.sandbox.dependencies;

/*Generated by MPS */

import java.util.List;

public interface MessageBus {
  void OnMessage(Integer messageId, List<String> names);
  void Foo(Boolean bar);
}
