package de.vimotest.sandbox.dependencies;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;
import java.util.Objects;

public class SimpleDependency_ViewModelSpy extends SimpleDependency_ViewModel {
  private SimpleDependency_ViewModel wrapped;

  public void setWrapped(SimpleDependency_ViewModel wrappedObject) {
    this.wrapped = wrappedObject;
  }

  public static class LoadViewModelCallInfo {
    public String PathValue;
    public LoadViewModelCallInfo() {
    }
    public LoadViewModelCallInfo(String PathValue) {
      this.PathValue = PathValue;
    }
  }
  public List<LoadViewModelCallInfo> LoadViewModelCallInfos = new LinkedList<>();
  public void LoadViewModel(String Path) {
    LoadViewModelCallInfo callInfo = new LoadViewModelCallInfo();
    callInfo.PathValue = Path;
    this.LoadViewModelCallInfos.add(callInfo);
    if (!(Objects.equals(this.wrapped, null))) {
      this.wrapped.loadViewModel(Path);
    }
  }
}
