package de.vimotest.sandbox.dependencies;

/*Generated by MPS */


public class SimpleDependency_ViewModel {
  private Boolean MyBool;
  public Boolean getMyBool() {
    return this.MyBool;
  }
  public void loadViewModel(String Path) {
  }
}
