package de.vimotest.sandbox.dependencies;

/*Generated by MPS */


public abstract class SimpleDependency_ViewModelTestSetup {
  public abstract void Init();
  public abstract SimpleDependency_ViewModel BuildSut();
}
