package de.vimotest.sandbox.dependencies;

/*Generated by MPS */


public class SimpleDependency_ViewModelTestSetupImpl extends SimpleDependency_ViewModelTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public SimpleDependency_ViewModel BuildSut() {
    return null;
  }
  @Override
  public MessageBus getMessageBus() {
    return null;
  }
  @Override
  public LoggerSpy getLogger() {
    return null;
  }
}
