package de.vimotest.sandbox.dependencies;

/*Generated by MPS */


public abstract class SimpleDependency_ViewModelTestEnvironment {
  public abstract void Init();
  public abstract SimpleDependency_ViewModel BuildSut();
  public abstract MessageBus getMessageBus();
  public abstract LoggerSpy getLogger();
}
