package de.vimotest.sandbox.dependencies;

/*Generated by MPS */

import java.util.List;

public interface ViewDependencyView {
  void Refresh();
  Boolean ConfirmDeletion();
  MyEnum AskForEnum();
  List<String> GetSomeResultList(String scope);
}
