package de.vimotest.sandbox.dependencies;

/*Generated by MPS */


public abstract class ViewModelDependency_ViewModelTestEnvironment {
  public abstract void Init();
  public abstract ViewModelDependency_ViewModel BuildSut();
  public abstract ViewModelDependency_ViewModel getSimpleDependency_ViewModel();
}
