package de.vimotest.sandbox.dependencies;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;
import java.util.Objects;

public class ViewDependencyViewSpy implements ViewDependencyView {
  private ViewDependencyView wrapped;

  public void setWrapped(ViewDependencyView wrappedObject) {
    this.wrapped = wrappedObject;
  }

  public static class RefreshCallInfo {
    public RefreshCallInfo() {
    }
  }
  public static class ConfirmDeletionCallInfo {
    public ConfirmDeletionCallInfo() {
    }
  }
  public static class AskForEnumCallInfo {
    public AskForEnumCallInfo() {
    }
  }
  public static class GetSomeResultListCallInfo {
    public String scopeValue;
    public GetSomeResultListCallInfo() {
    }
    public GetSomeResultListCallInfo(String scopeValue) {
      this.scopeValue = scopeValue;
    }
  }
  public static class ShowErrorCallInfo {
    public String errorMessageValue;
    public ShowErrorCallInfo() {
    }
    public ShowErrorCallInfo(String errorMessageValue) {
      this.errorMessageValue = errorMessageValue;
    }
  }
  public List<RefreshCallInfo> RefreshCallInfos = new LinkedList<>();
  public List<ConfirmDeletionCallInfo> ConfirmDeletionCallInfos = new LinkedList<>();
  public List<AskForEnumCallInfo> AskForEnumCallInfos = new LinkedList<>();
  public List<GetSomeResultListCallInfo> GetSomeResultListCallInfos = new LinkedList<>();
  public List<ShowErrorCallInfo> ShowErrorCallInfos = new LinkedList<>();
  @Override
  public void Refresh() {
    RefreshCallInfo callInfo = new RefreshCallInfo();
    this.RefreshCallInfos.add(callInfo);
    if (!(Objects.equals(this.wrapped, null))) {
      this.wrapped.Refresh();
    }
  }
  @Override
  public Boolean ConfirmDeletion() {
    ConfirmDeletionCallInfo callInfo = new ConfirmDeletionCallInfo();
    this.ConfirmDeletionCallInfos.add(callInfo);
    if (!(Objects.equals(this.wrapped, null))) {
      return this.wrapped.ConfirmDeletion();
    }
    return false;
  }
  @Override
  public MyEnum AskForEnum() {
    AskForEnumCallInfo callInfo = new AskForEnumCallInfo();
    this.AskForEnumCallInfos.add(callInfo);
    if (!(Objects.equals(this.wrapped, null))) {
      return this.wrapped.AskForEnum();
    }
    return null;
  }
  @Override
  public List<String> GetSomeResultList(String scope) {
    GetSomeResultListCallInfo callInfo = new GetSomeResultListCallInfo();
    callInfo.scopeValue = scope;
    this.GetSomeResultListCallInfos.add(callInfo);
    if (!(Objects.equals(this.wrapped, null))) {
      return this.wrapped.GetSomeResultList(scope);
    }
    return null;
  }
  @Override
  public void ShowError(String errorMessage) {
    ShowErrorCallInfo callInfo = new ShowErrorCallInfo();
    callInfo.errorMessageValue = errorMessage;
    this.ShowErrorCallInfos.add(callInfo);
    if (!(Objects.equals(this.wrapped, null))) {
      this.wrapped.ShowError(errorMessage);
    }
  }
}
