package de.vimotest.sandbox.dependencies;

/*Generated by MPS */


public class ViewDependencyViewModelTestEnvironmentImpl extends ViewDependencyViewModelTestEnvironment {
  @Override
  public void Init() {
  }
  @Override
  public ViewDependencyViewModel BuildSut() {
    return null;
  }
  @Override
  public ViewDependencyView getViewDependencyView() {
    return null;
  }
}
