package de.vimotest.sandbox.dependencies;

/*Generated by MPS */


public abstract class ViewModelDependency_ViewModelTestSetup {
  public abstract void Init();
  public abstract ViewModelDependency_ViewModel BuildSut();
}
