package de.vimotest.generationConfig.recordAsClass;

/*Generated by MPS */

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.Assert;

public class RecordAsClass_ViewTests_Test {
  private RecordAsClass_ViewModel sut;
  private RecordAsClass_ViewModelTestEnvironment testEnvironment;
  @Test
  public void test_MyTest_given_empty_context_when_then_Object_is_todo_recordpattern() throws Exception {
    this.given_empty_context();
    this.BuildSut();
    this.then_Object_is_todo_recordpattern();
  }
  @BeforeEach
  public void setUp() {
    this.testEnvironment = new RecordAsClass_ViewModelTestEnvironmentImpl();
    this.testEnvironment.Init();
  }



  protected void BuildSut() {
    this.sut = this.testEnvironment.BuildSut();
  }



  public void given_empty_context() {
  }




  public void then_Object_is_todo_recordpattern() {
    MyRecordObject actualMyRecordObject = this.sut.getObject();
    Assert.assertTrue("Expected field 'Flag' has boolean value <true>, but it was <" + ((actualMyRecordObject.getFlag() ? "true" : "false")) + ">", actualMyRecordObject.getFlag());
  }
}
