package de.vimotest.generationConfig.recordAsClass;

/*Generated by MPS */


public class RecordAsClass_ViewModelTestEnvironmentImpl extends RecordAsClass_ViewModelTestEnvironment {
  @Override
  public void Init() {
  }
  @Override
  public void SetEmptyContext() {
  }
  @Override
  public RecordAsClass_ViewModel BuildSut() {
    return null;
  }
}
