package de.vimotest.generationConfig.recordAsClass;

/*Generated by MPS */


public abstract class RecordAsClass_ViewModelTestEnvironment {
  public abstract void Init();
  public abstract void SetEmptyContext();
  public abstract RecordAsClass_ViewModel BuildSut();
}
