package de.vimotest.sandbox.dependencies.calls;

/*Generated by MPS */

import de.vimotest.sandbox.dependencies.LoggerSpy;

public class VerifyDependencyCallViewModelTestSetupImpl extends VerifyDependencyCallViewModelTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public VerifyDependencyCallViewModel BuildSut() {
    return null;
  }
  @Override
  public LoggerSpy getLogger() {
    return null;
  }
  @Override
  public VerifyDependencyCallViewModel getSimpleDependency_ViewModel() {
    return null;
  }
}
