package de.vimotest.sandbox.dependencies.calls;

/*Generated by MPS */

import de.vimotest.sandbox.dependencies.LoggerSpy;
import de.vimotest.sandbox.dependencies.SimpleDependency_ViewModel;

public class VerifyDependencyCallViewModelTestEnvironmentImpl extends VerifyDependencyCallViewModelTestEnvironment {
  @Override
  public void Init() {
  }
  @Override
  public VerifyDependencyCallViewModel BuildSut() {
    return null;
  }
  @Override
  public LoggerSpy getLogger() {
    return null;
  }
  @Override
  public SimpleDependency_ViewModel getSimpleDependency_ViewModel() {
    return null;
  }
}
