package de.vimotest.sandbox.dependencies.calls;

/*Generated by MPS */

import de.vimotest.sandbox.dependencies.LoggerSpy;

public abstract class VerifyDependencyCallViewModelTestSetup {
  public abstract void Init();
  public abstract VerifyDependencyCallViewModel BuildSut();
  public abstract LoggerSpy getLogger();
  public abstract VerifyDependencyCallViewModel getSimpleDependency_ViewModel();
}
