package de.vimotest.sandbox.dependencies.calls;

/*Generated by MPS */

import de.vimotest.sandbox.dependencies.LoggerSpy;
import de.vimotest.sandbox.dependencies.SimpleDependency_ViewModelSpy;

public abstract class VerifyDependencyCallViewModelTestEnvironment {
  public abstract void Init();
  public abstract VerifyDependencyCallViewModel BuildSut();
  public abstract LoggerSpy getLogger();
  public abstract SimpleDependency_ViewModelSpy getSimpleDependency_ViewModel();
}
