package de.vimotest.examples.taskview;

/*Generated by MPS */


public class TaskListViewModelContextProvider {
  public void Init() {
  }
  public void SetDataTableJson(String json) {
  }
  public void SetSimpleStringContext(String string) {
  }
  public TaskListViewModel BuildSut() {
    return null;
  }
}
