package de.vimotest.examples.taskview;

/*Generated by MPS */


public abstract class TaskListViewModelTasksRow {
  public abstract String getPriorityImageSource();
  public abstract String getTask_NameText();
  public abstract String getDue_DateText();
  public abstract String getRowHandle();
}
