package de.vimotest.generationConfig.parameterObject;

/*Generated by MPS */

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;

public class ParameterObjectCommand_ViewTests_Test {
  private ParameterObjectCommand_ViewModel sut;
  private ParameterObjectCommand_ViewModelTestSetup testSetup;
  @Test
  public void test_MyTest_given_empty_context_when_LoadView_and_uncheck_MyFlag_then_() throws Exception {
    this.given_empty_context();
    this.BuildSut();
    this.when_LoadView();
    this.when_uncheck_MyFlag();
  }
  @BeforeEach
  public void setUp() {
    this.testSetup = new ParameterObjectCommand_ViewModelTestSetupImpl();
    this.testSetup.Init();
  }



  protected void BuildSut() {
    this.sut = this.testSetup.BuildSut();
  }



  public void given_empty_context() {
  }


  public void when_LoadView() {
    ParameterObjectCommand_ViewModel.LoadViewParams loadViewParameters = new ParameterObjectCommand_ViewModel.LoadViewParams("A", true, 42);
    this.sut.loadView(loadViewParameters);
  }
  public void when_uncheck_MyFlag() {
    ParameterObjectCommand_ViewModel.CheckParams checkedParameters = new ParameterObjectCommand_ViewModel.CheckParams(false);
    this.sut.myFlagChecked(checkedParameters);
  }


}
