package de.vimotest.generationConfig.parameterObject;

/*Generated by MPS */


public abstract class ParameterObjectCommand_ViewModelTestEnvironment {
  public abstract void Init();
  public abstract void SetEmptyContext();
  public abstract ParameterObjectCommand_ViewModel BuildSut();
}
