package de.vimotest.generationConfig.parameterObject;

/*Generated by MPS */


public class ParameterObjectCommand_ViewModelTestEnvironmentImpl extends ParameterObjectCommand_ViewModelTestEnvironment {
  @Override
  public void Init() {
  }
  @Override
  public void SetEmptyContext() {
  }
  @Override
  public ParameterObjectCommand_ViewModel BuildSut() {
    return null;
  }
}
