package de.vimotest.sandbox.dependencies.subscope;

/*Generated by MPS */


public class RepeatUsageDependency_ViewModel {
  public Boolean MyBool;
  public Boolean getMyBool() {
    return this.MyBool;
  }
  public void loadView() {
  }
}
