package de.vimotest.sandbox.dependencies.subscope;

/*Generated by MPS */

import de.vimotest.sandbox.dependencies.Logger;

public class RepeatUsageDependency_ViewModelTestSetupImpl extends RepeatUsageDependency_ViewModelTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public RepeatUsageDependency_ViewModel BuildSut() {
    return null;
  }
  @Override
  public MessageBus getMessageBus() {
    return null;
  }
  @Override
  public Logger getLogger() {
    return null;
  }
}
