package de.vimotest.sandbox.dependencies.subscope;

/*Generated by MPS */

import de.vimotest.sandbox.dependencies.LoggerSpy;

public abstract class RepeatUsageDependency_ViewModelTestEnvironment {
  public abstract void Init();
  public abstract RepeatUsageDependency_ViewModel BuildSut();
  public abstract MessageBus getMessageBus();
  public abstract LoggerSpy getLogger();
}
