package de.vimotest.sandbox.dependencies.subscope;

/*Generated by MPS */


public class RepeatUsageDependency_ViewModel {
  private Boolean MyBool;
  public Boolean getMyBool() {
    return this.MyBool;
  }
  public void loadViewModel() {
  }
}
