package de.vimotest.generationConfig.capitalizedGetterSetterNames;

/*Generated by MPS */


public class CapitalizedGetterNames_ViewMyElementsRow {
  private String HeaderLabelText;
  public String GetHeaderLabelText() {
    return this.HeaderLabelText;
  }
  private Integer myRowHandle;
  public Integer GetMyRowHandle() {
    return this.myRowHandle;
  }
}
