package de.vimotest.generationConfig.capitalizedGetterSetterNames;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public class CapitalizedGetterNames_View {
  private Boolean isMyFlagCheckBoxChecked;
  public Boolean GetIsMyFlagCheckBoxChecked() {
    return this.isMyFlagCheckBoxChecked;
  }
  private Boolean myVisibility;
  public Boolean GetMyVisibility() {
    return this.myVisibility;
  }
  private Boolean isMyFlagCheckBoxEnabled;
  public Boolean GetIsMyFlagCheckBoxEnabled() {
    return this.isMyFlagCheckBoxEnabled;
  }
  private String MyFlagCheckBoxText;
  public String GetMyFlagCheckBoxText() {
    return this.MyFlagCheckBoxText;
  }
  private List<CapitalizedGetterNames_ViewMyElementsRow> myRows = new LinkedList<>();
  public List<CapitalizedGetterNames_ViewMyElementsRow> GetMyRows() {
    return this.myRows;
  }
}
