package de.vimotest.generationConfig.capitalizedGetterSetterNames;

/*Generated by MPS */


public class CapitalizedGetterNames_ViewListViewRow {
  private String HeaderText;
  public String GetHeaderText() {
    return this.HeaderText;
  }
  private Integer myRowHandle;
  public Integer GetMyRowHandle() {
    return this.myRowHandle;
  }
}
