package de.vimotest.examples.loginview;

/*Generated by MPS */

import de.vimotest.examples.loginview.de.vimotest.examples.loginview.LoginViewModel;
import de.vimotest.examples.loginview.de.vimotest.examples.loginview.LoginViewModelTestSetup;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import de.vimotest.examples.loginview.de.vimotest.examples.loginview.LoginViewModelTestSetupImpl;
import org.junit.Assert;

public class LoginViewModelTests_Test {
  private LoginViewModel sut;
  private LoginViewModelTestSetup testSetup;
  private String prefilledValues = "<Prefs>  \n  <User>Ada</User>\n  <Pw>Lovelace1</Pw>\n</Prefs>";
  @Test
  public void test_Load_View_on_empty_context_given_empty_context_when_LoadView_and_fill_User_in_Username_and_fill_MyPass123_in_Password_and_check_ShowPassword_then_Username_shows_text_User_and_Password_shows_text_MyPass123_and_Login_is_enabled() throws Exception {
    this.given_empty_context();
    this.BuildSut();
    this.when_LoadView();
    this.when_fill_User_in_Username();
    this.when_fill_MyPass123_in_Password();
    this.when_check_ShowPassword();
    this.then_Username_shows_text_User_();
    this.then_Password_shows_text_MyPass123_();
    this.then_Login_is_enabled();
  }
  @Test
  public void test_Load_View_on_empty_context_given_empty_context_when_LoadView_and_fill_User_in_Username_and_clear_text_in_Password_then_Username_shows_text_User_and_Password_shows_empty_text_and_Login_is_not_enabled() throws Exception {
    this.given_empty_context();
    this.BuildSut();
    this.when_LoadView();
    this.when_fill_User_in_Username();
    this.when_clear_text_in_Password();
    this.then_Username_shows_text_User_();
    this.then_Password_shows_empty_text();
    this.then_Login_is_not_enabled();
  }
  @Test
  public void test_Load_View_on_Pre_filled_User_Preferences_given_prefilledValues_when_LoadView_then_Username_shows_text_Ada_and_Password_shows_text_____and_Login_is_enabled() throws Exception {
    this.given_prefilledValues();
    this.BuildSut();
    this.when_LoadView();
    this.then_Username_shows_text_Ada_();
    this.then_Password_shows_text_____();
    this.then_Login_is_enabled();
  }
  @Test
  public void test_Load_View_on_Pre_filled_User_Preferences_given_prefilledValues_when_LoadView_and_check_ShowPassword_then_Username_shows_text_Ada_and_Password_shows_text_Lovelace1_and_ShowPassword_is_checked_and_Login_is_enabled() throws Exception {
    this.given_prefilledValues();
    this.BuildSut();
    this.when_LoadView();
    this.when_check_ShowPassword();
    this.then_Username_shows_text_Ada_();
    this.then_Password_shows_text_Lovelace1_();
    this.then_ShowPassword_is_checked();
    this.then_Login_is_enabled();
  }
  @Test
  public void test_Load_View_on_Pre_filled_User_Preferences_given_prefilledValues_when_LoadView_and_fill_lovelace_in_Password_and_click_Login_then_Error_shows_text_Needs_uppercase_letters_() throws Exception {
    this.given_prefilledValues();
    this.BuildSut();
    this.when_LoadView();
    this.when_fill_lovelace_in_Password();
    this.when_click_Login();
    this.then_Error_shows_text_Needs_uppercase_letters_();
  }
  @BeforeEach
  public void setUp() {
    this.testSetup = new LoginViewModelTestSetupImpl();
    this.testSetup.Init();
  }



  protected void BuildSut() {
    this.sut = this.testSetup.BuildSut();
  }



  public void given_empty_context() {
  }
  public void given_prefilledValues() {
    this.testSetup.SetXmlElementContext(this.prefilledValues);
  }


  public void when_LoadView() {
    this.sut.loadView();
  }
  public void when_fill_User_in_Username() {
    this.sut.usernameTextFilled("User");
  }
  public void when_fill_MyPass123_in_Password() {
    this.sut.passwordTextFilled("MyPass123");
  }
  public void when_check_ShowPassword() {
    this.sut.showPasswordChecked(true);
  }
  public void when_clear_text_in_Password() {
    this.sut.passwordTextFilled("");
  }
  public void when_fill_lovelace_in_Password() {
    this.sut.passwordTextFilled("lovelace");
  }
  public void when_click_Login() {
    this.sut.loginClicked();
  }


  public void then_Username_shows_text_User_() {
    Assert.assertEquals("User", this.sut.getUsernameTextBoxText());
  }
  public void then_Password_shows_text_MyPass123_() {
    Assert.assertEquals("MyPass123", this.sut.getPasswordTextBoxText());
  }
  public void then_Login_is_enabled() {
    Assert.assertTrue(this.sut.getIsLoginButtonEnabled());
  }
  public void then_Password_shows_empty_text() {
    Assert.assertEquals("", this.sut.getPasswordTextBoxText());
  }
  public void then_Login_is_not_enabled() {
    Assert.assertFalse(this.sut.getIsLoginButtonEnabled());
  }
  public void then_Username_shows_text_Ada_() {
    Assert.assertEquals("Ada", this.sut.getUsernameTextBoxText());
  }
  public void then_Password_shows_text_____() {
    Assert.assertEquals("******", this.sut.getPasswordTextBoxText());
  }
  public void then_Password_shows_text_Lovelace1_() {
    Assert.assertEquals("Lovelace1", this.sut.getPasswordTextBoxText());
  }
  public void then_ShowPassword_is_checked() {
    Assert.assertTrue(this.sut.getIsShowPasswordCheckBoxChecked());
  }
  public void then_Error_shows_text_Needs_uppercase_letters_() {
    Assert.assertEquals("Needs uppercase letters", this.sut.getErrorLabelText());
  }
}
