package de.vimotest.sandbox.bindings;

/*Generated by MPS */


public class MyCustomRow {
  private String RowText;
  public String GetRowText() {
    return this.RowText;
  }
  private Integer handle;
  public Integer getHandle() {
    return this.handle;
  }
  private Integer level;
  public Integer getLevel() {
    return this.level;
  }
}
