package de.vimotest.sandbox.bindings;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public class NameBinding_View {
  private String mText;
  public String getCustomText() {
    return this.mText;
  }
  private Boolean mEnabled;
  public Boolean getCustomEnabled() {
    return this.mEnabled;
  }
  private List<MyCustomRow> rows = new LinkedList<>();
  public List<MyCustomRow> getRows() {
    return this.rows;
  }
  private Boolean updatingFlag;
  public Boolean getUpdatingFlag() {
    return this.updatingFlag;
  }
  public void LoadView() {
  }
  public void OkClicked() {
  }
}
