package de.vimotest.sandbox.bindings;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public class ViMoTestFileNameBinding {
  private List<ViMoTestFileNameBindingMyTableViewRow> MyTableViewWidgetTableRows = new LinkedList<>();
  public List<ViMoTestFileNameBindingMyTableViewRow> getMyTableViewWidgetTableRows() {
    return this.MyTableViewWidgetTableRows;
  }
  private Boolean isMyTableViewUpdatingRowsFlag;
  public Boolean getIsMyTableViewUpdatingRowsFlag() {
    return this.isMyTableViewUpdatingRowsFlag;
  }
  public void LoadView() {
  }
}
