package de.vimotest.sandbox.bindings;

/*Generated by MPS */


public class ViMoTestFileNameBindingMyTableViewRow {
  private String columnCellText;
  public String getColumnCellText() {
    return this.columnCellText;
  }
  private Integer RowIndex;
  public Integer getRowIndex() {
    return this.RowIndex;
  }
}
