package de.vimotest.sandbox.bindings;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public class ViMoTestFileNameBinding {
  private List<ViMoTestFileNameBindingMyElementsRow> MyElementsTableWidgetTableRows = new LinkedList<>();
  public List<ViMoTestFileNameBindingMyElementsRow> getMyElementsTableWidgetTableRows() {
    return this.MyElementsTableWidgetTableRows;
  }
  public void loadView() {
  }
}
