package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.widgetassertions.Buttons_ViewModel;
import de.vimotest.sandbox.widgetassertions.Buttons_ViewModelTestEnvironment;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import de.vimotest.sandbox.widgetassertions.Buttons_ViewModelTestEnvironmentImpl;
import org.junit.Assert;

public class Buttons_ViewTests_Test {
  private Buttons_ViewModel sut;
  private Buttons_ViewModelTestEnvironment testEnvironment;
  @Test
  public void test_My_Scenario_given_empty_context_when_then_Ok_is_enabled_and_is_visible_and_shows_text_Test_() throws Exception {
    this.given_empty_context();
    this.BuildSut();
    this.then_Ok_is_enabled_and_is_visible_and_shows_text_Test_();
  }
  @Test
  public void test_My_Scenario_given_empty_context_when_then_Ok_is_not_enabled_and_is_visible_and_shows_text_Test_() throws Exception {
    this.given_empty_context();
    this.BuildSut();
    this.then_Ok_is_not_enabled_and_is_visible_and_shows_text_Test_();
  }
  @Test
  public void test_My_Scenario_given_empty_context_when_then_Ok_is_enabled_and_is_not_visible_and_shows_text_Test_() throws Exception {
    this.given_empty_context();
    this.BuildSut();
    this.then_Ok_is_enabled_and_is_not_visible_and_shows_text_Test_();
  }
  @BeforeEach
  public void setUp() {
    this.testEnvironment = new Buttons_ViewModelTestEnvironmentImpl();
    this.testEnvironment.Init();
  }



  protected void BuildSut() {
    this.sut = this.testEnvironment.BuildSut();
  }



  public void given_empty_context() {
  }




  public void then_Ok_is_enabled_and_is_visible_and_shows_text_Test_() {
    Assert.assertTrue(this.sut.getIsOkButtonEnabled());
    Assert.assertTrue(this.sut.getIsOkButtonVisible());
    Assert.assertEquals("Test", this.sut.getOkButtonText());
  }
  public void then_Ok_is_not_enabled_and_is_visible_and_shows_text_Test_() {
    Assert.assertFalse(this.sut.getIsOkButtonEnabled());
    Assert.assertTrue(this.sut.getIsOkButtonVisible());
    Assert.assertEquals("Test", this.sut.getOkButtonText());
  }
  public void then_Ok_is_enabled_and_is_not_visible_and_shows_text_Test_() {
    Assert.assertTrue(this.sut.getIsOkButtonEnabled());
    Assert.assertFalse(this.sut.getIsOkButtonVisible());
    Assert.assertEquals("Test", this.sut.getOkButtonText());
  }
}
