package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.commands.CheckCommand_ViewModel;
import de.vimotest.sandbox.commands.CheckCommand_ViewModelTestSetup;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import de.vimotest.sandbox.commands.CheckCommand_ViewModelTestSetupImpl;

public class CheckCommand_ViewTests_Test {
  private CheckCommand_ViewModel sut;
  private CheckCommand_ViewModelTestSetup testSetup;
  @Test
  public void test_Check_CheckBox_given_when_check_MyCheckBox1_and_uncheck_MyCheckBox2_then_() throws Exception {
    this.BuildSut();
    this.when_check_MyCheckBox1();
    this.when_uncheck_MyCheckBox2();
  }
  @BeforeEach
  public void setUp() {
    this.testSetup = new CheckCommand_ViewModelTestSetupImpl();
    this.testSetup.Init();
  }



  protected void BuildSut() {
    this.sut = this.testSetup.BuildSut();
  }





  public void when_check_MyCheckBox1() {
    this.sut.myCheckBox1Checked(true);
  }
  public void when_uncheck_MyCheckBox2() {
    this.sut.myCheckBox2Checked(false);
  }


}
