package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.commands.CheckCommand_View;
import de.vimotest.sandbox.commands.CheckCommand_ViewContextProvider;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import de.vimotest.sandbox.commands.CheckCommand_ViewContextProviderImpl;

public class CheckCommand_ViewTests_Test {
  private CheckCommand_View sut;
  private CheckCommand_ViewContextProvider contextProvider;
  @Test
  public void test_Check_CheckBox_given_when_check_MyCheckBox1_and_uncheck_MyCheckBox2_then_() throws Exception {
    this.BuildSut();
    this.when_check_MyCheckBox1();
    this.when_uncheck_MyCheckBox2();
  }
  @BeforeEach
  public void setUp() {
    this.contextProvider = new CheckCommand_ViewContextProviderImpl();
    this.contextProvider.Init();
  }



  protected void BuildSut() {
    this.sut = this.contextProvider.BuildSut();
  }





  public void when_check_MyCheckBox1() {
    this.sut.myCheckBox1Checked(true);
  }
  public void when_uncheck_MyCheckBox2() {
    this.sut.myCheckBox2Checked(false);
  }


}
