package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.commands.ClickCommand_View;
import de.vimotest.sandbox.commands.ClickCommand_ViewContextProvider;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import de.vimotest.sandbox.commands.ClickCommand_ViewContextProviderImpl;

public class ClickCommand_ViewTests_Test {
  private ClickCommand_View sut;
  private ClickCommand_ViewContextProvider contextProvider;
  @Test
  public void test_Click_Button_given_when_click_Ok_then_() throws Exception {
    this.BuildSut();
    this.when_click_Ok();
  }
  @BeforeEach
  public void setUp() {
    this.contextProvider = new ClickCommand_ViewContextProviderImpl();
    this.contextProvider.Init();
  }



  protected void BuildSut() {
    this.sut = this.contextProvider.BuildSut();
  }





  public void when_click_Ok() {
    this.sut.okClicked();
  }


}
