package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.context.ContextReference_View;
import de.vimotest.sandbox.context.ContextReference_ViewContextProvider;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;

public class ContextReference_ViewTests_Test {
  private ContextReference_View sut;
  private ContextReference_ViewContextProvider contextProvider;
  private String base = "My Context";
  @Test
  public void test_String_Context_given_base_when_then_() throws Exception {
    this.given_base();
    this.BuildSut();
  }
  @Test
  public void test_Context_Reference_given_base_when_then_() throws Exception {
    this.given_base1();
    this.BuildSut();
  }
  @BeforeEach
  public void setUp() {
    this.contextProvider = new ContextReference_ViewContextProvider();
    this.contextProvider.Init();
  }



  protected void BuildSut() {
    this.sut = this.contextProvider.BuildSut();
  }



  public void given_base() {
    this.contextProvider.SetSimpleStringContext(this.base);
  }
  public void given_base1() {
    this.contextProvider.SetSimpleStringContext(this.base);
  }




}
