package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.context.ContextReference_View;
import de.vimotest.sandbox.context.ContextReference_ViewTestSetup;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import de.vimotest.sandbox.context.ContextReference_ViewTestSetupImpl;

public class ContextReference_View_ContextReference_ViewTests_OtherSuite_Tests_Test {
  private ContextReference_View sut;
  private ContextReference_ViewTestSetup testSetup;
  private String base = "My Context";
  @Test
  public void test__1st_Context_Reference_from_other_suite_given_base_when_then_() throws Exception {
    this.given_base();
    this.BuildSut();
  }
  @Test
  public void test__2nd_Context_Reference_from_other_suite_given_base_when_then_() throws Exception {
    this.given_base_1();
    this.BuildSut();
  }
  @BeforeEach
  public void setUp() {
    this.testSetup = new ContextReference_ViewTestSetupImpl();
    this.testSetup.Init();
  }



  protected void BuildSut() {
    this.sut = this.testSetup.BuildSut();
  }



  public void given_base() {
    this.testSetup.SetSimpleStringContext(this.base);
  }
  public void given_base_1() {
    this.testSetup.SetSimpleStringContext(this.base);
  }




}
