package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.context.ContextReference_ViewModel;
import de.vimotest.sandbox.context.ContextReference_ViewModelTestSetup;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import de.vimotest.sandbox.context.ContextReference_ViewModelTestSetupImpl;

public class ContextReference_ViewTests_Test {
  private ContextReference_ViewModel sut;
  private ContextReference_ViewModelTestSetup testSetup;
  private String baseContext = "My Context";
  @Test
  public void test_String_Context_given_baseContext_when_then_() throws Exception {
    this.given_baseContext();
    this.BuildSut();
  }
  @Test
  public void test_Context_Reference_given_baseContext_when_then_() throws Exception {
    this.given_baseContext_1();
    this.BuildSut();
  }
  @BeforeEach
  public void setUp() {
    this.testSetup = new ContextReference_ViewModelTestSetupImpl();
    this.testSetup.Init();
  }



  protected void BuildSut() {
    this.sut = this.testSetup.BuildSut();
  }



  public void given_baseContext() {
    this.testSetup.SetSimpleStringContext(this.baseContext);
  }
  public void given_baseContext_1() {
    this.testSetup.SetSimpleStringContext(this.baseContext);
  }




}
