package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.context.DataTableContext_View;
import de.vimotest.sandbox.context.DataTableContext_ViewTestSetup;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import de.vimotest.sandbox.context.DataTableContext_ViewTestSetupImpl;

public class DataTableContext_View_DataTableContext_ViewTests_Naming_Tests_Test {
  private DataTableContext_View sut;
  private DataTableContext_ViewTestSetup testSetup;
  private String id_0_name_A = "| id | name |\n| 0 | A |";
  private String data = "| id | name |\n| 0 | A |";
  private String data1 = "| id | name |\n| 0 | A |";
  @Test
  public void test_DataTable_Context_implicit_name_given_id_0_name_A_when_then_() throws Exception {
    this.given_id_0_name_A();
    this.BuildSut();
  }
  @Test
  public void test_DataTable_Context_two_objects_equal_contents_given_data_and_data1_when_then_() throws Exception {
    this.given_data();
    this.given_data1();
    this.BuildSut();
  }
  @Test
  public void test_DataTable_Context_duplicate_name_from_other_test_given_data_when_then_() throws Exception {
    this.given_data();
    this.BuildSut();
  }
  @Test
  public void test_DataTable_Context_Ref_duplicate_name_from_other_test_given_data_when_then_() throws Exception {
    this.given_data_1();
    this.BuildSut();
  }
  @BeforeEach
  public void setUp() {
    this.testSetup = new DataTableContext_ViewTestSetupImpl();
    this.testSetup.Init();
  }



  protected void BuildSut() {
    this.sut = this.testSetup.BuildSut();
  }



  public void given_id_0_name_A() {
    this.testSetup.SetDataTableString(this.id_0_name_A);
  }
  public void given_data() {
    this.testSetup.SetDataTableString(this.data);
  }
  public void given_data1() {
    this.testSetup.SetDataTableString(this.data1);
  }
  public void given_data_1() {
    this.testSetup.SetDataTableString(this.data);
  }




}
