package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.context.DataTableContext_ViewModel;
import de.vimotest.sandbox.context.DataTableContext_ViewModelTestEnvironment;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import de.vimotest.sandbox.context.DataTableContext_ViewModelTestEnvironmentImpl;

public class DataTableContext_ViewTests_Test {
  private DataTableContext_ViewModel sut;
  private DataTableContext_ViewModelTestEnvironment testEnvironment;
  private String dataTableCustomSetter = "| id | name |\n| 0 | A |";
  private String dataTableToString = "| id | name |\n| 0 | A |";
  private String dataTableToJson = "[ { id:\"0\", name:\"A\" } ]";
  private String dataTableToXml = "<Data>\n  <DataRow>\n    <id>0    </id>\n    <name>A    </name>\n| 0 | A |\n  </DataRow>\n</Data>";
  @Test
  public void test_DataTable_Context_Custom_Setter_given_dataTableCustomSetter_when_then_() throws Exception {
    this.given_dataTableCustomSetter();
    this.BuildSut();
  }
  @Test
  public void test_DataTable_Context_to_String_given_dataTableToString_when_then_() throws Exception {
    this.given_dataTableToString();
    this.BuildSut();
  }
  @Test
  public void test_DataTable_Context_to_JSON_given_dataTableToJson_when_then_() throws Exception {
    this.given_dataTableToJson();
    this.BuildSut();
  }
  @Test
  public void test_DataTable_Context_to_XML_given_dataTableToXml_when_then_() throws Exception {
    this.given_dataTableToXml();
    this.BuildSut();
  }
  @BeforeEach
  public void setUp() {
    this.testEnvironment = new DataTableContext_ViewModelTestEnvironmentImpl();
    this.testEnvironment.Init();
  }



  protected void BuildSut() {
    this.sut = this.testEnvironment.BuildSut();
  }



  public void given_dataTableCustomSetter() {
    this.testEnvironment.SetIdAndName(this.dataTableCustomSetter);
  }
  public void given_dataTableToString() {
    this.testEnvironment.SetDataTableString(this.dataTableToString);
  }
  public void given_dataTableToJson() {
    this.testEnvironment.SetDataTableJson(this.dataTableToJson);
  }
  public void given_dataTableToXml() {
    this.testEnvironment.SetDataTableXml(this.dataTableToXml);
  }




}
