package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.context.DataPathContext_ViewModel;
import de.vimotest.sandbox.context.DataPathContext_ViewModelTestEnvironment;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import de.vimotest.sandbox.context.DataPathContext_ViewModelTestEnvironmentImpl;

public class DataPathContext_ViewTests_Test {
  private DataPathContext_ViewModel sut;
  private DataPathContext_ViewModelTestEnvironment testEnvironment;
  @Test
  public void test_Data_Path_Context_given_my_element_when_then_() throws Exception {
    this.given_my_element();
    this.BuildSut();
  }
  @Test
  public void test_Data_Path_Context_implicit_name_given_path_resource_elements_myelement_when_then_() throws Exception {
    this.given_path_resource_elements_myelement();
    this.BuildSut();
  }
  @BeforeEach
  public void setUp() {
    this.testEnvironment = new DataPathContext_ViewModelTestEnvironmentImpl();
    this.testEnvironment.Init();
  }



  protected void BuildSut() {
    this.sut = this.testEnvironment.BuildSut();
  }


  public void given_my_element() {
    this.testEnvironment.SetDataPathContext("resource:/elements/myelement");
  }
  public void given_path_resource_elements_myelement() {
    this.testEnvironment.SetDataPathContext("resource:/elements/myelement");
  }


}
