package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.datadriven.DataDrivenViewModel;
import de.vimotest.sandbox.datadriven.DataDrivenViewModelTestEnvironment;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import de.vimotest.sandbox.datadriven.DataDrivenViewModelTestEnvironmentImpl;

public class DataDrivenTests_Test {
  private DataDrivenViewModel sut;
  private DataDrivenViewModelTestEnvironment testEnvironment;
  @Test
  public void test_DataDrivenTable_given_when_then_() throws Exception {
    this.BuildSut();
  }
  @BeforeEach
  public void setUp() {
    this.testEnvironment = new DataDrivenViewModelTestEnvironmentImpl();
    this.testEnvironment.Init();
  }



  protected void BuildSut() {
    this.sut = this.testEnvironment.BuildSut();
  }







}
