# de.vimotest.sandbox.cmake

set(GENERATED_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ListViews_ViewModelMyListOfLabelRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ListViews_ViewModelMyListOfImagesRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ListViews_ViewModelMyCheckboxesRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ListViews_ViewModelMyStringRowHandlesRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ListViews_ViewModelMyListWithMultiRowSelectionRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ListViews_ViewModelMyButtonsRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewModelMyListViewElementsRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewModelMyStringRowHandleListViewElementsRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewModelMyIndexBasedMultiSelectRowListViewElementsRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewModelMyStringHandleMultiSelectRowListViewElementsRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/RowBasedCommand_ViewModelMyFlagsRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/LowLevelFields_ViewModelCustomListRowFieldRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TableViews_ViewModelMyElementsRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TableViews_ViewModelMyStringRowHandlesRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewModelMyTableViewElementsRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewModelMyStringRowHandleTableViewElementsRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/RowBasedCommand_ViewModelMyComboBoxesRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/bindings/ViMoTestFileNameBindingMyElementsRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/LowLevelFields_ViewModelCustomTableRowFieldRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TreeViews_ViewModelMyTreeViewElementsRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TreeViews_ViewModelMyStringRowHandlesRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TreeViews_ViewModelMyParentIndexRowHandlesRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TreeViews_ViewModelMyParentStringRowHandlesRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewModelMyTreeViewElementsRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewModelMyStringRowHandleTreeViewElementsRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/RowBasedCommand_ViewModelMyStandardControlsRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/bindings/MyCustomRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/LowLevelFields_ViewModelCustomTreeRowFieldRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/CheckBoxes_ViewModel.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/Labels_ViewModel.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/Images_ViewModel.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ComboBoxes_ViewModel.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ListViews_ViewModel.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TableViews_ViewModel.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TreeViews_ViewModel.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/GenericCommands_ViewModel.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TextBoxes_ViewModel.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/CheckCommand_ViewModel.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/FillTextCommand_ViewModel.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/Buttons_ViewModel.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/ClickCommand_ViewModel.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/LoadCommand_ViewModel.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectEntryCommand_ViewModel.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewModel.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/RowBasedCommand_ViewModel.cpp
  ${CMAKE_CURRENT_LIST_DIR}/bindings/NameBinding_ViewModel.cpp
  ${CMAKE_CURRENT_LIST_DIR}/bindings/CustomFileNameBinding.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/RadioButton_ViewModel.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/LowLevelFields_ViewModel.cpp
  ${CMAKE_CURRENT_LIST_DIR}/dependencies/SimpleDependency_ViewModel.cpp
  ${CMAKE_CURRENT_LIST_DIR}/dependencies/ViewModelDependency_ViewModel.cpp
  ${CMAKE_CURRENT_LIST_DIR}/dependencies/subscope/RepeatUsageDependency_ViewModel.cpp
  ${CMAKE_CURRENT_LIST_DIR}/dependencies/calls/VerifyDependencyCallViewModel.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/CheckBoxes_ViewModelTestEnvironmentImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/Labels_ViewModelTestEnvironmentImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ComboBoxes_ViewModelTestEnvironmentImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/Images_ViewModelTestEnvironmentImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ListViews_ViewModelTestEnvironmentImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TableViews_ViewModelTestEnvironmentImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TreeViews_ViewModelTestEnvironmentImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TextBoxes_ViewModelTestEnvironmentImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/GenericCommands_ViewModelTestEnvironmentImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/CheckCommand_ViewModelTestEnvironmentImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/Buttons_ViewModelTestEnvironmentImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/FillTextCommand_ViewModelTestEnvironmentImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/ClickCommand_ViewModelTestEnvironmentImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/LoadCommand_ViewModelTestEnvironmentImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectEntryCommand_ViewModelTestEnvironmentImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewModelTestEnvironmentImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/RowBasedCommand_ViewModelTestEnvironmentImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/context/StringContext_ViewModelTestEnvironmentImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/context/XmlFileContext_ViewModelTestEnvironmentImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/context/ContextReference_ViewModelTestEnvironmentImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/RadioButton_ViewModelTestEnvironmentImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/context/DataTableContext_ViewModelTestEnvironmentImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/LowLevelFields_ViewModelTestEnvironmentImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/context/DataPathContext_ViewModelTestEnvironmentImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/context/XmlElementContext_ViewModelTestEnvironmentImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/dependencies/ViewModelDependency_ViewModelTestEnvironment.cpp
  ${CMAKE_CURRENT_LIST_DIR}/dependencies/ViewModelDependency_ViewModelTestEnvironmentImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/dependencies/SimpleDependency_ViewModelTestEnvironmentImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/dependencies/subscope/RepeatUsageDependency_ViewModelTestEnvironmentImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/dependencies/calls/VerifyDependencyCallViewModelTestEnvironment.cpp
  ${CMAKE_CURRENT_LIST_DIR}/dependencies/calls/VerifyDependencyCallViewModelTestEnvironmentImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/dependencies/ViewDependencyViewModelTestEnvironmentImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/dependencies/LoggerSpy.cpp
)

set(GENERATED_HEADERS
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ListViews_ViewModelMyListOfLabelRow.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ListViews_ViewModelMyListOfImagesRow.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ListViews_ViewModelMyCheckboxesRow.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ListViews_ViewModelMyStringRowHandlesRow.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ListViews_ViewModelMyListWithMultiRowSelectionRow.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ListViews_ViewModelMyButtonsRow.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewModelMyListViewElementsRow.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewModelMyStringRowHandleListViewElementsRow.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewModelMyIndexBasedMultiSelectRowListViewElementsRow.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewModelMyStringHandleMultiSelectRowListViewElementsRow.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/RowBasedCommand_ViewModelMyFlagsRow.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/LowLevelFields_ViewModelCustomListRowFieldRow.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TableViews_ViewModelMyElementsRow.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TableViews_ViewModelMyStringRowHandlesRow.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewModelMyTableViewElementsRow.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewModelMyStringRowHandleTableViewElementsRow.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/RowBasedCommand_ViewModelMyComboBoxesRow.h
  ${CMAKE_CURRENT_LIST_DIR}/bindings/ViMoTestFileNameBindingMyElementsRow.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/LowLevelFields_ViewModelCustomTableRowFieldRow.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TreeViews_ViewModelMyTreeViewElementsRow.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TreeViews_ViewModelMyStringRowHandlesRow.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TreeViews_ViewModelMyParentIndexRowHandlesRow.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TreeViews_ViewModelMyParentStringRowHandlesRow.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewModelMyTreeViewElementsRow.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewModelMyStringRowHandleTreeViewElementsRow.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/RowBasedCommand_ViewModelMyStandardControlsRow.h
  ${CMAKE_CURRENT_LIST_DIR}/bindings/MyCustomRow.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/LowLevelFields_ViewModelCustomTreeRowFieldRow.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/CheckBoxes_ViewModel.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/Labels_ViewModel.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/Images_ViewModel.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ComboBoxes_ViewModel.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ListViews_ViewModel.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TableViews_ViewModel.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TreeViews_ViewModel.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/GenericCommands_ViewModel.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TextBoxes_ViewModel.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/CheckCommand_ViewModel.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/FillTextCommand_ViewModel.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/Buttons_ViewModel.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/ClickCommand_ViewModel.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/LoadCommand_ViewModel.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectEntryCommand_ViewModel.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewModel.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/RowBasedCommand_ViewModel.h
  ${CMAKE_CURRENT_LIST_DIR}/bindings/NameBinding_ViewModel.h
  ${CMAKE_CURRENT_LIST_DIR}/bindings/CustomFileNameBinding.h
  ${CMAKE_CURRENT_LIST_DIR}/context/StringContext_ViewModel.h
  ${CMAKE_CURRENT_LIST_DIR}/context/XmlFileContext_ViewModel.h
  ${CMAKE_CURRENT_LIST_DIR}/context/ContextReference_ViewModel.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/RadioButton_ViewModel.h
  ${CMAKE_CURRENT_LIST_DIR}/context/DataTableContext_ViewModel.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/LowLevelFields_ViewModel.h
  ${CMAKE_CURRENT_LIST_DIR}/context/DataPathContext_ViewModel.h
  ${CMAKE_CURRENT_LIST_DIR}/context/XmlElementContext_ViewModel.h
  ${CMAKE_CURRENT_LIST_DIR}/dependencies/SimpleDependency_ViewModel.h
  ${CMAKE_CURRENT_LIST_DIR}/dependencies/ViewModelDependency_ViewModel.h
  ${CMAKE_CURRENT_LIST_DIR}/dependencies/subscope/RepeatUsageDependency_ViewModel.h
  ${CMAKE_CURRENT_LIST_DIR}/dependencies/calls/VerifyDependencyCallViewModel.h
  ${CMAKE_CURRENT_LIST_DIR}/dependencies/ViewDependencyViewModel.h
  ${CMAKE_CURRENT_LIST_DIR}/dependencies/MessageBus.h
  ${CMAKE_CURRENT_LIST_DIR}/dependencies/Logger.h
  ${CMAKE_CURRENT_LIST_DIR}/dependencies/subscope/MessageBus.h
  ${CMAKE_CURRENT_LIST_DIR}/dependencies/ViewDependencyView.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/CheckBoxes_ViewModelTestEnvironment.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/CheckBoxes_ViewModelTestEnvironmentImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/Labels_ViewModelTestEnvironment.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/Labels_ViewModelTestEnvironmentImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ComboBoxes_ViewModelTestEnvironment.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ComboBoxes_ViewModelTestEnvironmentImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/Images_ViewModelTestEnvironment.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/Images_ViewModelTestEnvironmentImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ListViews_ViewModelTestEnvironment.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ListViews_ViewModelTestEnvironmentImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TableViews_ViewModelTestEnvironment.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TableViews_ViewModelTestEnvironmentImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TreeViews_ViewModelTestEnvironment.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TreeViews_ViewModelTestEnvironmentImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TextBoxes_ViewModelTestEnvironment.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TextBoxes_ViewModelTestEnvironmentImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/GenericCommands_ViewModelTestEnvironment.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/GenericCommands_ViewModelTestEnvironmentImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/CheckCommand_ViewModelTestEnvironment.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/CheckCommand_ViewModelTestEnvironmentImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/Buttons_ViewModelTestEnvironment.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/Buttons_ViewModelTestEnvironmentImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/FillTextCommand_ViewModelTestEnvironment.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/FillTextCommand_ViewModelTestEnvironmentImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/ClickCommand_ViewModelTestEnvironment.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/ClickCommand_ViewModelTestEnvironmentImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/LoadCommand_ViewModelTestEnvironment.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/LoadCommand_ViewModelTestEnvironmentImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectEntryCommand_ViewModelTestEnvironment.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectEntryCommand_ViewModelTestEnvironmentImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewModelTestEnvironment.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewModelTestEnvironmentImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/RowBasedCommand_ViewModelTestEnvironment.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/RowBasedCommand_ViewModelTestEnvironmentImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/context/StringContext_ViewModelTestEnvironment.h
  ${CMAKE_CURRENT_LIST_DIR}/context/StringContext_ViewModelTestEnvironmentImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/context/XmlFileContext_ViewModelTestEnvironment.h
  ${CMAKE_CURRENT_LIST_DIR}/context/XmlFileContext_ViewModelTestEnvironmentImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/context/ContextReference_ViewModelTestEnvironment.h
  ${CMAKE_CURRENT_LIST_DIR}/context/ContextReference_ViewModelTestEnvironmentImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/RadioButton_ViewModelTestEnvironment.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/RadioButton_ViewModelTestEnvironmentImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/context/DataTableContext_ViewModelTestEnvironment.h
  ${CMAKE_CURRENT_LIST_DIR}/context/DataTableContext_ViewModelTestEnvironmentImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/LowLevelFields_ViewModelTestEnvironment.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/LowLevelFields_ViewModelTestEnvironmentImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/context/DataPathContext_ViewModelTestEnvironment.h
  ${CMAKE_CURRENT_LIST_DIR}/context/DataPathContext_ViewModelTestEnvironmentImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/context/XmlElementContext_ViewModelTestEnvironment.h
  ${CMAKE_CURRENT_LIST_DIR}/context/XmlElementContext_ViewModelTestEnvironmentImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/dependencies/ViewModelDependency_ViewModelTestEnvironment.h
  ${CMAKE_CURRENT_LIST_DIR}/dependencies/ViewModelDependency_ViewModelTestEnvironmentImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/dependencies/SimpleDependency_ViewModelTestEnvironment.h
  ${CMAKE_CURRENT_LIST_DIR}/dependencies/SimpleDependency_ViewModelTestEnvironmentImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/dependencies/subscope/RepeatUsageDependency_ViewModelTestEnvironment.h
  ${CMAKE_CURRENT_LIST_DIR}/dependencies/subscope/RepeatUsageDependency_ViewModelTestEnvironmentImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/dependencies/calls/VerifyDependencyCallViewModelTestEnvironment.h
  ${CMAKE_CURRENT_LIST_DIR}/dependencies/calls/VerifyDependencyCallViewModelTestEnvironmentImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/dependencies/ViewDependencyViewModelTestEnvironment.h
  ${CMAKE_CURRENT_LIST_DIR}/dependencies/ViewDependencyViewModelTestEnvironmentImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/dependencies/LoggerSpy.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectEntryCommand_ViewModelMyOptionsOption.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/RadioButton_ViewModelOptionsOption.h
)

