# de.vimotest.sandbox.cmake

set(GENERATED_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ListViews_ViewMyListOfLabelRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ListViews_ViewMyListOfImagesRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ListViews_ViewMyCheckboxesRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ListViews_ViewMyStringRowHandlesRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ListViews_ViewMyListWithMultiRowSelectionRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewMyListViewElementsRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewMyStringRowHandleListViewElementsRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewMyIndexBasedMultiSelectRowListViewElementsRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewMyStringHandleMultiSelectRowListViewElementsRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/RowBasedCommand_ViewMyFlagsRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/LowLevelFields_ViewCustomListRowFieldRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TableViews_ViewMyElementsRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TableViews_ViewMyStringRowHandlesRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewMyTableViewElementsRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewMyStringRowHandleTableViewElementsRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/RowBasedCommand_ViewMyComboBoxesRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/bindings/ViMoTestFileNameBindingMyElementsRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/LowLevelFields_ViewCustomTableRowFieldRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TreeViews_ViewMyTreeViewElementsRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TreeViews_ViewMyStringRowHandlesRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TreeViews_ViewMyParentIndexRowHandlesRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TreeViews_ViewMyParentStringRowHandlesRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewMyTreeViewElementsRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewMyStringRowHandleTreeViewElementsRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/RowBasedCommand_ViewMyStandardControlsRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/bindings/MyCustomRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/LowLevelFields_ViewCustomTreeRowFieldRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/CheckBoxes_View.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/Labels_View.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/Images_View.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ComboBoxes_View.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ListViews_View.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TableViews_View.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TreeViews_View.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/GenericCommands_View.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TextBoxes_View.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/CheckCommand_View.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/FillTextCommand_View.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/Buttons_View.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/ClickCommand_View.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/LoadCommand_View.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectEntryCommand_View.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_View.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/RowBasedCommand_View.cpp
  ${CMAKE_CURRENT_LIST_DIR}/bindings/NameBinding_View.cpp
  ${CMAKE_CURRENT_LIST_DIR}/bindings/CustomFileNameBinding.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/RadioButton_View.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/LowLevelFields_View.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/CheckBoxes_ViewTestSetupImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/Labels_ViewTestSetupImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ComboBoxes_ViewTestSetupImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/Images_ViewTestSetupImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ListViews_ViewTestSetupImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TableViews_ViewTestSetupImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TreeViews_ViewTestSetupImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TextBoxes_ViewTestSetupImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/GenericCommands_ViewTestSetupImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/CheckCommand_ViewTestSetupImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/Buttons_ViewTestSetupImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/FillTextCommand_ViewTestSetupImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/ClickCommand_ViewTestSetupImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/LoadCommand_ViewTestSetupImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectEntryCommand_ViewTestSetupImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewTestSetupImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/commands/RowBasedCommand_ViewTestSetupImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/context/StringContext_ViewTestSetupImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/context/XmlFileContext_ViewTestSetupImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/context/ContextReference_ViewTestSetupImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/RadioButton_ViewTestSetupImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/context/DataTableContext_ViewTestSetupImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/LowLevelFields_ViewTestSetupImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/context/DataPathContext_ViewTestSetupImpl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/context/XmlElementContext_ViewTestSetupImpl.cpp
)

set(GENERATED_HEADERS
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ListViews_ViewMyListOfLabelRow.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ListViews_ViewMyListOfImagesRow.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ListViews_ViewMyCheckboxesRow.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ListViews_ViewMyStringRowHandlesRow.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ListViews_ViewMyListWithMultiRowSelectionRow.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewMyListViewElementsRow.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewMyStringRowHandleListViewElementsRow.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewMyIndexBasedMultiSelectRowListViewElementsRow.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewMyStringHandleMultiSelectRowListViewElementsRow.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/RowBasedCommand_ViewMyFlagsRow.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/LowLevelFields_ViewCustomListRowFieldRow.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TableViews_ViewMyElementsRow.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TableViews_ViewMyStringRowHandlesRow.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewMyTableViewElementsRow.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewMyStringRowHandleTableViewElementsRow.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/RowBasedCommand_ViewMyComboBoxesRow.h
  ${CMAKE_CURRENT_LIST_DIR}/bindings/ViMoTestFileNameBindingMyElementsRow.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/LowLevelFields_ViewCustomTableRowFieldRow.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TreeViews_ViewMyTreeViewElementsRow.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TreeViews_ViewMyStringRowHandlesRow.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TreeViews_ViewMyParentIndexRowHandlesRow.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TreeViews_ViewMyParentStringRowHandlesRow.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewMyTreeViewElementsRow.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewMyStringRowHandleTreeViewElementsRow.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/RowBasedCommand_ViewMyStandardControlsRow.h
  ${CMAKE_CURRENT_LIST_DIR}/bindings/MyCustomRow.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/LowLevelFields_ViewCustomTreeRowFieldRow.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/CheckBoxes_View.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/Labels_View.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/Images_View.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ComboBoxes_View.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ListViews_View.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TableViews_View.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TreeViews_View.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/GenericCommands_View.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TextBoxes_View.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/CheckCommand_View.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/FillTextCommand_View.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/Buttons_View.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/ClickCommand_View.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/LoadCommand_View.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectEntryCommand_View.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_View.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/RowBasedCommand_View.h
  ${CMAKE_CURRENT_LIST_DIR}/bindings/NameBinding_View.h
  ${CMAKE_CURRENT_LIST_DIR}/bindings/CustomFileNameBinding.h
  ${CMAKE_CURRENT_LIST_DIR}/context/StringContext_View.h
  ${CMAKE_CURRENT_LIST_DIR}/context/XmlFileContext_View.h
  ${CMAKE_CURRENT_LIST_DIR}/context/ContextReference_View.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/RadioButton_View.h
  ${CMAKE_CURRENT_LIST_DIR}/context/DataTableContext_View.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/LowLevelFields_View.h
  ${CMAKE_CURRENT_LIST_DIR}/context/DataPathContext_View.h
  ${CMAKE_CURRENT_LIST_DIR}/context/XmlElementContext_View.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/CheckBoxes_ViewTestSetup.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/CheckBoxes_ViewTestSetupImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/Labels_ViewTestSetup.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/Labels_ViewTestSetupImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ComboBoxes_ViewTestSetup.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ComboBoxes_ViewTestSetupImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/Images_ViewTestSetup.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/Images_ViewTestSetupImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ListViews_ViewTestSetup.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/ListViews_ViewTestSetupImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TableViews_ViewTestSetup.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TableViews_ViewTestSetupImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TreeViews_ViewTestSetup.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TreeViews_ViewTestSetupImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TextBoxes_ViewTestSetup.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/TextBoxes_ViewTestSetupImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/GenericCommands_ViewTestSetup.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/GenericCommands_ViewTestSetupImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/CheckCommand_ViewTestSetup.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/CheckCommand_ViewTestSetupImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/Buttons_ViewTestSetup.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/Buttons_ViewTestSetupImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/FillTextCommand_ViewTestSetup.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/FillTextCommand_ViewTestSetupImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/ClickCommand_ViewTestSetup.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/ClickCommand_ViewTestSetupImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/LoadCommand_ViewTestSetup.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/LoadCommand_ViewTestSetupImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectEntryCommand_ViewTestSetup.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectEntryCommand_ViewTestSetupImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewTestSetup.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/SelectRowCommand_ViewTestSetupImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/RowBasedCommand_ViewTestSetup.h
  ${CMAKE_CURRENT_LIST_DIR}/commands/RowBasedCommand_ViewTestSetupImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/context/StringContext_ViewTestSetup.h
  ${CMAKE_CURRENT_LIST_DIR}/context/StringContext_ViewTestSetupImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/context/XmlFileContext_ViewTestSetup.h
  ${CMAKE_CURRENT_LIST_DIR}/context/XmlFileContext_ViewTestSetupImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/context/ContextReference_ViewTestSetup.h
  ${CMAKE_CURRENT_LIST_DIR}/context/ContextReference_ViewTestSetupImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/RadioButton_ViewTestSetup.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/RadioButton_ViewTestSetupImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/context/DataTableContext_ViewTestSetup.h
  ${CMAKE_CURRENT_LIST_DIR}/context/DataTableContext_ViewTestSetupImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/LowLevelFields_ViewTestSetup.h
  ${CMAKE_CURRENT_LIST_DIR}/widgetassertions/LowLevelFields_ViewTestSetupImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/context/DataPathContext_ViewTestSetup.h
  ${CMAKE_CURRENT_LIST_DIR}/context/DataPathContext_ViewTestSetupImpl.h
  ${CMAKE_CURRENT_LIST_DIR}/context/XmlElementContext_ViewTestSetup.h
  ${CMAKE_CURRENT_LIST_DIR}/context/XmlElementContext_ViewTestSetupImpl.h
)

