package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.commands.GenericCommands_View;
import de.vimotest.sandbox.commands.GenericCommands_ViewContextProvider;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import java.util.Arrays;

public class GenericCommands_ViewTests_Test {
  private GenericCommands_View sut;
  private GenericCommands_ViewContextProvider contextProvider;
  @Test
  public void test_Generic_Commands_Call_given_when_MyCommand_then_() throws Exception {
    this.BuildSut();
    this.when_MyCommand();
  }
  @BeforeEach
  public void setUp() {
    this.contextProvider = new GenericCommands_ViewContextProvider();
    this.contextProvider.Init();
  }



  protected void BuildSut() {
    this.sut = this.contextProvider.BuildSut();
  }





  public void when_MyCommand() {
    this.sut.MyCommand(false, Arrays.asList("A", "B"));
  }


}
