package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.commands.GenericCommands_ViewModel;
import de.vimotest.sandbox.commands.GenericCommands_ViewModelTestSetup;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import de.vimotest.sandbox.commands.GenericCommands_ViewModelTestSetupImpl;
import java.util.Arrays;

public class GenericCommands_ViewTests_Test {
  private GenericCommands_ViewModel sut;
  private GenericCommands_ViewModelTestSetup testSetup;
  @Test
  public void test_Generic_Commands_Call_given_when_MyCommand_then_() throws Exception {
    this.BuildSut();
    this.when_MyCommand();
  }
  @BeforeEach
  public void setUp() {
    this.testSetup = new GenericCommands_ViewModelTestSetupImpl();
    this.testSetup.Init();
  }



  protected void BuildSut() {
    this.sut = this.testSetup.BuildSut();
  }





  public void when_MyCommand() {
    this.sut.myCommand(false, Arrays.asList("A", "B"));
  }


}
