package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.widgetassertions.Images_ViewModel;
import de.vimotest.sandbox.widgetassertions.Images_ViewModelTestEnvironment;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import de.vimotest.sandbox.widgetassertions.Images_ViewModelTestEnvironmentImpl;
import org.junit.Assert;

public class Images_ViewTest_Test {
  private Images_ViewModel sut;
  private Images_ViewModelTestEnvironment testEnvironment;
  @Test
  public void test_My_Scenario_given_empty_context_when_then_Status_shows_image_image_active_and_UpOrDown_shows_image_image_down_() throws Exception {
    this.given_empty_context();
    this.BuildSut();
    this.then_Status_shows_image_image_active_();
    this.then_UpOrDown_shows_image_image_down_();
  }
  @BeforeEach
  public void setUp() {
    this.testEnvironment = new Images_ViewModelTestEnvironmentImpl();
    this.testEnvironment.Init();
  }



  protected void BuildSut() {
    this.sut = this.testEnvironment.BuildSut();
  }


  public void given_empty_context() {
  }


  public void then_Status_shows_image_image_active_() {
    Assert.assertEquals("Expected that image Status has " + "image <image_active>" + ", but was <" + this.sut.getStatusImageName() + ">", "image_active", this.sut.getStatusImageName());
  }
  public void then_UpOrDown_shows_image_image_down_() {
    Assert.assertEquals("Expected that image UpOrDown has " + "image <image_down>" + ", but was <" + this.sut.getUpOrDownImageName() + ">", "image_down", this.sut.getUpOrDownImageName());
  }
}
