package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.commands.LoadCommand_ViewModel;
import de.vimotest.sandbox.commands.LoadCommand_ViewModelTestEnvironment;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import de.vimotest.sandbox.commands.LoadCommand_ViewModelTestEnvironmentImpl;

public class LoadCommand_ViewTests_Test {
  private LoadCommand_ViewModel sut;
  private LoadCommand_ViewModelTestEnvironment testEnvironment;
  @Test
  public void test_Load_Commands_Call_given_when_LoadViewModel_then_() throws Exception {
    this.BuildSut();
    this.when_LoadViewModel();
  }
  @Test
  public void test_Load_with_Parameter_Commands_Call_given_when_LoadViewWithName_then_() throws Exception {
    this.BuildSut();
    this.when_LoadViewWithName();
  }
  @BeforeEach
  public void setUp() {
    this.testEnvironment = new LoadCommand_ViewModelTestEnvironmentImpl();
    this.testEnvironment.Init();
  }



  protected void BuildSut() {
    this.sut = this.testEnvironment.BuildSut();
  }



  public void when_LoadViewModel() {
    this.sut.loadViewModel();
  }
  public void when_LoadViewWithName() {
    this.sut.loadViewWithName("Name");
  }

}
