package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.commands.LoadCommand_ViewModel;
import de.vimotest.sandbox.commands.LoadCommand_ViewModelTestSetup;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import de.vimotest.sandbox.commands.LoadCommand_ViewModelTestSetupImpl;

public class LoadCommand_ViewTests_Test {
  private LoadCommand_ViewModel sut;
  private LoadCommand_ViewModelTestSetup testSetup;
  @Test
  public void test_Load_Commands_Call_given_when_LoadView_then_() throws Exception {
    this.BuildSut();
    this.when_LoadView();
  }
  @Test
  public void test_Load_with_Parameter_Commands_Call_given_when_LoadViewWithName_then_() throws Exception {
    this.BuildSut();
    this.when_LoadViewWithName();
  }
  @BeforeEach
  public void setUp() {
    this.testSetup = new LoadCommand_ViewModelTestSetupImpl();
    this.testSetup.Init();
  }



  protected void BuildSut() {
    this.sut = this.testSetup.BuildSut();
  }





  public void when_LoadView() {
    this.sut.loadView();
  }
  public void when_LoadViewWithName() {
    this.sut.loadViewWithName("Name");
  }


}
