package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.widgetassertions.RadioButton_ViewModel;
import de.vimotest.sandbox.widgetassertions.RadioButton_ViewModelTestEnvironment;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import de.vimotest.sandbox.widgetassertions.RadioButton_ViewModelTestEnvironmentImpl;
import org.junit.Assert;
import de.vimotest.sandbox.widgetassertions.ConvertOptionsToString;
import de.vimotest.sandbox.widgetassertions.RadioButton_ViewModelOptionsOption;

public class RadioButton_ViewTests_Test {
  private RadioButton_ViewModel sut;
  private RadioButton_ViewModelTestEnvironment testEnvironment;
  @Test
  public void test_Select_Option_given_when_then_Options_selected_OptionB_() throws Exception {
    this.BuildSut();
    this.then_Options_selected_OptionB_();
  }
  @Test
  public void test_RadioButton_disabled_given_when_then_Options_selected_OptionA_and_OptionB_is_not_enabled() throws Exception {
    this.BuildSut();
    this.then_Options_selected_OptionA_and_OptionB_is_not_enabled();
  }
  @Test
  public void test_RadioButton_invisible_given_when_then_Options_selected_OptionA_and_OptionB_is_not_visible() throws Exception {
    this.BuildSut();
    this.then_Options_selected_OptionA_and_OptionB_is_not_visible();
  }
  @BeforeEach
  public void setUp() {
    this.testEnvironment = new RadioButton_ViewModelTestEnvironmentImpl();
    this.testEnvironment.Init();
  }



  protected void BuildSut() {
    this.sut = this.testEnvironment.BuildSut();
  }




  public void then_Options_selected_OptionB_() {
    Assert.assertEquals("Expected that radio button group Options has selected <" + "OptionB" + ">, but was <" + ConvertOptionsToString.convertOptionsToString(this.sut.getOptionsRadioButtonGroupSelectedEntry()) + ">", RadioButton_ViewModelOptionsOption.OptionB, this.sut.getOptionsRadioButtonGroupSelectedEntry());
  }
  public void then_Options_selected_OptionA_and_OptionB_is_not_enabled() {
    Assert.assertEquals("Expected that radio button group Options has selected <" + "OptionA" + ">, but was <" + ConvertOptionsToString.convertOptionsToString(this.sut.getOptionsRadioButtonGroupSelectedEntry()) + ">", RadioButton_ViewModelOptionsOption.OptionA, this.sut.getOptionsRadioButtonGroupSelectedEntry());
    Assert.assertFalse("Expected radio button OptionB is disabled, but it was enabled", this.sut.getIsOptionBRadioButtonEnabled());
  }
  public void then_Options_selected_OptionA_and_OptionB_is_not_visible() {
    Assert.assertEquals("Expected that radio button group Options has selected <" + "OptionA" + ">, but was <" + ConvertOptionsToString.convertOptionsToString(this.sut.getOptionsRadioButtonGroupSelectedEntry()) + ">", RadioButton_ViewModelOptionsOption.OptionA, this.sut.getOptionsRadioButtonGroupSelectedEntry());
    Assert.assertFalse("Expected radio button OptionB is hidden, but it was visible", this.sut.getIsOptionBRadioButtonVisible());
  }
}
