package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.widgetassertions.RadioButton_View;
import de.vimotest.sandbox.widgetassertions.RadioButton_ViewTestSetup;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import de.vimotest.sandbox.widgetassertions.RadioButton_ViewTestSetupImpl;
import org.junit.Assert;

public class RadioButton_ViewTests_Test {
  private RadioButton_View sut;
  private RadioButton_ViewTestSetup testSetup;
  @Test
  public void test_Select_Option_given_when_then_Options_selected_OptionB_() throws Exception {
    this.BuildSut();
    this.then_Options_selected_OptionB_();
  }
  @Test
  public void test_RadioButton_disabled_given_when_then_Options_selected_OptionA_() throws Exception {
    this.BuildSut();
    this.then_Options_selected_OptionA_();
  }
  @Test
  public void test_RadioButton_invisible_given_when_then_Options_selected_OptionA_() throws Exception {
    this.BuildSut();
    this.then_Options_selected_OptionA__1();
  }
  @BeforeEach
  public void setUp() {
    this.testSetup = new RadioButton_ViewTestSetupImpl();
    this.testSetup.Init();
  }



  protected void BuildSut() {
    this.sut = this.testSetup.BuildSut();
  }







  public void then_Options_selected_OptionB_() {
    Assert.assertEquals("OptionB", this.sut.getOptionsRadioButtonGroupSelectedEntry());
  }
  public void then_Options_selected_OptionA_() {
    Assert.assertEquals("OptionA", this.sut.getOptionsRadioButtonGroupSelectedEntry());
  }
  public void then_Options_selected_OptionA__1() {
    Assert.assertEquals("OptionA", this.sut.getOptionsRadioButtonGroupSelectedEntry());
  }
}
