package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.dependencies.subscope.RepeatUsageDependency_ViewModel;
import de.vimotest.sandbox.dependencies.subscope.RepeatUsageDependency_ViewModelTestSetup;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import de.vimotest.sandbox.dependencies.subscope.RepeatUsageDependency_ViewModelTestSetupImpl;

public class RepeatUsageDependency_ViewModelTests_Test {
  private RepeatUsageDependency_ViewModel sut;
  private RepeatUsageDependency_ViewModelTestSetup testSetup;
  @Test
  public void test_Invoke_Direct_Dependency_given_when_OnMessage_then_() throws Exception {
    this.BuildSut();
    this.when_OnMessage();
  }
  @Test
  public void test_Invoke_Registry_Dependency_given_when_Log_then_() throws Exception {
    this.BuildSut();
    this.when_Log();
  }
  @BeforeEach
  public void setUp() {
    this.testSetup = new RepeatUsageDependency_ViewModelTestSetupImpl();
    this.testSetup.Init();
  }



  protected void BuildSut() {
    this.sut = this.testSetup.BuildSut();
  }





  public void when_OnMessage() {
    this.testSetup.getMessageBus().OnMessage(0, null);
  }
  public void when_Log() {
    this.testSetup.getLogger().Log("my message");
  }


}
