package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.commands.SelectEntryCommand_ViewModel;
import de.vimotest.sandbox.commands.SelectEntryCommand_ViewModelTestEnvironment;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import de.vimotest.sandbox.commands.SelectEntryCommand_ViewModelTestEnvironmentImpl;
import de.vimotest.sandbox.commands.SelectEntryCommand_ViewModelMyOptionsOption;
import java.util.List;
import org.junit.Assert;

public class SelectEntryCommand_ViewTests_Test {
  private SelectEntryCommand_ViewModel sut;
  private SelectEntryCommand_ViewModelTestEnvironment testEnvironment;
  @Test
  public void test_Select_Entry_Combobox_Call_given_when_select_entry_C_in_MyElements_then_MyElements_has_3_entries_and() throws Exception {
    this.BuildSut();
    this.when_select_entry_C_in_MyElements();
    this.then_MyElements_has_3_entries_and();
  }
  @Test
  public void test_Select_Entry_RadioButton_Call_given_when_select_entry_B_in_MyOptions_then_() throws Exception {
    this.BuildSut();
    this.when_select_entry_B_in_MyOptions();
  }
  @BeforeEach
  public void setUp() {
    this.testEnvironment = new SelectEntryCommand_ViewModelTestEnvironmentImpl();
    this.testEnvironment.Init();
  }



  protected void BuildSut() {
    this.sut = this.testEnvironment.BuildSut();
  }





  public void when_select_entry_C_in_MyElements() {
    this.sut.myElementsEntrySelected("C");
  }
  public void when_select_entry_B_in_MyOptions() {
    this.sut.myOptionsEntrySelected(SelectEntryCommand_ViewModelMyOptionsOption.B);
  }


  public void then_MyElements_has_3_entries_and() {
    List<String> actualMyElementsEntries = this.sut.getMyElementsComboBoxEntries();
    Assert.assertEquals(Integer.valueOf(3), Integer.valueOf(actualMyElementsEntries.size()));
    Assert.assertEquals("A", actualMyElementsEntries.get(1 - 1));
    Assert.assertEquals("B", actualMyElementsEntries.get(2 - 1));
    Assert.assertEquals("C", actualMyElementsEntries.get(3 - 1));
    Assert.assertEquals(null, this.sut.getMyElementsComboBoxSelectedEntry());
  }
}
