package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.commands.SelectRowCommand_ViewModel;
import de.vimotest.sandbox.commands.SelectRowCommand_ViewModelTestEnvironment;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import de.vimotest.sandbox.commands.SelectRowCommand_ViewModelTestEnvironmentImpl;
import java.util.Arrays;
import java.util.List;
import de.vimotest.sandbox.commands.SelectRowCommand_ViewModelMyListViewElementsRow;
import org.junit.Assert;
import wrappers.javaWrappers.IntegerFunctions;
import de.vimotest.sandbox.commands.SelectRowCommand_ViewModelMyStringRowHandleListViewElementsRow;
import de.vimotest.sandbox.commands.SelectRowCommand_ViewModelMyTableViewElementsRow;
import de.vimotest.sandbox.commands.SelectRowCommand_ViewModelMyStringRowHandleTableViewElementsRow;
import de.vimotest.sandbox.commands.SelectRowCommand_ViewModelMyTreeViewElementsRow;
import de.vimotest.sandbox.commands.SelectRowCommand_ViewModelMyStringRowHandleTreeViewElementsRow;
import de.vimotest.sandbox.commands.SelectRowCommand_ViewModelMyStringHandleMultiSelectRowListViewElementsRow;

public class SelectRowCommand_ViewTests_Test {
  private SelectRowCommand_ViewModel sut;
  private SelectRowCommand_ViewModelTestEnvironment testEnvironment;
  @Test
  public void test_Select_Row_ListView_Call_given_when_select_row_1_in_MyListViewElements_then_MyListViewElements_has_2_rows() throws Exception {
    this.BuildSut();
    this.when_select_row_1_in_MyListViewElements();
    this.then_MyListViewElements_has_2_rows();
  }
  @Test
  public void test_Select_Row_ListView_Call_string_row_handle_given_when_select_row_ROW_B_in_MyStringRowHandleListViewElements_then_MyStringRowHandleListViewElements_has_2_rows() throws Exception {
    this.BuildSut();
    this.when_select_row_ROW_B_in_MyStringRowHandleListViewElements();
    this.then_MyStringRowHandleListViewElements_has_2_rows();
  }
  @Test
  public void test_Select_Row_TableView_Call_given_when_select_row_1_in_MyTableViewElements_then_MyTableViewElements_has_2_rows() throws Exception {
    this.BuildSut();
    this.when_select_row_1_in_MyTableViewElements();
    this.then_MyTableViewElements_has_2_rows();
  }
  @Test
  public void test_Select_Row_TableView_Call_string_row_handle_given_when_select_row_ROW_B_in_MyStringRowHandleTableViewElements_then_MyStringRowHandleTableViewElements_has_2_rows() throws Exception {
    this.BuildSut();
    this.when_select_row_ROW_B_in_MyStringRowHandleTableViewElements();
    this.then_MyStringRowHandleTableViewElements_has_2_rows();
  }
  @Test
  public void test_Select_Row_TreeView_Call_given_when_select_row_1_in_MyTreeViewElements_then_MyTreeViewElements_has_2_rows() throws Exception {
    this.BuildSut();
    this.when_select_row_1_in_MyTreeViewElements();
    this.then_MyTreeViewElements_has_2_rows();
  }
  @Test
  public void test_Select_Row_TreeView_Call_string_row_handle_given_when_select_row_ROW_B_in_MyStringRowHandleTreeViewElements_then_MyStringRowHandleTreeViewElements_has_2_rows() throws Exception {
    this.BuildSut();
    this.when_select_row_ROW_B_in_MyStringRowHandleTreeViewElements();
    this.then_MyStringRowHandleTreeViewElements_has_2_rows();
  }
  @Test
  public void test_Select_Multiple_Rows_given_when_select_rows_ROW_A_ROW_C_in_MyStringHandleMultiSelectRowListViewElements_then_MyStringHandleMultiSelectRowListViewElements_has_3_rows() throws Exception {
    this.BuildSut();
    this.when_select_rows_ROW_A_ROW_C_in_MyStringHandleMultiSelectRowListViewElements();
    this.then_MyStringHandleMultiSelectRowListViewElements_has_3_rows();
  }
  @BeforeEach
  public void setUp() {
    this.testEnvironment = new SelectRowCommand_ViewModelTestEnvironmentImpl();
    this.testEnvironment.Init();
  }



  protected void BuildSut() {
    this.sut = this.testEnvironment.BuildSut();
  }





  public void when_select_row_1_in_MyListViewElements() {
    this.sut.myListViewElementsListRowSelected(1);
  }
  public void when_select_row_ROW_B_in_MyStringRowHandleListViewElements() {
    this.sut.myStringRowHandleListViewElementsListRowSelected("ROW_B");
  }
  public void when_select_row_1_in_MyTableViewElements() {
    this.sut.myTableViewElementsTableRowSelected(1);
  }
  public void when_select_row_ROW_B_in_MyStringRowHandleTableViewElements() {
    this.sut.myStringRowHandleTableViewElementsTableRowSelected("ROW_B");
  }
  public void when_select_row_1_in_MyTreeViewElements() {
    this.sut.myTreeViewElementsTreeRowSelected(1);
  }
  public void when_select_row_ROW_B_in_MyStringRowHandleTreeViewElements() {
    this.sut.myStringRowHandleTreeViewElementsTreeRowSelected("ROW_B");
  }
  public void when_select_rows_ROW_A_ROW_C_in_MyStringHandleMultiSelectRowListViewElements() {
    this.sut.myStringHandleMultiSelectRowListViewElementsListRowSelected(Arrays.asList("ROW_A", "ROW_C"));
  }


  public void then_MyListViewElements_has_2_rows() {
    List<SelectRowCommand_ViewModelMyListViewElementsRow> actualRows = this.sut.getMyListViewElementsListRows();
    Assert.assertEquals("Expected that list view MyListViewElements has 2 rows, but has " + IntegerFunctions.ToString(actualRows.size()), Integer.valueOf(2), Integer.valueOf(actualRows.size()));
    // {
    SelectRowCommand_ViewModelMyListViewElementsRow row0 = actualRows.get(1 - 1);
    Assert.assertEquals("Expected that list view MyListViewElements row at index 0 has rowhandle <0>, but was <" + row0.getRowIndex() + ">", Integer.valueOf(row0.getRowIndex()), row0.getRowIndex());
    Assert.assertEquals("Expected that label Header has text <" + "A" + ">, but was <" + row0.getHeaderLabelText() + ">", "A", row0.getHeaderLabelText());
    // }
    // {
    SelectRowCommand_ViewModelMyListViewElementsRow row1 = actualRows.get(2 - 1);
    Assert.assertEquals("Expected that list view MyListViewElements row at index 1 has rowhandle <1>, but was <" + row1.getRowIndex() + ">", Integer.valueOf(row1.getRowIndex()), row1.getRowIndex());
    Assert.assertEquals("Expected that label Header has text <" + "B" + ">, but was <" + row1.getHeaderLabelText() + ">", "B", row1.getHeaderLabelText());
    // }
  }
  public void then_MyStringRowHandleListViewElements_has_2_rows() {
    List<SelectRowCommand_ViewModelMyStringRowHandleListViewElementsRow> actualRows = this.sut.getMyStringRowHandleListViewElementsListRows();
    Assert.assertEquals("Expected that list view MyStringRowHandleListViewElements has 2 rows, but has " + IntegerFunctions.ToString(actualRows.size()), Integer.valueOf(2), Integer.valueOf(actualRows.size()));
    // {
    SelectRowCommand_ViewModelMyStringRowHandleListViewElementsRow row0 = actualRows.get(1 - 1);
    Assert.assertEquals("Expected that list view MyStringRowHandleListViewElements row at index 0 has rowhandle <ROW_A>, but was <" + row0.getRowHandle() + ">", "ROW_A", row0.getRowHandle());
    Assert.assertEquals("Expected that label Header has text <" + "A" + ">, but was <" + row0.getHeaderLabelText() + ">", "A", row0.getHeaderLabelText());
    // }
    // {
    SelectRowCommand_ViewModelMyStringRowHandleListViewElementsRow row1 = actualRows.get(2 - 1);
    Assert.assertEquals("Expected that list view MyStringRowHandleListViewElements row at index 1 has rowhandle <ROW_B>, but was <" + row1.getRowHandle() + ">", "ROW_B", row1.getRowHandle());
    Assert.assertEquals("Expected that label Header has text <" + "B" + ">, but was <" + row1.getHeaderLabelText() + ">", "B", row1.getHeaderLabelText());
    // }
  }
  public void then_MyTableViewElements_has_2_rows() {
    List<SelectRowCommand_ViewModelMyTableViewElementsRow> actualRows = this.sut.getMyTableViewElementsTableRows();
    Assert.assertEquals("Expected that table view MyTableViewElements has 2 rows, but has " + IntegerFunctions.ToString(actualRows.size()), Integer.valueOf(2), Integer.valueOf(actualRows.size()));
    // {
    SelectRowCommand_ViewModelMyTableViewElementsRow row0 = actualRows.get(1 - 1);
    Assert.assertEquals("Expected that table view MyTableViewElements row at index 0 has rowhandle <0>, but was <" + row0.getRowIndex() + ">", Integer.valueOf(row0.getRowIndex()), row0.getRowIndex());
    Assert.assertEquals("Expected that label columnCell has text <" + "A" + ">, but was <" + row0.getColumnCellLabelText() + ">", "A", row0.getColumnCellLabelText());
    // }
    // {
    SelectRowCommand_ViewModelMyTableViewElementsRow row1 = actualRows.get(2 - 1);
    Assert.assertEquals("Expected that table view MyTableViewElements row at index 1 has rowhandle <1>, but was <" + row1.getRowIndex() + ">", Integer.valueOf(row1.getRowIndex()), row1.getRowIndex());
    Assert.assertEquals("Expected that label columnCell has text <" + "B" + ">, but was <" + row1.getColumnCellLabelText() + ">", "B", row1.getColumnCellLabelText());
    // }
  }
  public void then_MyStringRowHandleTableViewElements_has_2_rows() {
    List<SelectRowCommand_ViewModelMyStringRowHandleTableViewElementsRow> actualRows = this.sut.getMyStringRowHandleTableViewElementsTableRows();
    Assert.assertEquals("Expected that table view MyStringRowHandleTableViewElements has 2 rows, but has " + IntegerFunctions.ToString(actualRows.size()), Integer.valueOf(2), Integer.valueOf(actualRows.size()));
    // {
    SelectRowCommand_ViewModelMyStringRowHandleTableViewElementsRow row0 = actualRows.get(1 - 1);
    Assert.assertEquals("Expected that table view MyStringRowHandleTableViewElements row at index 0 has rowhandle <ROW_A>, but was <" + row0.getRowHandle() + ">", "ROW_A", row0.getRowHandle());
    Assert.assertEquals("Expected that label columnCell has text <" + "A" + ">, but was <" + row0.getColumnCellLabelText() + ">", "A", row0.getColumnCellLabelText());
    // }
    // {
    SelectRowCommand_ViewModelMyStringRowHandleTableViewElementsRow row1 = actualRows.get(2 - 1);
    Assert.assertEquals("Expected that table view MyStringRowHandleTableViewElements row at index 1 has rowhandle <ROW_B>, but was <" + row1.getRowHandle() + ">", "ROW_B", row1.getRowHandle());
    Assert.assertEquals("Expected that label columnCell has text <" + "B" + ">, but was <" + row1.getColumnCellLabelText() + ">", "B", row1.getColumnCellLabelText());
    // }
  }
  public void then_MyTreeViewElements_has_2_rows() {
    List<SelectRowCommand_ViewModelMyTreeViewElementsRow> actualRows = this.sut.getMyTreeViewElementsTreeRows();
    Assert.assertEquals("Expected that tree view MyTreeViewElements has 2 rows, but has " + IntegerFunctions.ToString(actualRows.size()), Integer.valueOf(2), Integer.valueOf(actualRows.size()));
    // {
    SelectRowCommand_ViewModelMyTreeViewElementsRow row0 = actualRows.get(1 - 1);
    Assert.assertEquals("Expected that tree view MyTreeViewElements row at index 0 has rowhandle <0>, but was <" + row0.getRowIndex() + ">", Integer.valueOf(row0.getRowIndex()), row0.getRowIndex());
    Assert.assertEquals("Expected that tree view MyTreeViewElements row at index 0 has parent rowhandle <" + 0 + ">, but was <" + row0.getRowDepth() + ">", Integer.valueOf(row0.getRowDepth()), row0.getRowDepth());
    Assert.assertEquals("Expected that label columnCell has text <" + "A" + ">, but was <" + row0.getColumnCellLabelText() + ">", "A", row0.getColumnCellLabelText());
    // }
    // {
    SelectRowCommand_ViewModelMyTreeViewElementsRow row1 = actualRows.get(2 - 1);
    Assert.assertEquals("Expected that tree view MyTreeViewElements row at index 1 has rowhandle <1>, but was <" + row1.getRowIndex() + ">", Integer.valueOf(row1.getRowIndex()), row1.getRowIndex());
    Assert.assertEquals("Expected that tree view MyTreeViewElements row at index 1 has parent rowhandle <" + 0 + ">, but was <" + row1.getRowDepth() + ">", Integer.valueOf(row1.getRowDepth()), row1.getRowDepth());
    Assert.assertEquals("Expected that label columnCell has text <" + "B" + ">, but was <" + row1.getColumnCellLabelText() + ">", "B", row1.getColumnCellLabelText());
    // }
  }
  public void then_MyStringRowHandleTreeViewElements_has_2_rows() {
    List<SelectRowCommand_ViewModelMyStringRowHandleTreeViewElementsRow> actualRows = this.sut.getMyStringRowHandleTreeViewElementsTreeRows();
    Assert.assertEquals("Expected that tree view MyStringRowHandleTreeViewElements has 2 rows, but has " + IntegerFunctions.ToString(actualRows.size()), Integer.valueOf(2), Integer.valueOf(actualRows.size()));
    // {
    SelectRowCommand_ViewModelMyStringRowHandleTreeViewElementsRow row0 = actualRows.get(1 - 1);
    Assert.assertEquals("Expected that tree view MyStringRowHandleTreeViewElements row at index 0 has rowhandle <ROW_A>, but was <" + row0.getRowHandle() + ">", "ROW_A", row0.getRowHandle());
    Assert.assertEquals("Expected that tree view MyStringRowHandleTreeViewElements row at index 0 has parent rowhandle <" + 0 + ">, but was <" + row0.getRowDepth() + ">", Integer.valueOf(row0.getRowDepth()), row0.getRowDepth());
    Assert.assertEquals("Expected that label columnCell has text <" + "A" + ">, but was <" + row0.getColumnCellLabelText() + ">", "A", row0.getColumnCellLabelText());
    // }
    // {
    SelectRowCommand_ViewModelMyStringRowHandleTreeViewElementsRow row1 = actualRows.get(2 - 1);
    Assert.assertEquals("Expected that tree view MyStringRowHandleTreeViewElements row at index 1 has rowhandle <ROW_B>, but was <" + row1.getRowHandle() + ">", "ROW_B", row1.getRowHandle());
    Assert.assertEquals("Expected that tree view MyStringRowHandleTreeViewElements row at index 1 has parent rowhandle <" + 0 + ">, but was <" + row1.getRowDepth() + ">", Integer.valueOf(row1.getRowDepth()), row1.getRowDepth());
    Assert.assertEquals("Expected that label columnCell has text <" + "B" + ">, but was <" + row1.getColumnCellLabelText() + ">", "B", row1.getColumnCellLabelText());
    // }
  }
  public void then_MyStringHandleMultiSelectRowListViewElements_has_3_rows() {
    List<SelectRowCommand_ViewModelMyStringHandleMultiSelectRowListViewElementsRow> actualRows = this.sut.getMyStringHandleMultiSelectRowListViewElementsListRows();
    Assert.assertEquals("Expected that list view MyStringHandleMultiSelectRowListViewElements has 3 rows, but has " + IntegerFunctions.ToString(actualRows.size()), Integer.valueOf(3), Integer.valueOf(actualRows.size()));
    // {
    SelectRowCommand_ViewModelMyStringHandleMultiSelectRowListViewElementsRow row0 = actualRows.get(1 - 1);
    Assert.assertEquals("Expected that list view MyStringHandleMultiSelectRowListViewElements row at index 0 has rowhandle <ROW_A>, but was <" + row0.getRowHandle() + ">", "ROW_A", row0.getRowHandle());
    Assert.assertEquals("Expected that label Header has text <" + "A" + ">, but was <" + row0.getHeaderLabelText() + ">", "A", row0.getHeaderLabelText());
    // }
    // {
    SelectRowCommand_ViewModelMyStringHandleMultiSelectRowListViewElementsRow row1 = actualRows.get(2 - 1);
    Assert.assertEquals("Expected that list view MyStringHandleMultiSelectRowListViewElements row at index 1 has rowhandle <ROW_B>, but was <" + row1.getRowHandle() + ">", "ROW_B", row1.getRowHandle());
    Assert.assertEquals("Expected that label Header has text <" + "B" + ">, but was <" + row1.getHeaderLabelText() + ">", "B", row1.getHeaderLabelText());
    // }
    // {
    SelectRowCommand_ViewModelMyStringHandleMultiSelectRowListViewElementsRow row2 = actualRows.get(3 - 1);
    Assert.assertEquals("Expected that list view MyStringHandleMultiSelectRowListViewElements row at index 2 has rowhandle <ROW_C>, but was <" + row2.getRowHandle() + ">", "ROW_C", row2.getRowHandle());
    Assert.assertEquals("Expected that label Header has text <" + "C" + ">, but was <" + row2.getHeaderLabelText() + ">", "C", row2.getHeaderLabelText());
    // }
  }
}
