package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.dependencies.SimpleDependency_ViewModel;
import de.vimotest.sandbox.dependencies.SimpleDependency_ViewModelTestEnvironment;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import de.vimotest.sandbox.dependencies.SimpleDependency_ViewModelTestEnvironmentImpl;
import java.util.Arrays;

public class SimpleDependency_ViewModelTests_Test {
  private SimpleDependency_ViewModel sut;
  private SimpleDependency_ViewModelTestEnvironment testEnvironment;
  @Test
  public void test_Invoke_Direct_Dependency_given_when_OnMessage_then_() throws Exception {
    this.BuildSut();
    this.when_OnMessage();
  }
  @Test
  public void test_Invoke_Registry_Dependency_given_when_Log_then_() throws Exception {
    this.BuildSut();
    this.when_Log();
  }
  @BeforeEach
  public void setUp() {
    this.testEnvironment = new SimpleDependency_ViewModelTestEnvironmentImpl();
    this.testEnvironment.Init();
  }



  protected void BuildSut() {
    this.sut = this.testEnvironment.BuildSut();
  }





  public void when_OnMessage() {
    this.testEnvironment.getMessageBus().OnMessage(0, Arrays.asList("A", "B"));
  }
  public void when_Log() {
    this.testEnvironment.getLogger().Log("my message");
  }


}
