package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.dependencies.SimpleDependency_ViewModel;
import de.vimotest.sandbox.dependencies.SimpleDependency_ViewModelTestSetup;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import de.vimotest.sandbox.dependencies.SimpleDependency_ViewModelTestSetupImpl;

public class SimpleDependency_ViewModelTests_Test {
  private SimpleDependency_ViewModel sut;
  private SimpleDependency_ViewModelTestSetup testSetup;
  @Test
  public void test_Invoke_Direct_Dependency_given_when_OnMessage_then_() throws Exception {
    this.BuildSut();
    this.when_OnMessage();
  }
  @Test
  public void test_Invoke_Registry_Dependency_given_when_Log_then_() throws Exception {
    this.BuildSut();
    this.when_Log();
  }
  @BeforeEach
  public void setUp() {
    this.testSetup = new SimpleDependency_ViewModelTestSetupImpl();
    this.testSetup.Init();
  }



  protected void BuildSut() {
    this.sut = this.testSetup.BuildSut();
  }





  public void when_OnMessage() {

  }
  public void when_Log() {

  }


}
