package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.context.StringContext_View;
import de.vimotest.sandbox.context.StringContext_ViewTestSetup;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import de.vimotest.sandbox.context.StringContext_ViewTestSetupImpl;

public class StringContext2_ViewTests_Test {
  private StringContext_View sut;
  private StringContext_ViewTestSetup testSetup;
  private String alice_bob_charlie = "Alice, Bob, Charlie";
  @Test
  public void test_SimpleStringContext2_given_alice_bob_charlie_when_then_() throws Exception {
    this.given_alice_bob_charlie();
    this.BuildSut();
  }
  @BeforeEach
  public void setUp() {
    this.testSetup = new StringContext_ViewTestSetupImpl();
    this.testSetup.Init();
  }



  protected void BuildSut() {
    this.sut = this.testSetup.BuildSut();
  }



  public void given_alice_bob_charlie() {
    this.testSetup.SetSimpleStringContext(this.alice_bob_charlie);
  }




}
