package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.widgetassertions.TableViews_ViewModel;
import de.vimotest.sandbox.widgetassertions.TableViews_ViewModelTestEnvironment;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import de.vimotest.sandbox.widgetassertions.TableViews_ViewModelTestEnvironmentImpl;
import java.util.List;
import de.vimotest.sandbox.widgetassertions.TableViews_ViewModelMyElementsRow;
import org.junit.Assert;
import de.vimotest.sandbox.widgetassertions.TableViews_ViewModelMyStringRowHandleRow;
import de.vimotest.sandbox.widgetassertions.TableViews_ViewModelMyStringMultiRowHandlesRow;
import de.vimotest.sandbox.widgetassertions.TableViews_ViewModelFirstColumnRowHandleRow;
import de.vimotest.sandbox.widgetassertions.TableViews_ViewModelFirstColumnMultiRowHandleRow;

public class TableViews_ViewTest_Test {
  private TableViews_ViewModel sut;
  private TableViews_ViewModelTestEnvironment testEnvironment;
  @Test
  public void test_My_Scenario_given_empty_context_when_then_MyElements_has_2_rows_and_selected_row_index_1_and_is_visible_and_is_enabled_and_Description_is_not_visible_and_MyStringRowHandle_has_2_rows_and_selected_row_handle_ROW1_and_MyStringMultiRowHandles_has_2_rows_and_selected_row_handles_A_() throws Exception {
    this.given_empty_context();
    this.BuildSut();
    this.then_MyElements_has_2_rows_and_selected_row_index_1_and_is_visible_and_is_enabled_and_Description_is_not_visible();
    this.then_MyStringRowHandle_has_2_rows_and_selected_row_handle_ROW1();
    this.then_MyStringMultiRowHandles_has_2_rows_and_selected_row_handles_A_();
  }
  @Test
  public void test_Table_Ignore_Columns_given_empty_context_when_then_MyElements_has_2_rows() throws Exception {
    this.given_empty_context();
    this.BuildSut();
    this.then_MyElements_has_2_rows();
  }
  @Test
  public void test_FirstLabelColumn_row_handle_given_when_then_FirstColumnRowHandle_has_2_rows_and_selected_row_handle_MyRow1_and_FirstColumnMultiRowHandle_has_2_rows_and_selected_row_handles_Row0_Row1_() throws Exception {
    this.BuildSut();
    this.then_FirstColumnRowHandle_has_2_rows_and_selected_row_handle_MyRow1();
    this.then_FirstColumnMultiRowHandle_has_2_rows_and_selected_row_handles_Row0_Row1_();
  }
  @BeforeEach
  public void setUp() {
    this.testEnvironment = new TableViews_ViewModelTestEnvironmentImpl();
    this.testEnvironment.Init();
  }



  protected void BuildSut() {
    this.sut = this.testEnvironment.BuildSut();
  }


  public void given_empty_context() {
  }


  public void then_MyElements_has_2_rows_and_selected_row_index_1_and_is_visible_and_is_enabled_and_Description_is_not_visible() {
    List<TableViews_ViewModelMyElementsRow> actualRows = this.sut.getMyElementsTableRows();
    Assert.assertEquals("Expected that table view MyElements has 2 rows, but has " + Integer.toString(actualRows.size()), Integer.valueOf(2), Integer.valueOf(actualRows.size()));
    // {
    TableViews_ViewModelMyElementsRow row0 = actualRows.get(1 - 1);
    Assert.assertEquals("Expected that table view MyElements row at index 0 has rowhandle <0>, but was <" + Integer.toString(row0.getRowIndex()) + ">", Integer.valueOf(row0.getRowIndex()), row0.getRowIndex());
    Assert.assertTrue("Expected that checkbox Include is checked, but was <" + ((row0.getIsIncludeCheckBoxChecked() ? "checked" : "unchecked")) + ">", row0.getIsIncludeCheckBoxChecked());
    Assert.assertEquals("Expected that label Name has text <" + "A" + ">, but was <" + row0.getNameLabelText() + ">", "A", row0.getNameLabelText());
    Assert.assertEquals("Expected that label Description has text <" + "B" + ">, but was <" + row0.getDescriptionLabelText() + ">", "B", row0.getDescriptionLabelText());
    Assert.assertEquals("Expected that image InfoIcon has " + "image <image_info>" + ", but was <" + row0.getInfoIconImageName() + ">", "image_info", row0.getInfoIconImageName());
    // }
    // {
    TableViews_ViewModelMyElementsRow row1 = actualRows.get(2 - 1);
    Assert.assertEquals("Expected that table view MyElements row at index 1 has rowhandle <1>, but was <" + Integer.toString(row1.getRowIndex()) + ">", Integer.valueOf(row1.getRowIndex()), row1.getRowIndex());
    Assert.assertFalse("Expected that checkbox Include is unchecked, but was <" + ((row1.getIsIncludeCheckBoxChecked() ? "checked" : "unchecked")) + ">", row1.getIsIncludeCheckBoxChecked());
    Assert.assertEquals("Expected that label Name has text <" + "C" + ">, but was <" + row1.getNameLabelText() + ">", "C", row1.getNameLabelText());
    Assert.assertEquals("Expected that label Description has text <" + "D" + ">, but was <" + row1.getDescriptionLabelText() + ">", "D", row1.getDescriptionLabelText());
    Assert.assertEquals("Expected that image InfoIcon has " + "image <image_star>" + ", but was <" + row1.getInfoIconImageName() + ">", "image_star", row1.getInfoIconImageName());
    // }
    Assert.assertEquals("Expected that table view MyElements has selected row with row handle <" + Integer.toString(1) + ">, but was <" + Integer.toString(this.sut.getMyElementsTableSelectedRow()) + ">", Integer.valueOf(this.sut.getMyElementsTableSelectedRow()), this.sut.getMyElementsTableSelectedRow());
    Assert.assertTrue("Expected table view MyElements is visible, but it was hidden", this.sut.getIsMyElementsTableVisible());
    Assert.assertTrue("Expected table view MyElements is enabled, but it was disabled", this.sut.getIsMyElementsTableEnabled());
    Assert.assertFalse("Expected table column Description is hidden, but it was visible", this.sut.getIsMyElementsTableDescriptionColumnVisible());
  }
  public void then_MyStringRowHandle_has_2_rows_and_selected_row_handle_ROW1() {
    List<TableViews_ViewModelMyStringRowHandleRow> actualRows = this.sut.getMyStringRowHandleTableRows();
    Assert.assertEquals("Expected that table view MyStringRowHandle has 2 rows, but has " + Integer.toString(actualRows.size()), Integer.valueOf(2), Integer.valueOf(actualRows.size()));
    // {
    TableViews_ViewModelMyStringRowHandleRow row0 = actualRows.get(1 - 1);
    Assert.assertEquals("Expected that table view MyStringRowHandle row at index 0 has rowhandle <ROW0>, but was <" + row0.getRowHandle() + ">", "ROW0", row0.getRowHandle());
    Assert.assertEquals("Expected that label Values has text <" + "A" + ">, but was <" + row0.getValuesLabelText() + ">", "A", row0.getValuesLabelText());
    // }
    // {
    TableViews_ViewModelMyStringRowHandleRow row1 = actualRows.get(2 - 1);
    Assert.assertEquals("Expected that table view MyStringRowHandle row at index 1 has rowhandle <ROW1>, but was <" + row1.getRowHandle() + ">", "ROW1", row1.getRowHandle());
    Assert.assertEquals("Expected that label Values has text <" + "B" + ">, but was <" + row1.getValuesLabelText() + ">", "B", row1.getValuesLabelText());
    // }
    Assert.assertEquals("Expected that table view MyStringRowHandle has selected row with row handle <" + "ROW1" + ">, but was <" + this.sut.getMyStringRowHandleTableSelectedRow() + ">", "ROW1", this.sut.getMyStringRowHandleTableSelectedRow());
  }
  public void then_MyStringMultiRowHandles_has_2_rows_and_selected_row_handles_A_() {
    List<TableViews_ViewModelMyStringMultiRowHandlesRow> actualRows = this.sut.getMyStringMultiRowHandlesTableRows();
    Assert.assertEquals("Expected that table view MyStringMultiRowHandles has 2 rows, but has " + Integer.toString(actualRows.size()), Integer.valueOf(2), Integer.valueOf(actualRows.size()));
    // {
    TableViews_ViewModelMyStringMultiRowHandlesRow row0 = actualRows.get(1 - 1);
    Assert.assertEquals("Expected that table view MyStringMultiRowHandles row at index 0 has rowhandle <A>, but was <" + row0.getRowHandle() + ">", "A", row0.getRowHandle());
    Assert.assertEquals("Expected that label Values has text <" + "" + ">, but was <" + row0.getValuesLabelText() + ">", "", row0.getValuesLabelText());
    // }
    // {
    TableViews_ViewModelMyStringMultiRowHandlesRow row1 = actualRows.get(2 - 1);
    Assert.assertEquals("Expected that table view MyStringMultiRowHandles row at index 1 has rowhandle <B>, but was <" + row1.getRowHandle() + ">", "B", row1.getRowHandle());
    Assert.assertEquals("Expected that label Values has text <" + "" + ">, but was <" + row1.getValuesLabelText() + ">", "", row1.getValuesLabelText());
    // }
    List<String> actualMyStringMultiRowHandlesSelectedRowHandles = this.sut.getMyStringMultiRowHandlesTableSelectedRows();
    Assert.assertEquals("Expected that table view MyStringMultiRowHandles has selected 1 rows, but has " + Integer.toString(actualMyStringMultiRowHandlesSelectedRowHandles.size()), Integer.valueOf(1), Integer.valueOf(actualMyStringMultiRowHandlesSelectedRowHandles.size()));
    Assert.assertEquals("Expected that table view MyStringMultiRowHandles has selected row at index 0 with row handle <" + "A" + ">, but was <" + actualMyStringMultiRowHandlesSelectedRowHandles.get(1 - 1) + ">", "A", actualMyStringMultiRowHandlesSelectedRowHandles.get(1 - 1));
  }
  public void then_MyElements_has_2_rows() {
    List<TableViews_ViewModelMyElementsRow> actualRows = this.sut.getMyElementsTableRows();
    Assert.assertEquals("Expected that table view MyElements has 2 rows, but has " + Integer.toString(actualRows.size()), Integer.valueOf(2), Integer.valueOf(actualRows.size()));
    // {
    TableViews_ViewModelMyElementsRow row0 = actualRows.get(1 - 1);
    Assert.assertEquals("Expected that table view MyElements row at index 0 has rowhandle <0>, but was <" + Integer.toString(row0.getRowIndex()) + ">", Integer.valueOf(row0.getRowIndex()), row0.getRowIndex());
    Assert.assertEquals("Expected that label Name has text <" + "A" + ">, but was <" + row0.getNameLabelText() + ">", "A", row0.getNameLabelText());
    // }
    // {
    TableViews_ViewModelMyElementsRow row1 = actualRows.get(2 - 1);
    Assert.assertEquals("Expected that table view MyElements row at index 1 has rowhandle <1>, but was <" + Integer.toString(row1.getRowIndex()) + ">", Integer.valueOf(row1.getRowIndex()), row1.getRowIndex());
    Assert.assertEquals("Expected that image InfoIcon has " + "image <image_star>" + ", but was <" + row1.getInfoIconImageName() + ">", "image_star", row1.getInfoIconImageName());
    // }
  }
  public void then_FirstColumnRowHandle_has_2_rows_and_selected_row_handle_MyRow1() {
    List<TableViews_ViewModelFirstColumnRowHandleRow> actualRows = this.sut.getFirstColumnRowHandleTableRows();
    Assert.assertEquals("Expected that table view FirstColumnRowHandle has 2 rows, but has " + Integer.toString(actualRows.size()), Integer.valueOf(2), Integer.valueOf(actualRows.size()));
    // {
    TableViews_ViewModelFirstColumnRowHandleRow row0 = actualRows.get(1 - 1);
    Assert.assertEquals("Expected that label Name has text <" + "MyRow0" + ">, but was <" + row0.getNameLabelText() + ">", "MyRow0", row0.getNameLabelText());
    // }
    // {
    TableViews_ViewModelFirstColumnRowHandleRow row1 = actualRows.get(2 - 1);
    Assert.assertEquals("Expected that label Name has text <" + "MyRow1" + ">, but was <" + row1.getNameLabelText() + ">", "MyRow1", row1.getNameLabelText());
    // }
    Assert.assertEquals("Expected that table view FirstColumnRowHandle has selected row with row handle <" + "MyRow1" + ">, but was <" + this.sut.getFirstColumnRowHandleTableSelectedRow() + ">", "MyRow1", this.sut.getFirstColumnRowHandleTableSelectedRow());
  }
  public void then_FirstColumnMultiRowHandle_has_2_rows_and_selected_row_handles_Row0_Row1_() {
    List<TableViews_ViewModelFirstColumnMultiRowHandleRow> actualRows = this.sut.getFirstColumnMultiRowHandleTableRows();
    Assert.assertEquals("Expected that table view FirstColumnMultiRowHandle has 2 rows, but has " + Integer.toString(actualRows.size()), Integer.valueOf(2), Integer.valueOf(actualRows.size()));
    // {
    TableViews_ViewModelFirstColumnMultiRowHandleRow row0 = actualRows.get(1 - 1);
    Assert.assertEquals("Expected that label Name has text <" + "Row0" + ">, but was <" + row0.getNameLabelText() + ">", "Row0", row0.getNameLabelText());
    // }
    // {
    TableViews_ViewModelFirstColumnMultiRowHandleRow row1 = actualRows.get(2 - 1);
    Assert.assertEquals("Expected that label Name has text <" + "Row1" + ">, but was <" + row1.getNameLabelText() + ">", "Row1", row1.getNameLabelText());
    // }
    List<String> actualFirstColumnMultiRowHandleSelectedRowHandles = this.sut.getFirstColumnMultiRowHandleTableSelectedRows();
    Assert.assertEquals("Expected that table view FirstColumnMultiRowHandle has selected 2 rows, but has " + Integer.toString(actualFirstColumnMultiRowHandleSelectedRowHandles.size()), Integer.valueOf(2), Integer.valueOf(actualFirstColumnMultiRowHandleSelectedRowHandles.size()));
    Assert.assertEquals("Expected that table view FirstColumnMultiRowHandle has selected row at index 0 with row handle <" + "Row0" + ">, but was <" + actualFirstColumnMultiRowHandleSelectedRowHandles.get(1 - 1) + ">", "Row0", actualFirstColumnMultiRowHandleSelectedRowHandles.get(1 - 1));
    Assert.assertEquals("Expected that table view FirstColumnMultiRowHandle has selected row at index 1 with row handle <" + "Row1" + ">, but was <" + actualFirstColumnMultiRowHandleSelectedRowHandles.get(2 - 1) + ">", "Row1", actualFirstColumnMultiRowHandleSelectedRowHandles.get(2 - 1));
  }
}
