package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.dependencies.calls.VerifyDependencyCallViewModel;
import de.vimotest.sandbox.dependencies.calls.VerifyDependencyCallViewModelTestEnvironment;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import de.vimotest.sandbox.dependencies.calls.VerifyDependencyCallViewModelTestEnvironmentImpl;
import de.vimotest.sandbox.dependencies.LoggerSpy;
import org.junit.Assert;

public class VerifyDependencyCallViewModelTests_Test {
  private VerifyDependencyCallViewModel sut;
  private VerifyDependencyCallViewModelTestEnvironment testEnvironment;
  @Test
  public void test_Verify_dependency_call_given_when_then_call_Logger_Log_any_() throws Exception {
    this.BuildSut();
    this.then_call_Logger_Log_any_();
  }
  @BeforeEach
  public void setUp() {
    this.testEnvironment = new VerifyDependencyCallViewModelTestEnvironmentImpl();
    this.testEnvironment.Init();
  }



  protected void BuildSut() {
    this.sut = this.testEnvironment.BuildSut();
  }







  public void then_call_Logger_Log_any_() {
    LoggerSpy spy = this.testEnvironment.getLogger();
    Assert.assertEquals(Integer.valueOf(1), Integer.valueOf(spy.LogCallInfos.size()));
  }
}
