package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.dependencies.calls.VerifyDependencyCallViewModel;
import de.vimotest.sandbox.dependencies.calls.VerifyDependencyCallViewModelTestSetup;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import de.vimotest.sandbox.dependencies.calls.VerifyDependencyCallViewModelTestSetupImpl;

public class VerifyDependencyCallViewModelTests_Test {
  private VerifyDependencyCallViewModel sut;
  private VerifyDependencyCallViewModelTestSetup testSetup;
  @Test
  public void test_Verify_dependency_call_given_when_then_call_Logger_Log_any_() throws Exception {
    this.BuildSut();
    this.then_call_Logger_Log_any_();
  }
  @BeforeEach
  public void setUp() {
    this.testSetup = new VerifyDependencyCallViewModelTestSetupImpl();
    this.testSetup.Init();
  }



  protected void BuildSut() {
    this.sut = this.testSetup.BuildSut();
  }







  public void then_call_Logger_Log_any_() {
    // ;
  }
}
