package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.dependencies.ViewDependencyViewModel;
import de.vimotest.sandbox.dependencies.ViewDependencyViewModelTestEnvironment;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import de.vimotest.sandbox.dependencies.ViewDependencyViewModelTestEnvironmentImpl;

public class ViewDependencyViewModelTests_Test {
  private ViewDependencyViewModel sut;
  private ViewDependencyViewModelTestEnvironment testEnvironment;
  @Test
  public void test_View_Dependency_given_when_Foo_then_() throws Exception {
    this.BuildSut();
    this.when_Foo();
  }
  @BeforeEach
  public void setUp() {
    this.testEnvironment = new ViewDependencyViewModelTestEnvironmentImpl();
    this.testEnvironment.Init();
  }



  protected void BuildSut() {
    this.sut = this.testEnvironment.BuildSut();
  }





  public void when_Foo() {
    this.testEnvironment.getViewDependencyView().Foo();
  }


}
