package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.dependencies.ViewModelDependency_ViewModel;
import de.vimotest.sandbox.dependencies.ViewModelDependency_ViewModelTestEnvironment;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import de.vimotest.sandbox.dependencies.ViewModelDependency_ViewModelTestEnvironmentImpl;
import de.vimotest.sandbox.dependencies.SimpleDependency_ViewModelSpy;
import org.junit.Assert;

public class ViewModelDependency_ViewModelTests_Test {
  private ViewModelDependency_ViewModel sut;
  private ViewModelDependency_ViewModelTestEnvironment testEnvironment;
  @Test
  public void test_ViewModel_Dependency_Call_given_when_LoadViewModel_then_() throws Exception {
    this.BuildSut();
    this.when_LoadViewModel();
  }
  @Test
  public void test_ViewModel_Dependency_Verify_given_when_then_call_SimpleDependency_ViewModel_LoadViewModel___() throws Exception {
    this.BuildSut();
    this.then_call_SimpleDependency_ViewModel_LoadViewModel___();
  }
  @BeforeEach
  public void setUp() {
    this.testEnvironment = new ViewModelDependency_ViewModelTestEnvironmentImpl();
    this.testEnvironment.Init();
  }



  protected void BuildSut() {
    this.sut = this.testEnvironment.BuildSut();
  }



  public void when_LoadViewModel() {
    this.testEnvironment.getSimpleDependency_ViewModel().loadViewModel("MyPath");
  }

  public void then_call_SimpleDependency_ViewModel_LoadViewModel___() {
    SimpleDependency_ViewModelSpy spy = this.testEnvironment.getSimpleDependency_ViewModel();
    for (int callInfoIndex = 0; callInfoIndex <= spy.LoadViewModelCallInfos.size(); callInfoIndex++) {
      SimpleDependency_ViewModelSpy.LoadViewModelCallInfo callInfo = spy.LoadViewModelCallInfos.get(callInfoIndex - 1);
      Assert.assertEquals("SimpleDependency_ViewModel.LoadViewModel Call[" + Integer.toString(callInfoIndex) + "]: Expected argument value 'Path' is <" + "MyPath" + "> but was <" + callInfo.PathValue + ">", "MyPath", callInfo.PathValue);
    }
    Assert.assertEquals("Expected that SimpleDependency_ViewModel.LoadViewModel was called exactly 1 times, but was " + Integer.toString(spy.LoadViewModelCallInfos.size()), Integer.valueOf(1), Integer.valueOf(spy.LoadViewModelCallInfos.size()));
  }
}
