package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.dependencies.ViewModelDependency_ViewModel;
import de.vimotest.sandbox.dependencies.ViewModelDependency_ViewModelTestSetup;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import de.vimotest.sandbox.dependencies.ViewModelDependency_ViewModelTestSetupImpl;

public class ViewModelDependency_ViewModelTests_Test {
  private ViewModelDependency_ViewModel sut;
  private ViewModelDependency_ViewModelTestSetup testSetup;
  @Test
  public void test_ViewModel_Dependency_Invocation_given_when_LoadView_then_() throws Exception {
    this.BuildSut();
    this.when_LoadView();
  }
  @BeforeEach
  public void setUp() {
    this.testSetup = new ViewModelDependency_ViewModelTestSetupImpl();
    this.testSetup.Init();
  }



  protected void BuildSut() {
    this.sut = this.testSetup.BuildSut();
  }





  public void when_LoadView() {
    this.testSetup.getSimpleDependency_ViewModel().loadView();
  }


}
