package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.context.XmlElementContext_ViewModel;
import de.vimotest.sandbox.context.XmlElementContext_ViewModelTestEnvironment;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import de.vimotest.sandbox.context.XmlElementContext_ViewModelTestEnvironmentImpl;

public class XmlElementContext_ViewTests_Test {
  private XmlElementContext_ViewModel sut;
  private XmlElementContext_ViewModelTestEnvironment testEnvironment;
  private String myxml = "<MyXML>  \n  <Inner></Inner>\n</MyXML>";
  private String MyXML_Inner = "<MyXML>  \n  <Inner></Inner>\n</MyXML>";
  @Test
  public void test_Xml_Context_given_myxml_when_then_() throws Exception {
    this.given_myxml();
    this.BuildSut();
  }
  @Test
  public void test_Xml_Context_explicit_name_given_MyXML_Inner_when_then_() throws Exception {
    this.given_MyXML_Inner();
    this.BuildSut();
  }
  @BeforeEach
  public void setUp() {
    this.testEnvironment = new XmlElementContext_ViewModelTestEnvironmentImpl();
    this.testEnvironment.Init();
  }



  protected void BuildSut() {
    this.sut = this.testEnvironment.BuildSut();
  }


  public void given_myxml() {
    this.testEnvironment.SetXmlElementContext(this.myxml);
  }
  public void given_MyXML_Inner() {
    this.testEnvironment.SetXmlElementContext(this.MyXML_Inner);
  }


}
