package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.context.XmlFileContext_View;
import de.vimotest.sandbox.context.XmlFileContext_ViewContextProvider;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;

public class XmlFileContext_ViewTests_Test {
  private XmlFileContext_View sut;
  private XmlFileContext_ViewContextProvider contextProvider;
  private String XmlFile_NoExternalFile = "<MyXML>  \"\n\"  <Inner></Inner>\"\n\"</MyXML>";
  @Test
  public void test_XmlFile_NoExternalFile_given_XmlFile_NoExternalFile_when_then_() throws Exception {
    this.given_XmlFile_NoExternalFile();
    this.BuildSut();
  }
  @Test
  public void test_XmlFile_ExternalFile_given_XmlFile_ExternalFile_when_then_() throws Exception {
    this.given_XmlFile_ExternalFile();
    this.BuildSut();
  }
  @BeforeEach
  public void setUp() {
    this.contextProvider = new XmlFileContext_ViewContextProvider();
    this.contextProvider.Init();
  }



  protected void BuildSut() {
    this.sut = this.contextProvider.BuildSut();
  }



  public void given_XmlFile_NoExternalFile() {
    this.contextProvider.SetXmlFileContext(this.XmlFile_NoExternalFile);
  }
  public void given_XmlFile_ExternalFile() {
    this.contextProvider.SetXmlExternalFileContext("XmlFile_ExternalFile.xml");
  }




}
