package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.context.XmlFileContext_View;
import de.vimotest.sandbox.context.XmlFileContext_ViewTestSetup;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import de.vimotest.sandbox.context.XmlFileContext_ViewTestSetupImpl;

public class XmlFileContext_ViewTests_Test {
  private XmlFileContext_View sut;
  private XmlFileContext_ViewTestSetup testSetup;
  private String XmlFile_NoExternalFile = "<MyXML>  \n  <Inner></Inner>\n</MyXML>";
  @Test
  public void test_XmlFile_NoExternalFile_given_XmlFile_NoExternalFile_when_then_() throws Exception {
    this.given_XmlFile_NoExternalFile();
    this.BuildSut();
  }
  @Test
  public void test_XmlFile_ExternalFile_given_XmlFile_ExternalFile_when_then_() throws Exception {
    this.given_XmlFile_ExternalFile();
    this.BuildSut();
  }
  @BeforeEach
  public void setUp() {
    this.testSetup = new XmlFileContext_ViewTestSetupImpl();
    this.testSetup.Init();
  }



  protected void BuildSut() {
    this.sut = this.testSetup.BuildSut();
  }



  public void given_XmlFile_NoExternalFile() {
    this.testSetup.SetXmlFileContext(this.XmlFile_NoExternalFile);
  }
  public void given_XmlFile_ExternalFile() {
    this.testSetup.SetXmlExternalFileContext("XmlFile_ExternalFile.xml");
  }




}
