package de.vimotest.sandbox;

/*Generated by MPS */

import de.vimotest.sandbox.context.XmlFileContext_ViewModel;
import de.vimotest.sandbox.context.XmlFileContext_ViewModelTestEnvironment;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import de.vimotest.sandbox.context.XmlFileContext_ViewModelTestEnvironmentImpl;

public class XmlFileContext_ViewTests_Test {
  private XmlFileContext_ViewModel sut;
  private XmlFileContext_ViewModelTestEnvironment testEnvironment;
  private String XmlFile_NoExternalFile = "<MyXML>  \n  <Inner></Inner>\n</MyXML>";
  @Test
  public void test_XmlFile_NoExternalFile_given_XmlFile_NoExternalFile_when_then_() throws Exception {
    this.given_XmlFile_NoExternalFile();
    this.BuildSut();
  }
  @Test
  public void test_XmlFile_ExternalFile_given_XmlFile_ExternalFile_when_then_() throws Exception {
    this.given_XmlFile_ExternalFile();
    this.BuildSut();
  }
  @BeforeEach
  public void setUp() {
    this.testEnvironment = new XmlFileContext_ViewModelTestEnvironmentImpl();
    this.testEnvironment.Init();
  }



  protected void BuildSut() {
    this.sut = this.testEnvironment.BuildSut();
  }


  public void given_XmlFile_NoExternalFile() {
    this.testEnvironment.SetXmlFileContext(this.XmlFile_NoExternalFile);
  }
  public void given_XmlFile_ExternalFile() {
    this.testEnvironment.SetXmlExternalFileContext("XmlFile_ExternalFile.xml");
  }


}
