package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */

import java.util.Objects;

/**
 * foo
 */
public class ActivityconvertOptionsToString {
  public static String convertOptionsToString(RadioButton_ViewModelOptionsOption symbol) {
    if (Objects.equals(symbol, RadioButton_ViewModelOptionsOption.OptionA)) {
      return "OptionA";
    }
    if (Objects.equals(symbol, RadioButton_ViewModelOptionsOption.OptionB)) {
      return "OptionB";
    }
    if (Objects.equals(symbol, RadioButton_ViewModelOptionsOption.OptionC)) {
      return "OptionC";
    }
    return "?";
  }
}
