package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class Buttons_View {
  private String OkButtonText;
  public String getOkButtonText() {
    return this.OkButtonText;
  }
  private Boolean isOkButtonEnabled;
  public Boolean getIsOkButtonEnabled() {
    return this.isOkButtonEnabled;
  }
  private Boolean isOkButtonVisibility;
  public Boolean getIsOkButtonVisibility() {
    return this.isOkButtonVisibility;
  }
}
