package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class Buttons_ViewModelTestSetupImpl extends Buttons_ViewModelTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public void SetEmptyContext() {
  }
  @Override
  public Buttons_ViewModel BuildSut() {
    return null;
  }

}
