package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class Buttons_ViewModelTestEnvironmentImpl extends Buttons_ViewModelTestEnvironment {
  @Override
  public void Init() {
  }
  @Override
  public void SetEmptyContext() {
  }
  @Override
  public Buttons_ViewModel BuildSut() {
    return null;
  }
}
