package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public abstract class Buttons_ViewModelTestEnvironment {
  public abstract void Init();
  public abstract void SetEmptyContext();
  public abstract Buttons_ViewModel BuildSut();
}
