package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class Buttons_ViewContextProvider {
  public void Init() {
  }
  public void SetEmptyContext() {
  }
  public Buttons_View BuildSut() {
    return null;
  }
}
