package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class Buttons_ViewModel {
  private String OkButtonText;
  public String getOkButtonText() {
    return this.OkButtonText;
  }
  private Boolean isOkButtonEnabled;
  public Boolean getIsOkButtonEnabled() {
    return this.isOkButtonEnabled;
  }
  private Boolean isOkButtonVisible;
  public Boolean getIsOkButtonVisible() {
    return this.isOkButtonVisible;
  }
}
