package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class CheckBoxes_ViewModelTestEnvironmentImpl extends CheckBoxes_ViewModelTestEnvironment {
  @Override
  public void Init() {
  }
  @Override
  public void SetEmptyContext() {
  }
  @Override
  public CheckBoxes_ViewModel BuildSut() {
    return null;
  }
}
