package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public abstract class CheckBoxes_ViewContextProvider {
  public abstract void Init();
  public abstract void SetEmptyContext();
  public abstract CheckBoxes_View BuildSut();
}
