package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */

import java.util.Objects;

public class CheckBoxes_View {
  private Boolean isMyFlagWithLabelCheckBoxChecked;
  public Boolean getIsMyFlagWithLabelCheckBoxChecked() {
    return this.isMyFlagWithLabelCheckBoxChecked;
  }
  private Boolean isMyFlagWithLabelCheckBoxVisibility;
  public Boolean getIsMyFlagWithLabelCheckBoxVisibility() {
    return this.isMyFlagWithLabelCheckBoxVisibility;
  }
  private Boolean isMyFlagWithLabelCheckBoxEnabled;
  public Boolean getIsMyFlagWithLabelCheckBoxEnabled() {
    return this.isMyFlagWithLabelCheckBoxEnabled;
  }
  private String MyFlagWithLabelCheckBoxText;
  public String getMyFlagWithLabelCheckBoxText() {
    return this.MyFlagWithLabelCheckBoxText;
  }
  private Boolean isMyFlagNoLabelCheckBoxChecked;
  public Boolean getIsMyFlagNoLabelCheckBoxChecked() {
    return this.isMyFlagNoLabelCheckBoxChecked;
  }
  private Boolean isMyFlagTriStateCheckBoxChecked;
  public Boolean getIsMyFlagTriStateCheckBoxChecked() {
    return Objects.equals(this.isMyFlagTriStateCheckBoxChecked, true);
  }
}
