package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class ComboBoxes_ViewModelTestSetupImpl extends ComboBoxes_ViewModelTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public void SetEmptyContext() {
  }
  @Override
  public ComboBoxes_ViewModel BuildSut() {
    return null;
  }
}
