package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class ComboBoxes_ViewModelMyOptionsWithFixedChoicesAndDisplayValueEntry {
  public ComboBoxes_ViewModelMyOptionsWithFixedChoicesAndDisplayValueOption EnumValue;
  public String VisibleValue;
  public ComboBoxes_ViewModelMyOptionsWithFixedChoicesAndDisplayValueEntry() {
  }
  public ComboBoxes_ViewModelMyOptionsWithFixedChoicesAndDisplayValueEntry(ComboBoxes_ViewModelMyOptionsWithFixedChoicesAndDisplayValueOption EnumValue, String VisibleValue) {
    this.EnumValue = EnumValue;
    this.VisibleValue = VisibleValue;
  }
}
