package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class ComboBoxes_ViewContextProviderImpl extends ComboBoxes_ViewContextProvider {
  @Override
  public void Init() {
  }
  @Override
  public void SetEmptyContext() {
  }
  @Override
  public ComboBoxes_View BuildSut() {
    return null;
  }
}
