package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


/**
 * foo
 */
public enum ComboBoxes_ViewModelMyOptionsWithFixedChoicesAndDisplayValueOption {
  Green(),
  Yellow(),
  Red()
}
