package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class ComboBoxes_ViewContextProvider {
  public void Init() {
  }
  public void SetEmptyContext() {
  }
  public ComboBoxes_View BuildSut() {
    return null;
  }
}
