package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */

import java.util.Objects;

/**
 * foo
 */
public class ConvertMyOptionsWithFixedChoicesAndDisplayValueToString {
  public static String convertMyOptionsWithFixedChoicesAndDisplayValueToString(ComboBoxes_ViewModelMyOptionsWithFixedChoicesAndDisplayValueOption symbol) {
    if (Objects.equals(symbol, ComboBoxes_ViewModelMyOptionsWithFixedChoicesAndDisplayValueOption.Green)) {
      return "(green)";
    }
    if (Objects.equals(symbol, ComboBoxes_ViewModelMyOptionsWithFixedChoicesAndDisplayValueOption.Yellow)) {
      return "(yellow)";
    }
    if (Objects.equals(symbol, ComboBoxes_ViewModelMyOptionsWithFixedChoicesAndDisplayValueOption.Red)) {
      return "(red)";
    }
    return "?";
  }
}
