package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */

import java.util.Objects;

/**
 * foo
 */
public class ConvertMyOptionsWithFixedChoicesToString {
  public static String convertMyOptionsWithFixedChoicesToString(ComboBoxes_ViewModelMyOptionsWithFixedChoicesOption symbol) {
    if (Objects.equals(symbol, ComboBoxes_ViewModelMyOptionsWithFixedChoicesOption.Green)) {
      return "Green";
    }
    if (Objects.equals(symbol, ComboBoxes_ViewModelMyOptionsWithFixedChoicesOption.Yellow)) {
      return "Yellow";
    }
    if (Objects.equals(symbol, ComboBoxes_ViewModelMyOptionsWithFixedChoicesOption.Red)) {
      return "Red";
    }
    return "?";
  }
}
