package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class Images_View {
  private String MyImageImageSource;
  public String getMyImageImageSource() {
    return this.MyImageImageSource;
  }
  private Boolean isMyImageEnabled;
  public Boolean getIsMyImageEnabled() {
    return this.isMyImageEnabled;
  }
  private Boolean isMyImageVisibility;
  public Boolean getIsMyImageVisibility() {
    return this.isMyImageVisibility;
  }
  private String MyUpDownImageImageSource;
  public String getMyUpDownImageImageSource() {
    return this.MyUpDownImageImageSource;
  }
}
