package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class Images_ViewTestSetupImpl extends Images_ViewTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public void SetEmptyContext() {
  }
  @Override
  public Images_View BuildSut() {
    return null;
  }
}
