package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class Images_ViewModelTestSetupImpl extends Images_ViewModelTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public void SetEmptyContext() {
  }
  @Override
  public Images_ViewModel BuildSut() {
    return null;
  }

}
