package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public abstract class Images_ViewContextProvider {
  public abstract void Init();
  public abstract void SetEmptyContext();
  public abstract Images_View BuildSut();
}
