package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class Images_ViewContextProviderImpl extends Images_ViewContextProvider {
  public void Init() {
  }
  public void SetEmptyContext() {
  }
  public Images_View BuildSut() {
    return null;
  }
}
