package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public abstract class Images_ViewModelTestSetup {
  public abstract void Init();
  public abstract void SetEmptyContext();
  public abstract Images_ViewModel BuildSut();
}
