package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public class Labels_View {
  private String TestLabelText;
  public String getTestLabelText() {
    return this.TestLabelText;
  }
  private Boolean isTestLabelEnabled;
  public Boolean getIsTestLabelEnabled() {
    return this.isTestLabelEnabled;
  }
  private Boolean isTestLabelVisible;
  public Boolean getIsTestLabelVisible() {
    return this.isTestLabelVisible;
  }
  private List<String> MultiLineLabelText = new LinkedList<>();
  public List<String> getMultiLineLabelText() {
    return this.MultiLineLabelText;
  }
  private String WithToolTipLabelText;
  public String getWithToolTipLabelText() {
    return this.WithToolTipLabelText;
  }
  private String WithToolTipLabelToolTip;
  public String getWithToolTipLabelToolTip() {
    return this.WithToolTipLabelToolTip;
  }
  private String WithMultiLineToolTipLabelText;
  public String getWithMultiLineToolTipLabelText() {
    return this.WithMultiLineToolTipLabelText;
  }
  private List<String> WithMultiLineToolTipLabelToolTip = new LinkedList<>();
  public List<String> getWithMultiLineToolTipLabelToolTip() {
    return this.WithMultiLineToolTipLabelToolTip;
  }
  private String WithTextColorLabelText;
  public String getWithTextColorLabelText() {
    return this.WithTextColorLabelText;
  }
  private String WithTextColorLabelTextColor;
  public String getWithTextColorLabelTextColor() {
    return this.WithTextColorLabelTextColor;
  }
  private Boolean isOnlyVisibilityLabelVisible;
  public Boolean getIsOnlyVisibilityLabelVisible() {
    return this.isOnlyVisibilityLabelVisible;
  }
}
