package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class Labels_ViewTestSetupImpl extends Labels_ViewTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public void SetEmptyContext() {
  }
  @Override
  public Labels_View BuildSut() {
    return null;
  }
}
