package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class Labels_ViewModelTestEnvironmentImpl extends Labels_ViewModelTestEnvironment {
  @Override
  public void Init() {
  }
  @Override
  public void SetEmptyContext() {
  }
  @Override
  public Labels_ViewModel BuildSut() {
    return null;
  }
}
