package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public abstract class Labels_ViewModelTestSetup {
  public abstract void Init();
  public abstract void SetEmptyContext();
  public abstract Labels_ViewModel BuildSut();
}
