package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class ListViews_ViewModelMyListOfLabelRow {
  private String MyValueLabelText;
  public String getMyValueLabelText() {
    return this.MyValueLabelText;
  }
  private Boolean isMyValueLabelEnabled;
  public Boolean getIsMyValueLabelEnabled() {
    return this.isMyValueLabelEnabled;
  }
  private Boolean isMyValueLabelVisible;
  public Boolean getIsMyValueLabelVisible() {
    return this.isMyValueLabelVisible;
  }
  private Integer RowIndex;
  public Integer getRowIndex() {
    return this.RowIndex;
  }
}
