package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public class ListViews_View {
  private Boolean isMyListOfLabelVisibility;
  public Boolean getIsMyListOfLabelVisibility() {
    return this.isMyListOfLabelVisibility;
  }
  private Boolean isMyListOfLabelEnabled;
  public Boolean getIsMyListOfLabelEnabled() {
    return this.isMyListOfLabelEnabled;
  }
  private List<ListViews_ViewMyListOfLabelRow> MyListOfLabelWidgetListRows = new LinkedList<>();
  public List<ListViews_ViewMyListOfLabelRow> getMyListOfLabelWidgetListRows() {
    return this.MyListOfLabelWidgetListRows;
  }
  private Integer MyListOfLabelSelectedRow;
  public Integer getMyListOfLabelSelectedRow() {
    return this.MyListOfLabelSelectedRow;
  }
  private Boolean isMyListOfImagesVisibility;
  public Boolean getIsMyListOfImagesVisibility() {
    return this.isMyListOfImagesVisibility;
  }
  private Boolean isMyListOfImagesEnabled;
  public Boolean getIsMyListOfImagesEnabled() {
    return this.isMyListOfImagesEnabled;
  }
  private List<ListViews_ViewMyListOfImagesRow> MyListOfImagesWidgetListRows = new LinkedList<>();
  public List<ListViews_ViewMyListOfImagesRow> getMyListOfImagesWidgetListRows() {
    return this.MyListOfImagesWidgetListRows;
  }
  private Integer MyListOfImagesSelectedRow;
  public Integer getMyListOfImagesSelectedRow() {
    return this.MyListOfImagesSelectedRow;
  }
  private List<ListViews_ViewMyCheckboxesRow> MyCheckboxesWidgetListRows = new LinkedList<>();
  public List<ListViews_ViewMyCheckboxesRow> getMyCheckboxesWidgetListRows() {
    return this.MyCheckboxesWidgetListRows;
  }
  private Integer MyCheckboxesSelectedRow;
  public Integer getMyCheckboxesSelectedRow() {
    return this.MyCheckboxesSelectedRow;
  }
  private Boolean isMyCheckboxesVisibility;
  public Boolean getIsMyCheckboxesVisibility() {
    return this.isMyCheckboxesVisibility;
  }
  private Boolean isMyCheckboxesEnabled;
  public Boolean getIsMyCheckboxesEnabled() {
    return this.isMyCheckboxesEnabled;
  }
  private List<ListViews_ViewMyStringRowHandlesRow> MyStringRowHandlesWidgetListRows = new LinkedList<>();
  public List<ListViews_ViewMyStringRowHandlesRow> getMyStringRowHandlesWidgetListRows() {
    return this.MyStringRowHandlesWidgetListRows;
  }
  private String MyStringRowHandlesSelectedRow;
  public String getMyStringRowHandlesSelectedRow() {
    return this.MyStringRowHandlesSelectedRow;
  }
  private List<ListViews_ViewMyMultiRowSelectionListRow> MyMultiRowSelectionListWidgetListRows = new LinkedList<>();
  public List<ListViews_ViewMyMultiRowSelectionListRow> getMyMultiRowSelectionListWidgetListRows() {
    return this.MyMultiRowSelectionListWidgetListRows;
  }
  private List<Integer> MyMultiRowSelectionListSelectedRows = new LinkedList<>();
  public List<Integer> getMyMultiRowSelectionListSelectedRows() {
    return this.MyMultiRowSelectionListSelectedRows;
  }
}
