package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class ListViews_ViewMyMultiRowSelectionListRow {
  private String HeaderText;
  public String getHeaderText() {
    return this.HeaderText;
  }
  private Integer RowIndex;
  public Integer getRowIndex() {
    return this.RowIndex;
  }
}
