package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public abstract class ListViews_ViewTestSetup {
  public abstract void Init();
  public abstract void SetEmptyContext();
  public abstract ListViews_View BuildSut();
}
