package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class ListViews_ViewMyStringRowHandlesRow {
  private String ValuesText;
  public String getValuesText() {
    return this.ValuesText;
  }
  private String RowHandle;
  public String getRowHandle() {
    return this.RowHandle;
  }
}
