package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class ListViews_ViewMyListOfLabelRow {
  private String MyValueLabelText;
  public String getMyValueLabelText() {
    return this.MyValueLabelText;
  }
  private Boolean isMyValueLabelEnabled;
  public Boolean getIsMyValueLabelEnabled() {
    return this.isMyValueLabelEnabled;
  }
  private Boolean isMyValueLabelVisibility;
  public Boolean getIsMyValueLabelVisibility() {
    return this.isMyValueLabelVisibility;
  }
  private Integer RowIndex;
  public Integer getRowIndex() {
    return this.RowIndex;
  }
}
