package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public class ListViews_View {
  private Boolean isMyListOfLabelListVisibility;
  public Boolean getIsMyListOfLabelListVisibility() {
    return this.isMyListOfLabelListVisibility;
  }
  private Boolean isMyListOfLabelListEnabled;
  public Boolean getIsMyListOfLabelListEnabled() {
    return this.isMyListOfLabelListEnabled;
  }
  private List<ListViews_ViewMyListOfLabelRow> MyListOfLabelListWidgetListRows = new LinkedList<>();
  public List<ListViews_ViewMyListOfLabelRow> getMyListOfLabelListWidgetListRows() {
    return this.MyListOfLabelListWidgetListRows;
  }
  private Integer MyListOfLabelListSelectedRow;
  public Integer getMyListOfLabelListSelectedRow() {
    return this.MyListOfLabelListSelectedRow;
  }
  private Boolean isMyListOfImagesListVisibility;
  public Boolean getIsMyListOfImagesListVisibility() {
    return this.isMyListOfImagesListVisibility;
  }
  private Boolean isMyListOfImagesListEnabled;
  public Boolean getIsMyListOfImagesListEnabled() {
    return this.isMyListOfImagesListEnabled;
  }
  private List<ListViews_ViewMyListOfImagesRow> MyListOfImagesListWidgetListRows = new LinkedList<>();
  public List<ListViews_ViewMyListOfImagesRow> getMyListOfImagesListWidgetListRows() {
    return this.MyListOfImagesListWidgetListRows;
  }
  private Integer MyListOfImagesListSelectedRow;
  public Integer getMyListOfImagesListSelectedRow() {
    return this.MyListOfImagesListSelectedRow;
  }
  private List<ListViews_ViewMyCheckboxesRow> MyCheckboxesListWidgetListRows = new LinkedList<>();
  public List<ListViews_ViewMyCheckboxesRow> getMyCheckboxesListWidgetListRows() {
    return this.MyCheckboxesListWidgetListRows;
  }
  private Integer MyCheckboxesListSelectedRow;
  public Integer getMyCheckboxesListSelectedRow() {
    return this.MyCheckboxesListSelectedRow;
  }
  private Boolean isMyCheckboxesListVisibility;
  public Boolean getIsMyCheckboxesListVisibility() {
    return this.isMyCheckboxesListVisibility;
  }
  private Boolean isMyCheckboxesListEnabled;
  public Boolean getIsMyCheckboxesListEnabled() {
    return this.isMyCheckboxesListEnabled;
  }
  private List<ListViews_ViewMyStringRowHandlesRow> MyStringRowHandlesListWidgetListRows = new LinkedList<>();
  public List<ListViews_ViewMyStringRowHandlesRow> getMyStringRowHandlesListWidgetListRows() {
    return this.MyStringRowHandlesListWidgetListRows;
  }
  private String MyStringRowHandlesListSelectedRow;
  public String getMyStringRowHandlesListSelectedRow() {
    return this.MyStringRowHandlesListSelectedRow;
  }
  private List<ListViews_ViewMyListWithMultiRowSelectionRow> MyListWithMultiRowSelectionListWidgetListRows = new LinkedList<>();
  public List<ListViews_ViewMyListWithMultiRowSelectionRow> getMyListWithMultiRowSelectionListWidgetListRows() {
    return this.MyListWithMultiRowSelectionListWidgetListRows;
  }
  private List<Integer> MyListWithMultiRowSelectionListSelectedRows = new LinkedList<>();
  public List<Integer> getMyListWithMultiRowSelectionListSelectedRows() {
    return this.MyListWithMultiRowSelectionListSelectedRows;
  }
}
