package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class ListViews_ViewModelTestSetupImpl extends ListViews_ViewModelTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public void SetEmptyContext() {
  }
  @Override
  public ListViews_ViewModel BuildSut() {
    return null;
  }

}
