package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class ListViews_ViewMyListOfLabelRow {
  private String My_TextText;
  public String getMy_TextText() {
    return this.My_TextText;
  }
  private Boolean isMy_TextEnabled;
  public Boolean getIsMy_TextEnabled() {
    return this.isMy_TextEnabled;
  }
  private Boolean isMy_TextVisibility;
  public Boolean getIsMy_TextVisibility() {
    return this.isMy_TextVisibility;
  }
  private Integer RowIndex;
  public Integer getRowIndex() {
    return this.RowIndex;
  }
}
