package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class ListViews_ViewMyButtonsRow {
  private String ButtonsButtonText;
  public String getButtonsButtonText() {
    return this.ButtonsButtonText;
  }
  private String RowHandle;
  public String getRowHandle() {
    return this.RowHandle;
  }
}
