package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class ListViews_ViewMyListOfImagesRow {
  private String My_ImageImageSource;
  public String getMy_ImageImageSource() {
    return this.My_ImageImageSource;
  }
  private Boolean isMy_ImageEnabled;
  public Boolean getIsMy_ImageEnabled() {
    return this.isMy_ImageEnabled;
  }
  private Boolean isMy_ImageVisibility;
  public Boolean getIsMy_ImageVisibility() {
    return this.isMy_ImageVisibility;
  }
  private Integer RowIndex;
  public Integer getRowIndex() {
    return this.RowIndex;
  }
}
