package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public abstract class LowLevelFields_ViewModelTestEnvironment {
  public abstract void Init();
  public abstract LowLevelFields_ViewModel BuildSut();
}
