package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public class LowLevelFields_ViewModelCustomTableRowFieldRow {
  private String HeaderLabelText;
  public String getHeaderLabelText() {
    return this.HeaderLabelText;
  }
  public Boolean AdditionalBool;
  public Boolean getAdditionalBool() {
    return this.AdditionalBool;
  }
  public List<MyRowAdditions> AdditionalCustomElements = new LinkedList<>();
  public List<MyRowAdditions> getAdditionalCustomElements() {
    return this.AdditionalCustomElements;
  }
  private String RowHandle;
  public String getRowHandle() {
    return this.RowHandle;
  }
}
