package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class LowLevelFields_ViewContextProviderImpl extends LowLevelFields_ViewContextProvider {
  @Override
  public void Init() {
  }
  @Override
  public LowLevelFields_View BuildSut() {
    return null;
  }
}
