package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public class LowLevelFields_ViewModel {
  public Boolean MyBool;
  public Boolean getMyBool() {
    return this.MyBool;
  }
  public Integer MyInt;
  public Integer getMyInt() {
    return this.MyInt;
  }
  public String MyString;
  public String getMyString() {
    return this.MyString;
  }
  public List<String> MyStrings = new LinkedList<>();
  public List<String> getMyStrings() {
    return this.MyStrings;
  }
  public MyAdditions MyAdditions;
  public MyAdditions getMyAdditions() {
    return this.MyAdditions;
  }
  private List<LowLevelFields_ViewModelCustomTableRowFieldRow> CustomTableRowFieldTableRows = new LinkedList<>();
  public List<LowLevelFields_ViewModelCustomTableRowFieldRow> getCustomTableRowFieldTableRows() {
    return this.CustomTableRowFieldTableRows;
  }
  private List<LowLevelFields_ViewModelCustomListRowFieldRow> CustomListRowFieldListRows = new LinkedList<>();
  public List<LowLevelFields_ViewModelCustomListRowFieldRow> getCustomListRowFieldListRows() {
    return this.CustomListRowFieldListRows;
  }
  private List<LowLevelFields_ViewModelCustomTreeRowFieldRow> CustomTreeRowFieldTreeRows = new LinkedList<>();
  public List<LowLevelFields_ViewModelCustomTreeRowFieldRow> getCustomTreeRowFieldTreeRows() {
    return this.CustomTreeRowFieldTreeRows;
  }
}
