package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class LowLevelFields_ViewModelTestSetupImpl extends LowLevelFields_ViewModelTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public LowLevelFields_ViewModel BuildSut() {
    return null;
  }
}
