package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public abstract class LowLevelFields_ViewTestSetup {
  public abstract void Init();
  public abstract LowLevelFields_View BuildSut();
}
