package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class LowLevelFields_ViewModelCustomTreeRowFieldRow {
  private String HeaderLabelText;
  public String getHeaderLabelText() {
    return this.HeaderLabelText;
  }
  private Integer AdditionalInt;
  public Integer getAdditionalInt() {
    return this.AdditionalInt;
  }
  private String RowHandle;
  public String getRowHandle() {
    return this.RowHandle;
  }
  private Integer RowDepth;
  public Integer getRowDepth() {
    return this.RowDepth;
  }
}
