package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class LowLevelFields_ViewModelTestEnvironmentImpl extends LowLevelFields_ViewModelTestEnvironment {
  @Override
  public void Init() {
  }
  @Override
  public LowLevelFields_ViewModel BuildSut() {
    return null;
  }
}
