package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class RadioButton_View {
  private RadioButton_ViewOptionsOption OptionsRadioButtonGroupSelectedEntry;
  public RadioButton_ViewOptionsOption getOptionsRadioButtonGroupSelectedEntry() {
    return this.OptionsRadioButtonGroupSelectedEntry;
  }
  private Boolean isOptionsRadioButtonGroupVisible;
  public Boolean getIsOptionsRadioButtonGroupVisible() {
    return this.isOptionsRadioButtonGroupVisible;
  }
  private Boolean isOptionsRadioButtonGroupEnabled;
  public Boolean getIsOptionsRadioButtonGroupEnabled() {
    return this.isOptionsRadioButtonGroupEnabled;
  }
  private Boolean isOptionBRadioButtonVisible;
  public Boolean getIsOptionBRadioButtonVisible() {
    return this.isOptionBRadioButtonVisible;
  }
  private Boolean isOptionBRadioButtonEnabled;
  public Boolean getIsOptionBRadioButtonEnabled() {
    return this.isOptionBRadioButtonEnabled;
  }
  private Boolean isOptionCRadioButtonVisible;
  public Boolean getIsOptionCRadioButtonVisible() {
    return this.isOptionCRadioButtonVisible;
  }
  private Boolean isOptionCRadioButtonEnabled;
  public Boolean getIsOptionCRadioButtonEnabled() {
    return this.isOptionCRadioButtonEnabled;
  }
}
