package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class RadioButton_ViewContextProviderImpl extends RadioButton_ViewContextProvider {
  public void Init() {
  }
  public RadioButton_View BuildSut() {
    return null;
  }
}
