package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public abstract class RadioButton_ViewTestSetup {
  public abstract void Init();
  public abstract RadioButton_View BuildSut();
}
