package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class RadioButton_ViewTestSetupImpl extends RadioButton_ViewTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public RadioButton_View BuildSut() {
    return null;
  }
}
