package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public abstract class RadioButton_ViewModelTestEnvironment {
  public abstract void Init();
  public abstract RadioButton_ViewModel BuildSut();
}
