package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class TableViews_ViewMyElementsRow {
  private Boolean isIncludeCheckBoxChecked;
  public Boolean getIsIncludeCheckBoxChecked() {
    return this.isIncludeCheckBoxChecked;
  }
  private String NameLabelText;
  public String getNameLabelText() {
    return this.NameLabelText;
  }
  private String DescriptionLabelText;
  public String getDescriptionLabelText() {
    return this.DescriptionLabelText;
  }
  private String InfoIconImageImageSource;
  public String getInfoIconImageImageSource() {
    return this.InfoIconImageImageSource;
  }
  private Integer RowIndex;
  public Integer getRowIndex() {
    return this.RowIndex;
  }
}
