package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public class TableViews_ViewModel {
  private List<TableViews_ViewModelMyElementsRow> MyElementsTableRows = new LinkedList<>();
  public List<TableViews_ViewModelMyElementsRow> getMyElementsTableRows() {
    return this.MyElementsTableRows;
  }
  private Integer MyElementsTableSelectedRow;
  public Integer getMyElementsTableSelectedRow() {
    return this.MyElementsTableSelectedRow;
  }
  private Boolean isMyElementsTableVisible;
  public Boolean getIsMyElementsTableVisible() {
    return this.isMyElementsTableVisible;
  }
  private Boolean isMyElementsTableEnabled;
  public Boolean getIsMyElementsTableEnabled() {
    return this.isMyElementsTableEnabled;
  }
  private Boolean isMyElementsTableDescriptionColumnVisible;
  public Boolean getIsMyElementsTableDescriptionColumnVisible() {
    return this.isMyElementsTableDescriptionColumnVisible;
  }
  private List<TableViews_ViewModelMyStringRowHandleRow> MyStringRowHandleTableRows = new LinkedList<>();
  public List<TableViews_ViewModelMyStringRowHandleRow> getMyStringRowHandleTableRows() {
    return this.MyStringRowHandleTableRows;
  }
  private String MyStringRowHandleTableSelectedRow;
  public String getMyStringRowHandleTableSelectedRow() {
    return this.MyStringRowHandleTableSelectedRow;
  }
  private List<TableViews_ViewModelMyStringMultiRowHandlesRow> MyStringMultiRowHandlesTableRows = new LinkedList<>();
  public List<TableViews_ViewModelMyStringMultiRowHandlesRow> getMyStringMultiRowHandlesTableRows() {
    return this.MyStringMultiRowHandlesTableRows;
  }
  private List<String> MyStringMultiRowHandlesTableSelectedRows = new LinkedList<>();
  public List<String> getMyStringMultiRowHandlesTableSelectedRows() {
    return this.MyStringMultiRowHandlesTableSelectedRows;
  }
  private List<TableViews_ViewModelFirstColumnRowHandleRow> FirstColumnRowHandleTableRows = new LinkedList<>();
  public List<TableViews_ViewModelFirstColumnRowHandleRow> getFirstColumnRowHandleTableRows() {
    return this.FirstColumnRowHandleTableRows;
  }
  private String FirstColumnRowHandleTableSelectedRow;
  public String getFirstColumnRowHandleTableSelectedRow() {
    return this.FirstColumnRowHandleTableSelectedRow;
  }
  private List<TableViews_ViewModelFirstColumnMultiRowHandleRow> FirstColumnMultiRowHandleTableRows = new LinkedList<>();
  public List<TableViews_ViewModelFirstColumnMultiRowHandleRow> getFirstColumnMultiRowHandleTableRows() {
    return this.FirstColumnMultiRowHandleTableRows;
  }
  private List<String> FirstColumnMultiRowHandleTableSelectedRows = new LinkedList<>();
  public List<String> getFirstColumnMultiRowHandleTableSelectedRows() {
    return this.FirstColumnMultiRowHandleTableSelectedRows;
  }
}
