package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public abstract class TableViews_ViewTestSetup {
  public abstract void Init();
  public abstract void SetEmptyContext();
  public abstract TableViews_View BuildSut();
}
