package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class TableViews_ViewTestSetupImpl extends TableViews_ViewTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public void SetEmptyContext() {
  }
  @Override
  public TableViews_View BuildSut() {
    return null;
  }
}
