package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public abstract class TableViews_ViewModelTestSetup {
  public abstract void Init();
  public abstract void SetEmptyContext();
  public abstract TableViews_ViewModel BuildSut();
}
