package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public class TableViews_ViewModel {
  private List<TableViews_ViewModelMyElementsRow> MyElementsTableRows = new LinkedList<>();
  public List<TableViews_ViewModelMyElementsRow> getMyElementsTableRows() {
    return this.MyElementsTableRows;
  }
  private Integer MyElementsTableSelectedRow;
  public Integer getMyElementsTableSelectedRow() {
    return this.MyElementsTableSelectedRow;
  }
  private Boolean isMyElementsTableVisible;
  public Boolean getIsMyElementsTableVisible() {
    return this.isMyElementsTableVisible;
  }
  private Boolean isMyElementsTableEnabled;
  public Boolean getIsMyElementsTableEnabled() {
    return this.isMyElementsTableEnabled;
  }
  private Boolean isMyElementsTableDescriptionColumnVisible;
  public Boolean getIsMyElementsTableDescriptionColumnVisible() {
    return this.isMyElementsTableDescriptionColumnVisible;
  }
  private List<TableViews_ViewModelMyStringRowHandlesRow> MyStringRowHandlesTableRows = new LinkedList<>();
  public List<TableViews_ViewModelMyStringRowHandlesRow> getMyStringRowHandlesTableRows() {
    return this.MyStringRowHandlesTableRows;
  }
  private String MyStringRowHandlesTableSelectedRow;
  public String getMyStringRowHandlesTableSelectedRow() {
    return this.MyStringRowHandlesTableSelectedRow;
  }
}
