package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class TableViews_ViewMyStringRowHandlesRow {
  private String ValuesLabelText;
  public String getValuesLabelText() {
    return this.ValuesLabelText;
  }
  private String RowHandle;
  public String getRowHandle() {
    return this.RowHandle;
  }
}
