package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public class TableViews_View {
  private List<TableViews_ViewMyTableViewRow> MyTableViewWidgetTableRows = new LinkedList<>();
  public List<TableViews_ViewMyTableViewRow> getMyTableViewWidgetTableRows() {
    return this.MyTableViewWidgetTableRows;
  }
  private Integer MyTableViewSelectedRow;
  public Integer getMyTableViewSelectedRow() {
    return this.MyTableViewSelectedRow;
  }
  private Boolean isMyTableViewVisibility;
  public Boolean getIsMyTableViewVisibility() {
    return this.isMyTableViewVisibility;
  }
  private Boolean isMyTableViewEnabled;
  public Boolean getIsMyTableViewEnabled() {
    return this.isMyTableViewEnabled;
  }
  private List<TableViews_ViewMyStringRowHandlesRow> MyStringRowHandlesWidgetTableRows = new LinkedList<>();
  public List<TableViews_ViewMyStringRowHandlesRow> getMyStringRowHandlesWidgetTableRows() {
    return this.MyStringRowHandlesWidgetTableRows;
  }
  private String MyStringRowHandlesSelectedRow;
  public String getMyStringRowHandlesSelectedRow() {
    return this.MyStringRowHandlesSelectedRow;
  }
}
