package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class TableViews_ViewModelTestSetupImpl extends TableViews_ViewModelTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public void SetEmptyContext() {
  }
  @Override
  public TableViews_ViewModel BuildSut() {
    return null;
  }

}
