package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class TableViews_ViewContextProviderImpl extends TableViews_ViewContextProvider {
  @Override
  public void Init() {
  }
  @Override
  public void SetEmptyContext() {
  }
  @Override
  public TableViews_View BuildSut() {
    return null;
  }
}
