package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public abstract class TextBoxes_ViewTestSetup {
  public abstract void Init();
  public abstract void SetEmptyContext();
  public abstract TextBoxes_View BuildSut();
}
