package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class TextBoxes_ViewContextProvider {
  public void Init() {
  }
  public void SetEmptyContext() {
  }
  public TextBoxes_View BuildSut() {
    return null;
  }
}
