package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class TextBoxes_ViewTestSetupImpl extends TextBoxes_ViewTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public void SetEmptyContext() {
  }
  @Override
  public TextBoxes_View BuildSut() {
    return null;
  }
}
