package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class TreeViews_ViewMyTreeViewRow {
  private Boolean isIncludeChecked;
  public Boolean getIsIncludeChecked() {
    return this.isIncludeChecked;
  }
  private String NameText;
  public String getNameText() {
    return this.NameText;
  }
  private String DescriptionText;
  public String getDescriptionText() {
    return this.DescriptionText;
  }
  private String InfoIconImageSource;
  public String getInfoIconImageSource() {
    return this.InfoIconImageSource;
  }
  private Integer RowIndex;
  public Integer getRowIndex() {
    return this.RowIndex;
  }
  private Integer RowDepth;
  public Integer getRowDepth() {
    return this.RowDepth;
  }
}
