package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class TreeViews_ViewModelTestSetupImpl extends TreeViews_ViewModelTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public void SetEmptyContext() {
  }
  @Override
  public TreeViews_ViewModel BuildSut() {
    return null;
  }

}
