package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public class TreeViews_ViewModel {
  private Integer MyTreeViewElementsTreeSelectedRow;
  public Integer getMyTreeViewElementsTreeSelectedRow() {
    return this.MyTreeViewElementsTreeSelectedRow;
  }
  private Boolean isMyTreeViewElementsTreeVisible;
  public Boolean getIsMyTreeViewElementsTreeVisible() {
    return this.isMyTreeViewElementsTreeVisible;
  }
  private Boolean isMyTreeViewElementsTreeEnabled;
  public Boolean getIsMyTreeViewElementsTreeEnabled() {
    return this.isMyTreeViewElementsTreeEnabled;
  }
  private List<TreeViews_ViewModelMyTreeViewElementsRow> MyTreeViewElementsTreeRows = new LinkedList<>();
  public List<TreeViews_ViewModelMyTreeViewElementsRow> getMyTreeViewElementsTreeRows() {
    return this.MyTreeViewElementsTreeRows;
  }
  private Boolean isMyTreeViewElementsTreeDescriptionColumnVisible;
  public Boolean getIsMyTreeViewElementsTreeDescriptionColumnVisible() {
    return this.isMyTreeViewElementsTreeDescriptionColumnVisible;
  }
  private List<TreeViews_ViewModelMyStringRowHandlesRow> MyStringRowHandlesTreeRows = new LinkedList<>();
  public List<TreeViews_ViewModelMyStringRowHandlesRow> getMyStringRowHandlesTreeRows() {
    return this.MyStringRowHandlesTreeRows;
  }
  private String MyStringRowHandlesTreeSelectedRow;
  public String getMyStringRowHandlesTreeSelectedRow() {
    return this.MyStringRowHandlesTreeSelectedRow;
  }
  private List<TreeViews_ViewModelMyParentIndexRowHandlesRow> MyParentIndexRowHandlesTreeRows = new LinkedList<>();
  public List<TreeViews_ViewModelMyParentIndexRowHandlesRow> getMyParentIndexRowHandlesTreeRows() {
    return this.MyParentIndexRowHandlesTreeRows;
  }
  private List<TreeViews_ViewModelMyParentStringRowHandlesRow> MyParentStringRowHandlesTreeRows = new LinkedList<>();
  public List<TreeViews_ViewModelMyParentStringRowHandlesRow> getMyParentStringRowHandlesTreeRows() {
    return this.MyParentStringRowHandlesTreeRows;
  }
}
