package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class TreeViews_ViewModelMyParentStringRowHandlesRow {
  private String ValuesLabelText;
  public String getValuesLabelText() {
    return this.ValuesLabelText;
  }
  private String RowHandle;
  public String getRowHandle() {
    return this.RowHandle;
  }
  private String ParentRowHandle;
  public String getParentRowHandle() {
    return this.ParentRowHandle;
  }
}
