package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class TreeViews_ViewMyStringRowHandlesRow {
  private String ValuesText;
  public String getValuesText() {
    return this.ValuesText;
  }
  private String RowHandle;
  public String getRowHandle() {
    return this.RowHandle;
  }
  private Integer RowDepth;
  public Integer getRowDepth() {
    return this.RowDepth;
  }
}
