package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class TreeViews_ViewMyParentIndexRowHandlesRow {
  private String ValuesText;
  public String getValuesText() {
    return this.ValuesText;
  }
  private Integer RowIndex;
  public Integer getRowIndex() {
    return this.RowIndex;
  }
  private Integer ParentRowIndex;
  public Integer getParentRowIndex() {
    return this.ParentRowIndex;
  }
}
