package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class TreeViews_ViewMyParentStringRowHandlesRow {
  private String ValuesText;
  public String getValuesText() {
    return this.ValuesText;
  }
  private String RowHandle;
  public String getRowHandle() {
    return this.RowHandle;
  }
  private String ParentRowHandle;
  public String getParentRowHandle() {
    return this.ParentRowHandle;
  }
}
