package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public abstract class TreeViews_ViewTestSetup {
  public abstract void Init();
  public abstract void SetEmptyContext();
  public abstract TreeViews_View BuildSut();
}
