package de.vimotest.sandbox.widgetassertions;

/*Generated by MPS */


public class TreeViews_ViewContextProviderImpl extends TreeViews_ViewContextProvider {
  public void Init() {
  }
  public void SetEmptyContext() {
  }
  public TreeViews_View BuildSut() {
    return null;
  }
}
