package de.vimotest.sandbox.commands;

/*Generated by MPS */


public class CheckCommand_ViewModelTestEnvironmentImpl extends CheckCommand_ViewModelTestEnvironment {
  @Override
  public void Init() {
  }
  @Override
  public CheckCommand_ViewModel BuildSut() {
    return null;
  }
}
