package de.vimotest.sandbox.commands;

/*Generated by MPS */


public class CheckCommand_ViewModelTestSetupImpl extends CheckCommand_ViewModelTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public CheckCommand_ViewModel BuildSut() {
    return null;
  }

}
