package de.vimotest.sandbox.commands;

/*Generated by MPS */


public abstract class CheckCommand_ViewContextProvider {
  public abstract void Init();
  public abstract CheckCommand_View BuildSut();
}
