package de.vimotest.sandbox.commands;

/*Generated by MPS */


public class CheckCommand_ViewContextProvider {
  public void Init() {
  }
  public CheckCommand_View BuildSut() {
    return null;
  }
}
