package de.vimotest.sandbox.commands;

/*Generated by MPS */


public class CheckCommand_View {
  private Boolean isMyCheckBox1Checked;
  public Boolean getIsMyCheckBox1Checked() {
    return this.isMyCheckBox1Checked;
  }
  private Boolean isMyCheckBox2Checked;
  public Boolean getIsMyCheckBox2Checked() {
    return this.isMyCheckBox2Checked;
  }
  public void MyCheckBox1Checked(Boolean isChecked) {
  }
  public void MyCheckBox2Checked(Boolean isChecked) {
  }
}
