package de.vimotest.sandbox.commands;

/*Generated by MPS */


public abstract class ClickCommand_ViewModelTestSetup {
  public abstract void Init();
  public abstract ClickCommand_ViewModel BuildSut();
}
