package de.vimotest.sandbox.commands;

/*Generated by MPS */


public class ClickCommand_ViewModelTestSetupImpl extends ClickCommand_ViewModelTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public ClickCommand_ViewModel BuildSut() {
    return null;
  }
}
