package de.vimotest.sandbox.commands;

/*Generated by MPS */


public abstract class ClickCommand_ViewModelTestEnvironment {
  public abstract void Init();
  public abstract ClickCommand_ViewModel BuildSut();
}
