package de.vimotest.sandbox.commands;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public class FillTextCommand_View {
  private String MyValueTextBoxText;
  public String getMyValueTextBoxText() {
    return this.MyValueTextBoxText;
  }
  private List<String> MyFreeValueComboBoxComboBoxEntries = new LinkedList<>();
  public List<String> getMyFreeValueComboBoxComboBoxEntries() {
    return this.MyFreeValueComboBoxComboBoxEntries;
  }
  private String MyFreeValueComboBoxSelectedEntry;
  public String getMyFreeValueComboBoxSelectedEntry() {
    return this.MyFreeValueComboBoxSelectedEntry;
  }
  private String MyFreeValueComboBoxText;
  public String getMyFreeValueComboBoxText() {
    return this.MyFreeValueComboBoxText;
  }
  public void myValueTextFilled(String text) {
  }
  public void myFreeValueTextFilled(String text) {
  }
}
