package de.vimotest.sandbox.commands;

/*Generated by MPS */


public class FillTextCommand_ViewModelTestEnvironmentImpl extends FillTextCommand_ViewModelTestEnvironment {
  @Override
  public void Init() {
  }
  @Override
  public FillTextCommand_ViewModel BuildSut() {
    return null;
  }
}
