package de.vimotest.sandbox.commands;

/*Generated by MPS */


public class FillTextCommand_ViewTestSetupImpl extends FillTextCommand_ViewTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public FillTextCommand_View BuildSut() {
    return null;
  }
}
