package de.vimotest.sandbox.commands;

/*Generated by MPS */


public class FillTextCommand_ViewContextProviderImpl extends FillTextCommand_ViewContextProvider {
  @Override
  public void Init() {
  }
  @Override
  public FillTextCommand_View BuildSut() {
    return null;
  }
}
