package de.vimotest.sandbox.commands;

/*Generated by MPS */


public class FillTextCommand_ViewModelTestSetupImpl extends FillTextCommand_ViewModelTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public FillTextCommand_ViewModel BuildSut() {
    return null;
  }

}
