package de.vimotest.sandbox.commands;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public class FillTextCommand_ViewModel {
  private String MyValueTextBoxText;
  public String getMyValueTextBoxText() {
    return this.MyValueTextBoxText;
  }
  private List<String> MyFreeValueComboBoxEntries = new LinkedList<>();
  public List<String> getMyFreeValueComboBoxEntries() {
    return this.MyFreeValueComboBoxEntries;
  }
  private String MyFreeValueComboBoxSelectedEntry;
  public String getMyFreeValueComboBoxSelectedEntry() {
    return this.MyFreeValueComboBoxSelectedEntry;
  }
  private String MyFreeValueComboBoxText;
  public String getMyFreeValueComboBoxText() {
    return this.MyFreeValueComboBoxText;
  }
  public void myValueTextBoxTextFilled(String text) {
  }
  public void myFreeValueComboBoxTextFilled(String text) {
  }
}
