package de.vimotest.sandbox.commands;

/*Generated by MPS */


public class GenericCommands_ViewModelTestSetupImpl extends GenericCommands_ViewModelTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public GenericCommands_ViewModel BuildSut() {
    return null;
  }
}
