package de.vimotest.sandbox.commands;

/*Generated by MPS */


public class GenericCommands_ViewContextProviderImpl extends GenericCommands_ViewContextProvider {
  @Override
  public void Init() {
  }
  @Override
  public GenericCommands_View BuildSut() {
    return null;
  }
}
