package de.vimotest.sandbox.commands;

/*Generated by MPS */


public abstract class GenericCommands_ViewContextProvider {
  public abstract void Init();
  public abstract GenericCommands_View BuildSut();
}
