package de.vimotest.sandbox.commands;

/*Generated by MPS */


public abstract class GenericCommands_ViewModelTestSetup {
  public abstract void Init();
  public abstract GenericCommands_ViewModel BuildSut();
}
