package de.vimotest.sandbox.commands;

/*Generated by MPS */

import java.util.List;

public class GenericCommands_ViewModel {
  public void myCommand(String Id, Boolean MyFlag, List<String> Names, CommandEnum EnumValue) {
  }

}
