package de.vimotest.sandbox.commands;

/*Generated by MPS */


public class LoadCommand_ViewModelTestSetupImpl extends LoadCommand_ViewModelTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public LoadCommand_ViewModel BuildSut() {
    return null;
  }

}
