package de.vimotest.sandbox.commands;

/*Generated by MPS */


public abstract class LoadCommand_ViewModelTestSetup {
  public abstract void Init();
  public abstract LoadCommand_ViewModel BuildSut();
}
