package de.vimotest.sandbox.commands;

/*Generated by MPS */


public class LoadCommand_ViewModelTestEnvironmentImpl extends LoadCommand_ViewModelTestEnvironment {
  @Override
  public void Init() {
  }
  @Override
  public LoadCommand_ViewModel BuildSut() {
    return null;
  }
}
