package de.vimotest.sandbox.commands;

/*Generated by MPS */


public class LoadCommand_ViewTestSetupImpl extends LoadCommand_ViewTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public LoadCommand_View BuildSut() {
    return null;
  }
}
