package de.vimotest.sandbox.commands;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public class RowBasedCommand_ViewMyComboBoxesRow {
  private List<String> FreeTextComboBoxesComboBoxEntries = new LinkedList<>();
  public List<String> getFreeTextComboBoxesComboBoxEntries() {
    return this.FreeTextComboBoxesComboBoxEntries;
  }
  private String FreeTextComboBoxesComboBoxSelectedEntry;
  public String getFreeTextComboBoxesComboBoxSelectedEntry() {
    return this.FreeTextComboBoxesComboBoxSelectedEntry;
  }
  private String FreeTextComboBoxesComboBoxText;
  public String getFreeTextComboBoxesComboBoxText() {
    return this.FreeTextComboBoxesComboBoxText;
  }
  private List<String> EntryComboBoxesComboBoxEntries = new LinkedList<>();
  public List<String> getEntryComboBoxesComboBoxEntries() {
    return this.EntryComboBoxesComboBoxEntries;
  }
  private String EntryComboBoxesComboBoxSelectedEntry;
  public String getEntryComboBoxesComboBoxSelectedEntry() {
    return this.EntryComboBoxesComboBoxSelectedEntry;
  }
  private Integer RowIndex;
  public Integer getRowIndex() {
    return this.RowIndex;
  }
}
