package de.vimotest.sandbox.commands;

/*Generated by MPS */


public class RowBasedCommand_ViewContextProviderImpl extends RowBasedCommand_ViewContextProvider {
  @Override
  public void Init() {
  }
  @Override
  public RowBasedCommand_View BuildSut() {
    return null;
  }
}
