package de.vimotest.sandbox.commands;

/*Generated by MPS */


public class RowBasedCommand_ViewModelMyFlagsRow {
  private Boolean isCheckboxesCheckBoxChecked;
  public Boolean getIsCheckboxesCheckBoxChecked() {
    return this.isCheckboxesCheckBoxChecked;
  }
  private Integer RowIndex;
  public Integer getRowIndex() {
    return this.RowIndex;
  }
}
