package de.vimotest.sandbox.commands;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public class RowBasedCommand_ViewModel {
  private List<RowBasedCommand_ViewModelMyFlagsRow> MyFlagsListRows = new LinkedList<>();
  public List<RowBasedCommand_ViewModelMyFlagsRow> getMyFlagsListRows() {
    return this.MyFlagsListRows;
  }
  private List<RowBasedCommand_ViewModelMyComboBoxesRow> MyComboBoxesTableRows = new LinkedList<>();
  public List<RowBasedCommand_ViewModelMyComboBoxesRow> getMyComboBoxesTableRows() {
    return this.MyComboBoxesTableRows;
  }
  private List<RowBasedCommand_ViewModelMyStandardControlsRow> MyStandardControlsTreeRows = new LinkedList<>();
  public List<RowBasedCommand_ViewModelMyStandardControlsRow> getMyStandardControlsTreeRows() {
    return this.MyStandardControlsTreeRows;
  }
  public void loadView() {
  }
  public void checkboxesChecked(Integer rowIndex, Boolean isChecked) {
  }
  public void freeTextComboBoxesEntrySelected(Integer rowIndex, String entryName) {
  }
  public void entryComboBoxesEntrySelected(Integer rowIndex, String entryName) {
  }
  public void textBoxesTextFilled(Integer rowIndex, String text) {
  }
  public void buttonsClicked(Integer rowIndex) {
  }
}
