package de.vimotest.sandbox.commands;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public class RowBasedCommand_View {
  private List<RowBasedCommand_ViewMyFlagsRow> MyFlagsListWidgetListRows = new LinkedList<>();
  public List<RowBasedCommand_ViewMyFlagsRow> getMyFlagsListWidgetListRows() {
    return this.MyFlagsListWidgetListRows;
  }
  private List<RowBasedCommand_ViewMyComboBoxesRow> MyComboBoxesTableWidgetTableRows = new LinkedList<>();
  public List<RowBasedCommand_ViewMyComboBoxesRow> getMyComboBoxesTableWidgetTableRows() {
    return this.MyComboBoxesTableWidgetTableRows;
  }
  private List<RowBasedCommand_ViewMyStandardControlsRow> MyStandardControlsTreeWidgetTreeRows = new LinkedList<>();
  public List<RowBasedCommand_ViewMyStandardControlsRow> getMyStandardControlsTreeWidgetTreeRows() {
    return this.MyStandardControlsTreeWidgetTreeRows;
  }
  public void loadView() {
  }
  public void checkboxesChecked(Integer rowIndex, Boolean isChecked) {
  }
  public void freeTextComboBoxesEntrySelected(Integer rowIndex, String entryName) {
  }
  public void entryComboBoxesEntrySelected(Integer rowIndex, String entryName) {
  }
  public void textBoxesTextFilled(Integer rowIndex, String text) {
  }
  public void buttonsClicked(Integer rowIndex) {
  }
}
