package de.vimotest.sandbox.commands;

/*Generated by MPS */


public abstract class RowBasedCommand_ViewModelTestSetup {
  public abstract void Init();
  public abstract RowBasedCommand_ViewModel BuildSut();
}
