package de.vimotest.sandbox.commands;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public class RowBasedCommand_ViewMyTableViewRow {
  private List<String> FreeTextComboBoxesComboBoxEntries = new LinkedList<>();
  public List<String> getFreeTextComboBoxesComboBoxEntries() {
    return this.FreeTextComboBoxesComboBoxEntries;
  }
  private String FreeTextComboBoxesSelectedEntry;
  public String getFreeTextComboBoxesSelectedEntry() {
    return this.FreeTextComboBoxesSelectedEntry;
  }
  private String FreeTextComboBoxesText;
  public String getFreeTextComboBoxesText() {
    return this.FreeTextComboBoxesText;
  }
  private List<String> EntryComboBoxesComboBoxEntries = new LinkedList<>();
  public List<String> getEntryComboBoxesComboBoxEntries() {
    return this.EntryComboBoxesComboBoxEntries;
  }
  private String EntryComboBoxesSelectedEntry;
  public String getEntryComboBoxesSelectedEntry() {
    return this.EntryComboBoxesSelectedEntry;
  }
  private Integer RowIndex;
  public Integer getRowIndex() {
    return this.RowIndex;
  }
}
