package de.vimotest.sandbox.commands;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public class RowBasedCommand_ViewMyComboBoxesRow {
  private List<String> FreeTextComboBoxesComboBoxComboBoxEntries = new LinkedList<>();
  public List<String> getFreeTextComboBoxesComboBoxComboBoxEntries() {
    return this.FreeTextComboBoxesComboBoxComboBoxEntries;
  }
  private String FreeTextComboBoxesComboBoxSelectedEntry;
  public String getFreeTextComboBoxesComboBoxSelectedEntry() {
    return this.FreeTextComboBoxesComboBoxSelectedEntry;
  }
  private String FreeTextComboBoxesComboBoxText;
  public String getFreeTextComboBoxesComboBoxText() {
    return this.FreeTextComboBoxesComboBoxText;
  }
  private List<String> EntryComboBoxesComboBoxComboBoxEntries = new LinkedList<>();
  public List<String> getEntryComboBoxesComboBoxComboBoxEntries() {
    return this.EntryComboBoxesComboBoxComboBoxEntries;
  }
  private String EntryComboBoxesComboBoxSelectedEntry;
  public String getEntryComboBoxesComboBoxSelectedEntry() {
    return this.EntryComboBoxesComboBoxSelectedEntry;
  }
  private Integer RowIndex;
  public Integer getRowIndex() {
    return this.RowIndex;
  }
}
