package de.vimotest.sandbox.commands;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public class RowBasedCommand_View {
  private List<RowBasedCommand_ViewMyListViewRow> MyListViewWidgetListRows = new LinkedList<>();
  public List<RowBasedCommand_ViewMyListViewRow> getMyListViewWidgetListRows() {
    return this.MyListViewWidgetListRows;
  }
  private Boolean isMyListViewUpdatingRowsFlag;
  public Boolean getIsMyListViewUpdatingRowsFlag() {
    return this.isMyListViewUpdatingRowsFlag;
  }
  private List<RowBasedCommand_ViewMyTableViewRow> MyTableViewWidgetTableRows = new LinkedList<>();
  public List<RowBasedCommand_ViewMyTableViewRow> getMyTableViewWidgetTableRows() {
    return this.MyTableViewWidgetTableRows;
  }
  private Boolean isMyTableViewUpdatingRowsFlag;
  public Boolean getIsMyTableViewUpdatingRowsFlag() {
    return this.isMyTableViewUpdatingRowsFlag;
  }
  private List<RowBasedCommand_ViewMyTreeViewRow> MyTreeViewWidgetTreeRows = new LinkedList<>();
  public List<RowBasedCommand_ViewMyTreeViewRow> getMyTreeViewWidgetTreeRows() {
    return this.MyTreeViewWidgetTreeRows;
  }
  private Boolean isMyTreeViewUpdatingRowsFlag;
  public Boolean getIsMyTreeViewUpdatingRowsFlag() {
    return this.isMyTreeViewUpdatingRowsFlag;
  }
  public void LoadView() {
  }
  public void CheckboxesChecked(Integer rowIndex, Boolean isChecked) {
  }
  public void FreeTextComboBoxesEntrySelected(Integer rowIndex, String entryName) {
  }
  public void EntryComboBoxesEntrySelected(Integer rowIndex, String entryName) {
  }
  public void TextBoxesTextFilled(Integer rowIndex, String text) {
  }
  public void ButtonsClicked(Integer rowIndex) {
  }
}
