package de.vimotest.sandbox.commands;

/*Generated by MPS */


public abstract class RowBasedCommand_ViewModelTestEnvironment {
  public abstract void Init();
  public abstract RowBasedCommand_ViewModel BuildSut();
}
