package de.vimotest.sandbox.commands;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public class RowBasedCommand_View {
  private List<RowBasedCommand_ViewMyFlagsRow> MyFlagsListRows = new LinkedList<>();
  public List<RowBasedCommand_ViewMyFlagsRow> getMyFlagsListRows() {
    return this.MyFlagsListRows;
  }
  private List<RowBasedCommand_ViewMyComboBoxesRow> MyComboBoxesTableRows = new LinkedList<>();
  public List<RowBasedCommand_ViewMyComboBoxesRow> getMyComboBoxesTableRows() {
    return this.MyComboBoxesTableRows;
  }
  private List<RowBasedCommand_ViewMyStandardControlsRow> MyStandardControlsTreeRows = new LinkedList<>();
  public List<RowBasedCommand_ViewMyStandardControlsRow> getMyStandardControlsTreeRows() {
    return this.MyStandardControlsTreeRows;
  }
  public void loadView() {
  }
  public void checkboxesChecked(Integer rowIndex, Boolean isChecked) {
  }
  public void freeTextComboBoxesEntrySelected(Integer rowIndex, String entryName) {
  }
  public void entryComboBoxesEntrySelected(Integer rowIndex, String entryName) {
  }
  public void textBoxesTextFilled(Integer rowIndex, String text) {
  }
  public void buttonsClicked(Integer rowIndex) {
  }
}
