package de.vimotest.sandbox.commands;

/*Generated by MPS */


public class SelectRowCommand_ViewMyStringRowHandleTableViewElementsRow {
  private String columnCellTableColumnText;
  public String getColumnCellTableColumnText() {
    return this.columnCellTableColumnText;
  }
  private String columnCellLabelText;
  public String getColumnCellLabelText() {
    return this.columnCellLabelText;
  }
  private String RowHandle;
  public String getRowHandle() {
    return this.RowHandle;
  }
}
