package de.vimotest.sandbox.commands;

/*Generated by MPS */


public class SelectEntryCommand_ViewContextProviderImpl extends SelectEntryCommand_ViewContextProvider {
  public void Init() {
  }
  public SelectEntryCommand_View BuildSut() {
    return null;
  }
}
