package de.vimotest.sandbox.commands;

/*Generated by MPS */


public class SelectEntryCommand_ViewModelTestEnvironmentImpl extends SelectEntryCommand_ViewModelTestEnvironment {
  @Override
  public void Init() {
  }
  @Override
  public SelectEntryCommand_ViewModel BuildSut() {
    return null;
  }
}
