package de.vimotest.sandbox.commands;

/*Generated by MPS */


public class SelectRowCommand_ViewModelMyTableViewElementsRow {
  private String columnCellLabelText;
  public String getColumnCellLabelText() {
    return this.columnCellLabelText;
  }
  private Integer RowIndex;
  public Integer getRowIndex() {
    return this.RowIndex;
  }
}
