package de.vimotest.sandbox.commands;

/*Generated by MPS */


public class SelectRowCommand_ViewMyStringHandleMultiSelectRowListViewRow {
  private String HeaderText;
  public String getHeaderText() {
    return this.HeaderText;
  }
  private String RowHandle;
  public String getRowHandle() {
    return this.RowHandle;
  }
}
