package de.vimotest.sandbox.commands;

/*Generated by MPS */


public class SelectEntryCommand_ViewModelTestSetupImpl extends SelectEntryCommand_ViewModelTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public SelectEntryCommand_ViewModel BuildSut() {
    return null;
  }

}
