package de.vimotest.sandbox.commands;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public class SelectEntryCommand_View {
  private List<String> MyComboBoxComboBoxEntries = new LinkedList<>();
  public List<String> getMyComboBoxComboBoxEntries() {
    return this.MyComboBoxComboBoxEntries;
  }
  private String MyComboBoxSelectedEntry;
  public String getMyComboBoxSelectedEntry() {
    return this.MyComboBoxSelectedEntry;
  }
  private List<String> MyRadioButtonRadioButtonChoices = new LinkedList<>();
  public List<String> getMyRadioButtonRadioButtonChoices() {
    return this.MyRadioButtonRadioButtonChoices;
  }
  private String MyRadioButtonSelectedEntry;
  public String getMyRadioButtonSelectedEntry() {
    return this.MyRadioButtonSelectedEntry;
  }
  public void myComboBoxEntrySelected(String entryName) {
  }
  public void myRadioButtonEntrySelected(String entryName) {
  }
}
