package de.vimotest.sandbox.commands;

/*Generated by MPS */


public abstract class SelectRowCommand_ViewContextProvider {
  public abstract void Init();
  public abstract SelectRowCommand_View BuildSut();
}
