package de.vimotest.sandbox.commands;

/*Generated by MPS */


public class SelectRowCommand_ViewMyIndexBasedMultiSelectRowListViewElementsRow {
  private String HeaderLabelText;
  public String getHeaderLabelText() {
    return this.HeaderLabelText;
  }
  private Integer RowIndex;
  public Integer getRowIndex() {
    return this.RowIndex;
  }
}
