package de.vimotest.sandbox.commands;

/*Generated by MPS */


public class SelectRowCommand_ViewTestSetupImpl extends SelectRowCommand_ViewTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public SelectRowCommand_View BuildSut() {
    return null;
  }
}
