package de.vimotest.sandbox.commands;

/*Generated by MPS */


public class SelectRowCommand_ViewMyTableViewElementsRow {
  private String columnCellTableColumnText;
  public String getColumnCellTableColumnText() {
    return this.columnCellTableColumnText;
  }
  private String columnCellLabelText;
  public String getColumnCellLabelText() {
    return this.columnCellLabelText;
  }
  private Integer RowIndex;
  public Integer getRowIndex() {
    return this.RowIndex;
  }
}
