package de.vimotest.sandbox.commands;

/*Generated by MPS */


public class SelectRowCommand_ViewContextProvider {
  public void Init() {
  }
  public SelectRowCommand_View BuildSut() {
    return null;
  }
}
