package de.vimotest.sandbox.commands;

/*Generated by MPS */


public abstract class SelectEntryCommand_ViewTestSetup {
  public abstract void Init();
  public abstract SelectEntryCommand_View BuildSut();
}
