package de.vimotest.sandbox.commands;

/*Generated by MPS */


public class SelectRowCommand_ViewModelMyStringRowHandleTableViewElementsRow {
  private String columnCellLabelText;
  public String getColumnCellLabelText() {
    return this.columnCellLabelText;
  }
  private String RowHandle;
  public String getRowHandle() {
    return this.RowHandle;
  }
}
