package de.vimotest.sandbox.commands;

/*Generated by MPS */


public class SelectRowCommand_ViewMyStringRowHandleListViewElementsRow {
  private String HeaderLabelText;
  public String getHeaderLabelText() {
    return this.HeaderLabelText;
  }
  private String RowHandle;
  public String getRowHandle() {
    return this.RowHandle;
  }
}
