package de.vimotest.sandbox.commands;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public class SelectRowCommand_ViewModel {
  private List<SelectRowCommand_ViewModelMyListViewElementsRow> MyListViewElementsListRows = new LinkedList<>();
  public List<SelectRowCommand_ViewModelMyListViewElementsRow> getMyListViewElementsListRows() {
    return this.MyListViewElementsListRows;
  }
  private Integer MyListViewElementsListSelectedRow;
  public Integer getMyListViewElementsListSelectedRow() {
    return this.MyListViewElementsListSelectedRow;
  }
  private List<SelectRowCommand_ViewModelMyStringRowHandleListViewElementsRow> MyStringRowHandleListViewElementsListRows = new LinkedList<>();
  public List<SelectRowCommand_ViewModelMyStringRowHandleListViewElementsRow> getMyStringRowHandleListViewElementsListRows() {
    return this.MyStringRowHandleListViewElementsListRows;
  }
  private String MyStringRowHandleListViewElementsListSelectedRow;
  public String getMyStringRowHandleListViewElementsListSelectedRow() {
    return this.MyStringRowHandleListViewElementsListSelectedRow;
  }
  private List<SelectRowCommand_ViewModelMyTableViewElementsRow> MyTableViewElementsTableRows = new LinkedList<>();
  public List<SelectRowCommand_ViewModelMyTableViewElementsRow> getMyTableViewElementsTableRows() {
    return this.MyTableViewElementsTableRows;
  }
  private Integer MyTableViewElementsTableSelectedRow;
  public Integer getMyTableViewElementsTableSelectedRow() {
    return this.MyTableViewElementsTableSelectedRow;
  }
  private List<SelectRowCommand_ViewModelMyStringRowHandleTableViewElementsRow> MyStringRowHandleTableViewElementsTableRows = new LinkedList<>();
  public List<SelectRowCommand_ViewModelMyStringRowHandleTableViewElementsRow> getMyStringRowHandleTableViewElementsTableRows() {
    return this.MyStringRowHandleTableViewElementsTableRows;
  }
  private String MyStringRowHandleTableViewElementsTableSelectedRow;
  public String getMyStringRowHandleTableViewElementsTableSelectedRow() {
    return this.MyStringRowHandleTableViewElementsTableSelectedRow;
  }
  private List<SelectRowCommand_ViewModelMyTreeViewElementsRow> MyTreeViewElementsTreeRows = new LinkedList<>();
  public List<SelectRowCommand_ViewModelMyTreeViewElementsRow> getMyTreeViewElementsTreeRows() {
    return this.MyTreeViewElementsTreeRows;
  }
  private Integer MyTreeViewElementsTreeSelectedRow;
  public Integer getMyTreeViewElementsTreeSelectedRow() {
    return this.MyTreeViewElementsTreeSelectedRow;
  }
  private List<SelectRowCommand_ViewModelMyStringRowHandleTreeViewElementsRow> MyStringRowHandleTreeViewElementsTreeRows = new LinkedList<>();
  public List<SelectRowCommand_ViewModelMyStringRowHandleTreeViewElementsRow> getMyStringRowHandleTreeViewElementsTreeRows() {
    return this.MyStringRowHandleTreeViewElementsTreeRows;
  }
  private String MyStringRowHandleTreeViewElementsTreeSelectedRow;
  public String getMyStringRowHandleTreeViewElementsTreeSelectedRow() {
    return this.MyStringRowHandleTreeViewElementsTreeSelectedRow;
  }
  private List<SelectRowCommand_ViewModelMyIndexBasedMultiSelectRowListViewElementsRow> MyIndexBasedMultiSelectRowListViewElementsListRows = new LinkedList<>();
  public List<SelectRowCommand_ViewModelMyIndexBasedMultiSelectRowListViewElementsRow> getMyIndexBasedMultiSelectRowListViewElementsListRows() {
    return this.MyIndexBasedMultiSelectRowListViewElementsListRows;
  }
  private List<Integer> MyIndexBasedMultiSelectRowListViewElementsListSelectedRows = new LinkedList<>();
  public List<Integer> getMyIndexBasedMultiSelectRowListViewElementsListSelectedRows() {
    return this.MyIndexBasedMultiSelectRowListViewElementsListSelectedRows;
  }
  private List<SelectRowCommand_ViewModelMyStringHandleMultiSelectRowListViewElementsRow> MyStringHandleMultiSelectRowListViewElementsListRows = new LinkedList<>();
  public List<SelectRowCommand_ViewModelMyStringHandleMultiSelectRowListViewElementsRow> getMyStringHandleMultiSelectRowListViewElementsListRows() {
    return this.MyStringHandleMultiSelectRowListViewElementsListRows;
  }
  private List<String> MyStringHandleMultiSelectRowListViewElementsListSelectedRows = new LinkedList<>();
  public List<String> getMyStringHandleMultiSelectRowListViewElementsListSelectedRows() {
    return this.MyStringHandleMultiSelectRowListViewElementsListSelectedRows;
  }
  public void myListViewElementsRowSelected(Integer rowIndex) {
  }
  public void myStringRowHandleListViewElementsRowSelected(String rowHandle) {
  }
  public void myTableViewElementsRowSelected(Integer rowIndex) {
  }
  public void myStringRowHandleTableViewElementsRowSelected(String rowHandle) {
  }
  public void myTreeViewElementsRowSelected(Integer rowIndex) {
  }
  public void myStringRowHandleTreeViewElementsRowSelected(String rowHandle) {
  }
  public void myIndexBasedMultiSelectRowListViewElementsRowSelected(List<Integer> rowIndices) {
  }
  public void myStringHandleMultiSelectRowListViewElementsRowSelected(List<String> rowHandles) {
  }
}
