package de.vimotest.sandbox.commands;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public class SelectRowCommand_View {
  private List<SelectRowCommand_ViewMyListViewRow> MyListViewWidgetListRows = new LinkedList<>();
  public List<SelectRowCommand_ViewMyListViewRow> getMyListViewWidgetListRows() {
    return this.MyListViewWidgetListRows;
  }
  private Integer MyListViewSelectedRow;
  public Integer getMyListViewSelectedRow() {
    return this.MyListViewSelectedRow;
  }
  private List<SelectRowCommand_ViewMyStringRowHandleListViewRow> MyStringRowHandleListViewWidgetListRows = new LinkedList<>();
  public List<SelectRowCommand_ViewMyStringRowHandleListViewRow> getMyStringRowHandleListViewWidgetListRows() {
    return this.MyStringRowHandleListViewWidgetListRows;
  }
  private String MyStringRowHandleListViewSelectedRow;
  public String getMyStringRowHandleListViewSelectedRow() {
    return this.MyStringRowHandleListViewSelectedRow;
  }
  private List<SelectRowCommand_ViewMyTableViewRow> MyTableViewWidgetTableRows = new LinkedList<>();
  public List<SelectRowCommand_ViewMyTableViewRow> getMyTableViewWidgetTableRows() {
    return this.MyTableViewWidgetTableRows;
  }
  private Integer MyTableViewSelectedRow;
  public Integer getMyTableViewSelectedRow() {
    return this.MyTableViewSelectedRow;
  }
  private List<SelectRowCommand_ViewMyStringRowHandleTableViewRow> MyStringRowHandleTableViewWidgetTableRows = new LinkedList<>();
  public List<SelectRowCommand_ViewMyStringRowHandleTableViewRow> getMyStringRowHandleTableViewWidgetTableRows() {
    return this.MyStringRowHandleTableViewWidgetTableRows;
  }
  private String MyStringRowHandleTableViewSelectedRow;
  public String getMyStringRowHandleTableViewSelectedRow() {
    return this.MyStringRowHandleTableViewSelectedRow;
  }
  private List<SelectRowCommand_ViewMyTreeViewRow> MyTreeViewWidgetTreeRows = new LinkedList<>();
  public List<SelectRowCommand_ViewMyTreeViewRow> getMyTreeViewWidgetTreeRows() {
    return this.MyTreeViewWidgetTreeRows;
  }
  private Integer MyTreeViewSelectedRow;
  public Integer getMyTreeViewSelectedRow() {
    return this.MyTreeViewSelectedRow;
  }
  private List<SelectRowCommand_ViewMyStringRowHandleTreeViewRow> MyStringRowHandleTreeViewWidgetTreeRows = new LinkedList<>();
  public List<SelectRowCommand_ViewMyStringRowHandleTreeViewRow> getMyStringRowHandleTreeViewWidgetTreeRows() {
    return this.MyStringRowHandleTreeViewWidgetTreeRows;
  }
  private String MyStringRowHandleTreeViewSelectedRow;
  public String getMyStringRowHandleTreeViewSelectedRow() {
    return this.MyStringRowHandleTreeViewSelectedRow;
  }
  private List<SelectRowCommand_ViewMyIndexBasedMultiSelectRowListViewRow> MyIndexBasedMultiSelectRowListViewWidgetListRows = new LinkedList<>();
  public List<SelectRowCommand_ViewMyIndexBasedMultiSelectRowListViewRow> getMyIndexBasedMultiSelectRowListViewWidgetListRows() {
    return this.MyIndexBasedMultiSelectRowListViewWidgetListRows;
  }
  private List<Integer> MyIndexBasedMultiSelectRowListViewSelectedRows = new LinkedList<>();
  public List<Integer> getMyIndexBasedMultiSelectRowListViewSelectedRows() {
    return this.MyIndexBasedMultiSelectRowListViewSelectedRows;
  }
  private List<SelectRowCommand_ViewMyStringHandleMultiSelectRowListViewRow> MyStringHandleMultiSelectRowListViewWidgetListRows = new LinkedList<>();
  public List<SelectRowCommand_ViewMyStringHandleMultiSelectRowListViewRow> getMyStringHandleMultiSelectRowListViewWidgetListRows() {
    return this.MyStringHandleMultiSelectRowListViewWidgetListRows;
  }
  private List<String> MyStringHandleMultiSelectRowListViewSelectedRows = new LinkedList<>();
  public List<String> getMyStringHandleMultiSelectRowListViewSelectedRows() {
    return this.MyStringHandleMultiSelectRowListViewSelectedRows;
  }
  public void myListViewRowSelected(Integer rowIndex) {
  }
  public void myStringRowHandleListViewRowSelected(String rowHandle) {
  }
  public void myTableViewRowSelected(Integer rowIndex) {
  }
  public void myStringRowHandleTableViewRowSelected(String rowHandle) {
  }
  public void myTreeViewRowSelected(Integer rowIndex) {
  }
  public void myStringRowHandleTreeViewRowSelected(String rowHandle) {
  }
  public void myIndexBasedMultiSelectRowListViewRowSelected(List<Integer> rowIndices) {
  }
  public void myStringHandleMultiSelectRowListViewRowSelected(List<String> rowHandles) {
  }
}
