package de.vimotest.sandbox.commands;

/*Generated by MPS */


public abstract class SelectRowCommand_ViewModelTestSetup {
  public abstract void Init();
  public abstract SelectRowCommand_ViewModel BuildSut();
}
