package de.vimotest.sandbox.commands;

/*Generated by MPS */


public class SelectRowCommand_ViewContextProviderImpl extends SelectRowCommand_ViewContextProvider {
  @Override
  public void Init() {
  }
  @Override
  public SelectRowCommand_View BuildSut() {
    return null;
  }
}
