package de.vimotest.sandbox.commands;

/*Generated by MPS */


public abstract class SelectEntryCommand_ViewContextProvider {
  public abstract void Init();
  public abstract SelectEntryCommand_View BuildSut();
}
