package de.vimotest.sandbox.commands;

/*Generated by MPS */


public class SelectRowCommand_ViewMyTreeViewElementsRow {
  private String columnCellLabelText;
  public String getColumnCellLabelText() {
    return this.columnCellLabelText;
  }
  private Integer RowIndex;
  public Integer getRowIndex() {
    return this.RowIndex;
  }
  private Integer RowDepth;
  public Integer getRowDepth() {
    return this.RowDepth;
  }
}
