package de.vimotest.sandbox.commands;

/*Generated by MPS */


public class SelectRowCommand_ViewMyStringRowHandleTableViewRow {
  private String columnCellText;
  public String getColumnCellText() {
    return this.columnCellText;
  }
  private String RowHandle;
  public String getRowHandle() {
    return this.RowHandle;
  }
}
