package de.vimotest.sandbox.commands;

/*Generated by MPS */


public class SelectRowCommand_ViewMyStringRowHandleTreeViewRow {
  private String columnCellText;
  public String getColumnCellText() {
    return this.columnCellText;
  }
  private String RowHandle;
  public String getRowHandle() {
    return this.RowHandle;
  }
  private Integer RowDepth;
  public Integer getRowDepth() {
    return this.RowDepth;
  }
}
