name: Bundle ViMoTest MPS

on:
  workflow_dispatch:

env:
  PROJECT_NAME: "mps-vimotest"
  ARTIFACT_NAME: "mps-vimotest"

jobs:
  call-build-workflow:
    uses: ./.github/workflows/workflow-build.yaml

  bundle:
    needs: call-build-workflow
    strategy:
      matrix:
        os: [windows-x64, osx-x64, osx-aarch64, linux-x64]
    uses: ./.github/workflows/workflow-base-mps-bundle.yaml
    with:
      os: ${{ matrix.os }}
